import re
ADD = {
99: ("**From the Greater to the Lesser: The Argument That Requires Only Sight**",
"""The verse opens with the interrogative that introduces the Qur’an’s most frequently used argument, and its form is significant: *a-wa lam yaraw* — have they not seen? The appeal is not to a text or a tradition but to observation, and the thing observed is the one nobody disputes. *Inna Allāha alladhī khalaqa al-samāwāti wa al-arḍa la-qādirun ʿalā an yakhluqa mithlahum* — God, Who created the heavens and the earth, is able to create the like of them. Al-Rāzī states the inference in its logical form: the one who originates the greater is able to originate the lesser, since the lesser requires nothing that the greater did not already require, and more.

The Qur’an uses the argument repeatedly and always in the same register. 36:81: *“Is not He Who created the heavens and the earth able to create the like of them? Yes indeed, and He is the All-Knowing Creator.”* 40:57 states the comparative explicitly: *“The creation of the heavens and the earth is greater than the creation of mankind, but most people know not.”* 79:27–28 supplies the premise in the form of a question: *“Are you the harder to create, or the heaven which He built?”* 46:33 poses it as a challenge: *“Do they not see that God, Who created the heavens and the earth and was not wearied by their creation, is able to give life to the dead? Yes indeed — He has power over all things.”*

The force of the argument lies in what it does not require. It does not require the listener to accept a cosmology, a physics, or a revelation; it requires only that he acknowledge that the heavens and the earth exist and that he did not make them. From that acknowledgment the conclusion follows by the ordinary logic of capacity, and 51:20–21 states the whole method: *“And on the earth are signs for those who are certain, and in yourselves — do you not see?”*

The verse’s second clause supplies the term and the refusal. *Wa jaʿala lahum ajalan lā rayba fīhi* — and He appointed for them a term about which there is no doubt. The commentators read the term either as the appointed moment of death, which no one doubts when it arrives, or as the Day of Resurrection, whose certainty the verse asserts against the denial of verses 49 and 98. The clause *fa-abā al-ẓālimūna illā kafūrā* — but the wrongdoers refuse, except in ingratitude — repeats the formula of verse 89 and closes the section with the same diagnosis: the evidence has been sufficient throughout, and the refusal is not a response to it.

The verse therefore completes the resurrection argument by relocating it. The question is not whether resurrection is conceivable but whether the Maker of the heavens and the earth is able — and anyone who answers the second question has answered the first. This is why the Qur’an’s eschatology is inseparable from its cosmology: the doctrine of the Hereafter stands or falls with the doctrine of creation, and the one who has never resolved the second has no ground on which to deny the first."""),

100: ("**The Treasuries of Mercy, and the Scarcity Projected Onto God**",
"""The verse is a psychological observation stated as a conditional, and its precision is what makes it memorable. *Qul law antum tamlikūna khazāʾina raḥmati rabbī idhan la-amsaktum khashyata al-infāq* — say: if you possessed the treasuries of my Lord’s mercy, you would surely withhold them, for fear of spending. The commentators note the reasoning given: the withholding is not from malice but from the fear of exhaustion, which is the reasoning of a creature who has watched his own stores diminish.

Al-Ṭabarī records the occasion: the Quraysh said to the Prophet ﷺ that his Lord was stingy, and the verse answered by locating the stinginess where it belonged. Al-Qurṭubī explains the mechanism the verse exposes: the human being measures God’s giving by his own, and since his own giving depletes him, he assumes the same of God. This is projection in the strict sense — the attribution of one’s own nature to another — and the Qur’an identifies it as the source of a specific theological error: a God imagined as a limited dispenser who must economize, and whose gifts are therefore competitive, so that a gift to one is a loss to another.

The verse’s answer is implicit in the word *khazāʾin*, treasuries, and the Qur’an states the inexhaustibility explicitly elsewhere. 18:109 gives the image: *“Say: if the sea were ink for the words of my Lord, the sea would be exhausted before the words of my Lord were exhausted, even if We brought the like of it as a further supply.”* 34:39 states the principle in the register of provision: *“And whatever you spend of a thing, He will replace it, and He is the best of providers.”* 57:29 supplies the conclusion: *“...that the people of the Book may know that they have no power over anything of God’s bounty, and that bounty is in the hand of God; He gives it to whom He wills.”*

The ethical consequence is direct, and 47:38 draws it: *“Here you are — those called upon to spend in the way of God; and among you are those who withhold. And whoever withholds withholds only from himself, and God is the Rich and you are the poor.”* The one who withholds from fear of scarcity has misidentified who is being depleted, since the depletion is his own and the supply is not.

The verse’s modern application requires no translation. Every system organized on the assumption that provision is finite produces hoarding, and the hoarding is then offered as evidence that provision was finite — the belief generating its own confirmation. The verse identifies the error at its root, which is not economic but theological: the assumption that the source is limited, and therefore that generosity is a loss. 3:180 states the inversion: *“Let not those who withhold what God has given them of His bounty think that it is good for them; nay, it is evil for them.”*"""),

101: ("**Nine Signs to One People, and the Verdict They Returned**",
"""The verse supplies the case study that answers the demands of verses 90–93, and it is the most sign-dense episode in the Qur’an. *Wa laqad ātaynā Mūsā tisʿa āyātin bayyināt* — and We gave Moses nine clear signs. Al-Ṭabarī catalogues the identifications from Ibn ʿAbbās and others: the staff, the white hand, the years of famine, the flood, the locusts, the lice, the frogs, the blood, and either the parting of the sea or the drowning of Pharaoh. The Qur’an enumerates the plagues at 7:130–133 and the two principal signs at 27:12 and 20:17–23, so the nine are assembled from several passages rather than listed in one.

The verse’s function is the comparison it forces. The people who received the greatest concentration of clear signs in the Qur’an’s recorded history did not believe, and the response they gave is recorded in the same breath: *fa-qāla lahu Firʿawnu innī la-aẓunnuka yā Mūsā masḥūrā* — and Pharaoh said to him: I think thee, O Moses, bewitched. The word is the same one used of the Prophet ﷺ at verse 47, and the identity of the accusation across three thousand years is the verse’s finding. 51:52 states the general rule: *“Likewise no messenger came to those before them but they said: a sorcerer, or a madman.”*

The comparison therefore answers the Quraysh’s demands completely. They asked for a spring, a garden, a house of gold, a ladder to heaven, and a piece of the sky; Moses was given a staff that became a serpent, a hand that shone white, and five plagues in succession, and the verdict returned was that he was bewitched. Al-Rāzī draws the conclusion: the quantity of signs does not determine the response, since the response is determined by the disposition that receives them. This is the same finding the sūrah reached at verses 59 and 89, now with a documented case.

The verse’s placement immediately after the statement about the treasuries of mercy is significant. Having established that God’s bounty is not depleted by giving, the sūrah shows that it is not *earned* by demanding either: the most spectacular giving in the record went to the people who most rejected it, and the rejection did not interrupt the giving until the appointed term arrived.

The practical consequence for the reader is a caution about the logic of demand. The person who will not believe until a condition is met has usually set a condition he will not honor, and the test of this is the history of his previous conditions. The Qur’an’s answer to such a person is not another sign but the record of what happened the last time."""),

102: ("**Baṣāʾir: The Signs That Give Sight, and the Seeing That Was Refused**",
"""The verse records Moses’s reply and in doing so names what the signs were. *Wa laqad ʿalimta mā anzala hāʾulāʾi illā rabbu al-samāwāti wa al-arḍi baṣāʾir* — and thou knowest that none sent down these except the Lord of the heavens and the earth, as clear evidences giving insight. The word *baṣāʾir* is the plural of *baṣīrah*, from the root of sight, and it denotes evidences so clear that they confer insight rather than merely presenting data. Al-Zamakhsharī notes the force of the word: a *baṣīrah* is not a thing to be looked at but a thing that makes one see.

The clause *wa laqad ʿalimta* — and thou knowest — is the verse’s most striking feature, since it attributes knowledge to Pharaoh. Al-Ṭabarī and Ibn Kathīr both hold that Moses is telling Pharaoh what Pharaoh already knows: that the signs came from God. The Qur’an states the same fact about Pharaoh and his people at 27:14, and the statement is a precise psychological claim: *“And they denied them, while their souls were certain of them (wa istayqanat-hā anfusuhum), out of wrongdoing and arrogance.”* The certainty was present and the denial was simultaneous with it, and the two causes named — *ẓulm*, wrongdoing, and *ʿulūww*, arrogance — locate the denial in the will rather than in the intellect.

The reply Pharaoh gives is the verse’s confirmation of its own thesis: *wa innī la-aẓunnuka yā Mūsā mathbūrā* — and I think thee, O Moses, destroyed, ruined. The word *mathbūr* is from *th-b-r*, and the commentators gloss it as one cut off from good, or annihilated, or turned away from the truth. The response to certainty is not argument but a prediction of the certain man’s destruction, which is what a person says when he has nothing to say.

The verse’s function in the sūrah is to complete the case begun at verse 101. The signs were given; they were *baṣāʾir*, evidences that confer sight; they were recognized by the one who rejected them; and the rejection proceeded anyway. The Qur’an therefore establishes that the obstacle to faith is not epistemic, and it establishes this not by assertion but by the testimony of the rejecter himself. 6:110 states the general mechanism: *“And We shall turn their hearts and their sight, as they did not believe in it the first time, and We shall leave them in their insolence, wandering blindly.”*

The practical content of the verse is its account of what happens when a person recognizes a truth he does not intend to accept. He does not become uncertain; he becomes dismissive, and the dismissal takes the form of a prediction about the one who speaks. Anyone who has watched this exchange recognizes it immediately, and the verse supplies its name: the soul was certain, and the wrongdoing and the arrogance were what spoke."""),

103: ("**The Attempted Expulsion of Moses, and the Rule It Confirms**",
"""The verse completes the case study, and its verb is the one that ties it to the sūrah’s own situation. *Fa-arāda an yastafizzahum min al-arḍ* — and he intended to drive them out of the land. The verb *yastafizz* is the same one used at verse 76 of the Quraysh’s intention toward the Prophet ﷺ: *wa in kādū la-yastafizzūnaka min al-arḍ*. The lexical identity is not incidental; it is the sūrah’s method of establishing that the two cases are instances of one pattern.

The outcome is stated in the same breath: *fa-aghraqnāhu wa man maʿahu jamīʿā* — so We drowned him and all who were with him. The verse does not elaborate, since the story was already known to its audience in full; it supplies only the outcome, because the outcome is what the pattern requires. Al-Qurṭubī notes that the drowning is mentioned here rather than the plagues because it is the completion of the expulsion: the one who attempted to drive out the messenger was removed from the land himself.

The verse’s function is to confirm the *sunnah* stated at verses 76 and 77. The rule was given first — a people who expels its messenger will not remain after it except a little, and thou wilt find no change in the way of God — and the case is given second, so that the rule is not an assertion but a generalization from a documented instance. This is the Qur’an’s historical method throughout: it states the pattern and then supplies the evidence, and it does so in that order because the pattern is what the reader needs in order to read the evidence correctly.

The parallel between the two cases is close enough to be itemized. In both, the messenger was told to produce material proofs he could not produce. In both, he was accused of being bewitched. In both, the opponents proposed his expulsion. In both, the expulsion was attempted and the expellers were removed. The one difference is the one the sūrah has already explained at verse 59: the destruction of the Quraysh was withheld so that they might believe, and most of them did.

The verse therefore supplies what the argument of verses 90–98 required — not another sign but a precedent. The reader who has followed the demands, the objection to the messenger’s humanity, and the denial of the resurrection is given a case in which all three occurred together and the outcome is recorded. 40:21 states the method as an instruction: *“Have they not traveled in the earth and seen what was the end of those who were before them? They were greater than them in strength and in the traces they left in the earth, but God seized them for their sins, and they had no defender against God.”*"""),

104: ("**Dwell in the Land, and the Gathering of the Lafīf**",
"""The verse records the promise given after the drowning, and its two clauses describe two returns. *Wa qulnā min baʿdihī li-banī Isrāʾīla skunū al-arḍa* — and We said after him to the Children of Israel: dwell in the land. Al-Ṭabarī explains the command as the settlement in the land from which Pharaoh had attempted to expel them, which completes the reversal the previous verse established: the expellers drowned and the expelled inherited.

The second clause is the verse’s difficult and much-discussed part: *fa-idhā jāʾa waʿdu al-ākhirati jiʾnā bikum lafīfā* — and when the promise of the Hereafter comes, We shall bring you as a *lafīf*. The word *lafīf* denotes a mingled multitude, groups brought together from different places and mixed, and al-Qurṭubī glosses it as assembled from various lands, none of them remaining where they were. The exegetes divided over which promise is meant. One reading, held by a number of the Salaf, takes *waʿdu al-ākhirah* as the second of the two corruptions and returns described at verses 4–8 of this sūrah, so that the verse describes a historical gathering. The other, favored by Ibn Kathīr, takes it as the Day of Resurrection, in which case the gathering is the general one and the word *lafīf* describes the mixed assembly of all peoples.

The two readings are not mutually exclusive, and the Qur’an’s use of the phrase *waʿdu al-ākhirah* elsewhere supports both. 17:7 uses *waʿdu al-ākhirah* of a historical event, and 30:43 and 20:15 use the parallel phrase of the Day. Al-Rāzī’s resolution is that the verse is deliberately general, and that the mingled gathering described is true of the historical return and of the final one, since both involve the assembling of a dispersed people.

The verse’s function within the sūrah is to close the account of Moses begun at verse 101. The sequence — the nine signs, the accusation of sorcery, the attempted expulsion, the drowning, the settlement, and the final gathering — is a complete narrative in six verses, and it is given at this point because it is the evidence for the *sunnah* stated at verses 76–77. The reader has been told the rule and shown the instance, and the instance is now brought to its conclusion.

The practical content of the verse is its account of reversal. The people driven out of a land were settled in it, and the one who drove them out was removed — which is the pattern the sūrah promised would repeat. 28:5–6 states the same promise in its fullest form: *“And We desired to confer a favor upon those who were oppressed in the earth, and to make them leaders, and to make them the inheritors, and to establish them in the earth.”*"""),

105: ("**Bi-l-Ḥaqqi Nazalnā wa bi-l-Ḥaqqi Nazal: The Two Truths of Descent**",
"""The verse makes a claim about the revelation in a doubled formula, and the doubling has been read precisely by the grammarians. *Wa bi-l-ḥaqqi anzalnāhu wa bi-l-ḥaqqi nazal* — and with the truth We sent it down, and with the truth it came down. Al-Zamakhsharī distinguishes the two: the first *bi-l-ḥaqq* describes the sending, meaning that it was sent for a true purpose and with true content; the second describes the arrival, meaning that it came down unchanged, having lost nothing and gained nothing in the descent. Al-Qurṭubī adds a third reading: that it descended with truth in the sense that its descent was accompanied by the evidences of its truth — the signs, the angels, and the confirmation in the hearts of the believers.

The claim is therefore twofold and both parts are necessary. A revelation could be true in content and corrupted in transmission, or faithful in transmission and empty in content; the verse asserts both, and the second assertion is the one the Qur’an makes most insistently elsewhere. 15:9 states it as a promise: *“Indeed, We sent down the Reminder, and indeed We are its guardians.”* 41:42 states it as a description: *“Falsehood approaches it not from before it nor from behind it — a revelation from the Wise, the Praised.”* 85:21–22 supplies the shortest form: *“Nay, it is a glorious Qur’an, in a Preserved Tablet.”*

The second clause limits the office and completes the verse: *wa mā arsalnāka illā mubashshiran wa nadhīrā* — and We sent thee only as a bringer of good news and a warner. The two verbal nouns are the Qur’an’s standard pair for the prophetic function, and the particle *illā* restricts the office to them. The verse therefore makes the same delimitation the sūrah made at verse 54 and will make at verse 105’s close: the messenger conveys, and the outcome is not his. 34:28 states the same limit: *“And We sent thee not except to all mankind, as a bringer of good news and a warner — but most people know not.”*

The pairing of the two clauses is what gives the verse its force. The revelation is described as true in its origin and in its arrival, and the one who carries it is described as limited in his function. The two statements together prevent the two opposite errors: the message is not diminished by the messenger’s limitation, and the messenger is not elevated by the message’s truth. This is the structure the entire sūrah has maintained, from the *ʿabd* of verse 1 to the *basharan rasūlā* of verse 91.

The verse’s practical consequence is a rule for reading and for teaching. The authority of the message is not derived from the one who conveys it, so a weak conveyor does not weaken it and a strong one does not strengthen it; and the conveyor’s duty is defined by the two nouns — to give good news and to warn — neither of which includes compelling the response. 88:21–22 states the limit in its plainest form: *“So remind; thou art only a reminder. Thou art not a dictator over them.”*"""),

106: ("**Faradnāhu: The Deliberate Pace of the Revelation**",
"""The verse describes the manner of the revelation, and its two verbs are both technical. *Wa Qurʾānan faradnāhu* — and a Qur’an which We have apportioned, divided. The verb *faraḍa* denotes the apportioning of a thing into determined shares, as in the fixed shares of inheritance, and al-Ṭabarī glosses it as divided into commands and prohibitions, promises and warnings, narratives and parables. The second verb supplies the manner: *wa nazzalnāhu tanzīlā* — and We sent it down by degrees, the doubled form and the cognate accusative both emphasizing the gradualness.

The Qur’an states the reason for the gradualness explicitly at 25:32: *“And those who disbelieve say: why was not the Qur’an sent down to him all at once? Thus — that We may thereby make thy heart firm; and We have recited it in measured recitation (wa rattalnāhu tartīlā).”* The reasoning is given in two parts, and both concern formation rather than information. The heart is made firm by what is received in portions, since a revelation delivered all at once would be a weight the recipient could not carry and a text the community could not absorb. 2:106 supplies the second reason: the abrogation and replacement of rulings across the period, which allowed the law to be built in stages — the prohibition of alcohol is the standard case, delivered across three stages in three separate revelations.

Al-Rāzī draws the pedagogical principle, and it is a general one: a community is formed by a text delivered over time rather than by a text delivered complete, because formation requires the interval in which the material is practiced. The historical fact is the evidence: the revelation came across twenty-three years, and the community that received it was not the same at the end as at the beginning. The sūrah’s own placement of the prayer times at verse 78, in the middle of an argument, is an instance of the method — legislation arrives inside the polemic because the formation of the worshipper is the point of the argument.

The verse’s practical application extends beyond the revelation. Any body of knowledge that must change a person rather than merely inform him is better delivered in portions with intervals for practice than all at once, and the intervals are not delays but the mechanism. The tradition formalized this in the reports about the Companions learning ten verses at a time and not proceeding until they had learned the knowledge and the action contained in them — a practice that treats the interval as the substance of the learning.

The verse therefore supplies the answer to a question the sūrah has already encountered: why the revelation did not come with a single overwhelming sign. It came instead in measured portions across twenty-three years, and the result was a transformation that a sign could not have produced."""),

107: ("**Falling Upon the Chins: The Response of Those Who Were Given Knowledge**",
"""The verse describes the response of a specific group to the recitation, and the description is physical. *Wa yakhirrūna li-l-adhqāni sujjadan* — and they fall down upon their chins, prostrating. The word *adhqān* is the plural of *dhaqan*, the chin, and the image is of a prostration so complete that the face reaches the ground — al-Qurṭubī notes that the chin is mentioned as the part that touches first, indicating the speed and the completeness of the fall. The verb *yakhirrūn* denotes falling with force, not lowering oneself.

The two accompanying states complete the description: *wa yabkūn*, and they weep; *wa yazīduhum khushūʿā*, and it increases them in humility. The word *khushūʿ* denotes the humility that combines inward submission with outward stillness, and the Qur’an uses it of the heart, the voice, the eyes, and the posture. The verse’s claim is that the recitation *increases* it, which makes humility a quantity that grows with exposure rather than a state one arrives at.

The verse specifies who the group is: *alladhīna ūtū al-ʿilm min qablih*, those who were given knowledge before it. Al-Ṭabarī and Ibn Kathīr identify them as the believers among the People of the Book who recognized the Qur’an, and 5:83 describes their response in the same terms: *“And when they hear what was sent down to the Messenger, thou seest their eyes overflow with tears because of the truth they recognize. They say: our Lord, we believe, so write us down among the witnesses.”* 26:197–199 makes the same point about knowledge: *“Is it not a sign for them that the scholars of the Children of Israel know it? And if We had revealed it to one of the foreigners and he had recited it to them, they would not have believed in it.”*

The contrast within the sūrah is what gives the verse its force. Verses 41, 45, and 46 described the response of those who turned away — the veil, the coverings, the deafness, the turning of the back. This verse describes the response of those who received: the fall, the weeping, the increase in humility. The two descriptions are of the same recitation, and the difference is in the receiver, which is the finding the sūrah reached at verse 82: the same text is a healing for the believers and an increase in loss for the wrongdoers.

The verse’s practical content is a diagnostic. The measure of a person’s relation to the revelation is not his information about it but his physical and emotional response to hearing it, and the response the verse describes is available to anyone who listens. 39:23 states the same effect: *“God has sent down the best of speech, a Book consistent, repeating, at which the skins of those who fear their Lord shiver; then their skins and their hearts soften to the remembrance of God.”*"""),

108: ("**The Promise Fulfilled: The Confession That Completes the Prostration**",
"""The verse continues the description of verse 107 and supplies the words the prostrators speak. *Wa yaqūlūna subḥāna rabbinā in kāna waʿdu rabbinā la-mafʿūlā* — and they say: glory be to our Lord; truly the promise of our Lord is fulfilled. The sequence is significant: the prostration and the weeping come first, and the confession follows them, which is the Qur’an’s characteristic order — the recognition arrives through the body before it is articulated.

The formula has two parts, and each does distinct work. *Subḥāna rabbinā* is the glorification with which the sūrah began at verse 1, and its return here closes a structural circle: the sūrah opened with the glorification of the One who carried His servant by night, and it reaches this verse with the glorification of those who received what was carried. The confession *in kāna waʿdu rabbinā la-mafʿūlā* uses the emphatic *in* with the *lām* of affirmation, and the word *mafʿūl* denotes a thing that is done and completed, not merely promised.

Al-Qurṭubī explains what the promise refers to: the promise of the revelation’s truth, of the resurrection, and of the outcome for those who believed — all of which the hearers had been told and had not seen. The confession is therefore made by people who have now seen the fulfillment, and 5:83 records it in the same situation: *“What is wrong with us that we should not believe in God and in the truth that has come to us, when we hope that our Lord will admit us among the righteous?”*

The verse’s placement after the account of the gradual revelation at verse 106 is significant. The revelation came in portions across twenty-three years, and those who received it in portions are the ones who weep at its completion — which is the sūrah’s answer to the demand for a single overwhelming sign. The sign would have produced submission without transformation; the gradual revelation produced the response this verse describes.

The practical content of the verse is the sequence it models. The correct response to the recognition of a fulfilled promise is not argument but glorification, and the glorification is accompanied by the acknowledgment that the promise was sure from the beginning — *in kāna*, truly it was. This is the disposition of one who has waited and been vindicated, and it is available to anyone who has held to a promise through the interval in which it looked unfilled. 30:6 states the principle on which the confidence rests: *“The promise of God — God does not fail in His promise, but most people know not.”*"""),

109: ("**The Names Are Many and the Essence Is One**",
"""The verse is the Qur’an’s clearest statement of the doctrine of the divine names, and the occasion recorded for it is specific. Al-Ṭabarī preserves the report that the Prophet ﷺ was heard calling upon God in prayer by the names *al-Raḥmān* and *al-Raḥīm*, and that some of the polytheists objected that he claimed to worship one God while calling upon two. The verse answers by refusing the premise: *quli dʿū Allāha awi dʿū al-Raḥmān ayyan mā tadʿū fa-lahu al-asmāʾ al-ḥusnā* — say: call upon God or call upon al-Raḥmān; whichever you call, His are the most beautiful names.

The grammatical construction *ayyan mā tadʿū* is one of the most compressed in the Qur’an, and al-Zamakhsharī explains it as *whichever of them you call*, the *mā* being an intensifier attached to the interrogative. The clause therefore does not distinguish between the names at all: the invocation is identical whichever name is used, because the named is one. This is the doctrine of *tawḥīd al-asmāʾ wa al-ṣifāt* in a single sentence — the names are many, the named is one, and the multiplicity of the names does not divide the essence.

The Qur’an states the same doctrine at 7:180: *“And to God belong the most beautiful names, so call upon Him by them, and leave those who deviate concerning His names — they will be requited for what they did.”* 59:22–24 enumerates a series of them and closes with *“He is God, the Creator, the Maker, the Fashioner; His are the most beautiful names.”* The ḥadīth literature supplies the enumeration:

> *“God has ninety-nine names, a hundred less one. Whoever preserves them (aḥṣāhā) will enter Paradise.”* (al-Bukhārī 2736; Muslim 2677)

The word *aḥṣāhā* has been explained by the scholars as more than memorization: it denotes knowing them, understanding what each denotes, and acting accordingly — calling upon God by the name appropriate to the request, which is the practice the verse commands.

The theological content of the verse is what distinguishes Islamic monotheism from the alternatives it addresses. The multiplicity of names is not a multiplicity of deities, since each name denotes an attribute of one essence; and the attributes are not additions to the essence, since they are what the essence is. The verse’s practical consequence is a rule for prayer: the supplicant should name what he is asking for by the divine name that answers it, which turns invocation from a general appeal into a specific address.

The verse’s placement at the close of the sūrah is significant. The final verses are a doxology — glorification, prostration, and the naming of God — and this verse supplies the vocabulary for the naming. The sūrah began with *subḥān* and ends with the names by which the glorified is called."""),

110: ("**Neither Loud Nor Low: The Commanded Middle in Recitation**",
"""The verse is a command about the volume of prayer, and the occasion recorded for it is one of the most specific in the sūrah. Al-Bukhārī (4722) and Muslim (446) record from Ibn ʿAbbās that the verse was revealed in Makkah when the Prophet ﷺ would raise his voice in prayer and the polytheists, hearing the Qur’an, would revile it and its revealer and the One who sent it; he then lowered his voice to the point where his Companions behind him could not hear, and the verse commanded the middle.

> *“The verse was revealed concerning the prayer: he would raise his voice in recitation, and when the polytheists heard it they reviled the Qur’an and the One who revealed it; so God said to His Prophet: do not raise your voice in prayer, that they may not revile it, and do not lower it, that your Companions may not be unable to hear — and seek a way between that.”* (al-Bukhārī 4722)

The two terms are precise. *Tajhar*, from *j-h-r*, denotes the raising of the voice to full openness; *tukhāfit*, from *kh-f-t*, denotes the lowering of it to the point where it is barely audible. The command is *wa btaghi bayna dhālika sabīlā* — seek a way between the two — and the verb *ibtaghā* denotes the active search for a middle rather than the passive acceptance of a compromise.

Al-Ṭabarī records the alternative reading of the word *ṣalāh* here as denoting supplication (*duʿāʾ*) rather than the ritual prayer, on the strength of 40:60, *“Call upon Me and I will answer you,”* and of the Arabic usage in which *ṣalāh* and *duʿāʾ* are interchangeable. On that reading the verse commands the middle in supplication, and the jurists hold both readings, since the ruling applies to the ritual prayer and to the invocation outside it.

The verse’s significance extends beyond volume. It states the principle of the middle (*wasat*) in a concrete case, and the Qur’an applies the principle to the community as a whole at 2:143: *“And thus We have made you a middle nation.”* The specific application here is to a situation in which both extremes were errors with real consequences: the loud recitation produced blasphemy from the hearers, and the quiet one deprived the Companions of hearing. The middle was therefore not a compromise between two preferences but the only option that avoided two harms.

The practical application is general and the reasoning transfers directly. A person conveying a message must calibrate not only the content but the volume, and the calibration is determined by the effect on both parties — those who would be provoked by the excess and those who would be deprived by the deficiency. The verse supplies the rule and the reason in a single sentence, which is why the jurists derived from it not merely a ruling on volume but a principle about delivery."""),

111: ("**The Verse of Might: Four Negations and One Command**",
"""The sūrah closes with a declaration that the tradition calls *āyat al-ʿizz*, the verse of might, and its structure is four negations followed by a single command. *Wa quli al-ḥamdu li-Allāhi alladhī lam yattakhidh waladā* — and say: praise belongs to God, Who has taken no son. The first negation answers the Christian claim and the pre-Islamic Arab claim about the angels, and the Qur’an addresses both at 19:88–92 and 37:149–153. The word *yattakhidh* is from the form denoting the taking of a thing for oneself, so the negation is not merely that God has no son but that He did not take one — the claim is about an act that never occurred.

The second negation answers the polytheism of partnership: *wa lam yakun lahu sharīkun fī al-mulk*, and there is no partner with Him in dominion. The specification *fī al-mulk* is significant, since it denies partnership in sovereignty rather than merely in worship — the one who has no share in God’s rule cannot be a partner in any sense. The third negation is the subtlest: *wa lam yakun lahu walīyun mina al-dhulli*, and He has no protector from abasement. Al-Ṭabarī explains it as the denial of an ally taken out of need, which is the only reason a being takes an ally; God has allies by His choice and not by His need, and the distinction is what separates the Islamic conception from the pagan one, in which the gods require support.

The command that closes the verse is the sūrah’s final word and its structural completion: *wa kabbirhu takbīrā* — and magnify Him greatly. The doubled form *kabbir* with the cognate accusative *takbīrā* produces the same intensive construction used at verse 43, *ʿuluwwan kabīrā*, and the circle closes: the sūrah opened with *subḥāna alladhī asrā bi-ʿabdih*, glory to the One who carried His servant, and closes with the command to magnify the One who has no son, no partner, and no need.

The verse’s placement is therefore not incidental. The entire sūrah has been an argument for *tawḥīd* — against the attribution of children to God (vv. 40–41), against the invocation of intermediaries (vv. 56–57), against the elevation of the messenger to a share in divine power (v. 91), and against the claim that the revelation competes with God (v. 111) — and the final verse states the conclusion in the form in which it is to be held: not as a proposition but as a praise.

The practical content of the verse is that the doctrine ends in doxology. The four negations are not a metaphysical system but the removal of four obstacles to the praise, and the command that follows them is the sūrah’s actual destination. The tradition read it accordingly, and the verse became part of the daily liturgy: the formula *Allāhu akbar*, the magnification the verse commands, opens the prayer and closes it, and is uttered at every transition in the worshipper’s day. The sūrah that began with a journey ends with the word by which the journey into prayer is begun."""),
}
import re as _re
p='expanded/017.md'
s=open(p,encoding='utf-8').read()
parts=_re.split(r'(?m)^(## Sūrah al-Isrāʾ 17:\d+)$', s)
d={int(parts[i].split(':')[1]):[parts[i],parts[i+1]] for i in range(1,len(parts),2)}
for n,(h,t) in ADD.items():
    body=d[n][1]
    hs=[m.start() for m in _re.finditer(r'(?m)^\*\*(?!Expanded Commentary).+?\*\*$', body)]
    assert hs, n
    ins=hs[-1]
    d[n][1]=body[:ins]+'**'+h+'**\n\n'+t.strip()+'\n\n'+body[ins:]
out=[parts[0]]
for i in range(1,len(parts),2):
    n=int(parts[i].split(':')[1]); out.append(d[n][0]); out.append(d[n][1])
open(p,'w',encoding='utf-8').write(''.join(out))
print('added',len(ADD),'| words now',len(''.join(out).split()))
