import re
ADD = {
1: ("**Iltifāt: The Verse That Refuses to Tell a Story**",
"""The verse’s grammar is itself an argument, and the classical rhetoricians (ahl al-balāghah) read it as such. It opens with a verbless nominal exclamation — *subḥāna alladhī asrā* — not with *idh* (“when”) or *wa* (“and”), and therefore never enters narrative time at all. A story has a beginning, a middle, and a listener’s judgment suspended until the end; a declaration of transcendence has none of these, and the listener is positioned as a witness rather than a judge before the first fact arrives. Then comes the *iḍāfah* of honor: *bi-ʿabdihi*, “His servant,” a possessive construction in which the possessed is dignified by the Possessor — the same device that gives *baytu Allāh* its sanctity and *ʿilm Allāh* its authority. Al-Zamakhsharī notes that the Prophet ﷺ is not named, and that the omission is the point: the title selected is the one that cannot be inflated.

Most striking is the *iltifāt* — the sudden turn of grammatical person that Arabic rhetoric treats as a device for arresting attention. The verse begins in the third person, *“Glory be to Him Who carried His servant,”* speaking of God at a distance, and then turns without warning into the first person plural: *“whose precincts **We** have blessed,”* *“that **We** might show him some of Our signs.”* The speaker steps forward from behind the description. The effect is not decorative. The journey is being removed from the register of reported event, where a hearer may accept or decline, and placed in the register of direct speech, where the Agent is present and speaking. Al-Rāzī’s comment on the structure is that the verse establishes the Majesty before it establishes the miracle, because a miracle reported about an absent party can be argued with, while a miracle announced by the Actor cannot."""),

2: ("**Wakīl, Walī, Mawlā, Nāṣir: The Qur’an’s Vocabulary of Reliance**",
"""The command in this verse sits inside a network of four Qur’anic terms that together map the human heart’s dependencies, and reading them together clarifies what the Torah actually forbade. The *wakīl* is the one to whom affairs are entrusted for disposal; the *walī* is the one who is near and who protects, and it is the term used of God’s relationship to the believers at 2:257 — *“God is the Walī of those who believe; He brings them out of darkness into light.”* The *mawlā* is the patron and master, as at 3:150 — *“God is your Mawlā, and He is the best of helpers.”* The *naṣīr* is the one who gives victory in conflict. Ibn ʿĀshūr observes that the Qur’an’s prohibitions of shirk are almost always phrased in terms of these relational words rather than in terms of ritual, because the error they target is relational: it is the placement of trust, not the performance of a rite.

The practical test the vocabulary supplies is diagnostic and requires no theology. Ask what a person turns to first when frightened, and the answer names the *wakīl*. Ask whom a person fears disappointing most, and the answer names the *mawlā*. Ask whose approval a person would abandon a principle to keep, and the answer names the *walī*. Al-Qurṭubī’s formulation is that the heart’s *tawakkul* is the truest index of its creed, and that a tongue may profess unity while the heart has quietly constituted a partnership — which is why the Torah’s command, as this verse quotes it, is addressed not to the hands but to the reliance behind them."""),

3: ("**Noah as the Second Adam: Why the Ark Is Called a Carrying**",
"""The verse’s choice of *ḥamala* — to carry — does more than describe rescue, and the exegetes have long noticed that the Qur’an treats the flood as a second creation. The first human being was formed from clay and given life; the second beginning came through water, and the handful carried upon the planks became the ancestors of everyone since. Al-Ṭabarī connects the verse to 37:77, *“And We made his progeny the survivors (al-bāqīn)”* — a formulation the early commentators read literally: all subsequent humanity descends from those aboard. The passenger of a vessel contributes nothing to the vessel’s flotation, which is precisely the theological point the Children of Israel are being made to recall: their genealogy is a genealogy of the carried, not of the capable.

The Prophetic tradition fixes Noah’s rank in a report that also explains why this sūrah reaches back to him. In the long ḥadīth of intercession recorded by al-Bukhārī (4712) and Muslim (194), humanity on the Day of Judgment goes first to Adam, who declines, and then:

> *“They come to Noah and say: 'O Noah, you are the first of the messengers God sent to the people of the earth, and God named you a grateful servant.'”* (al-Bukhārī 4712)

Two of the three titles in this verse — first messenger, and *ʿabd shakūr* — are the same two the tradition assigns him, which is why the commentators treat verse 3 as a Qur’anic confirmation of a report the community already held. The pairing also supplies the moral logic of what follows: the man who was carried was grateful, and the descendants who were carried are being warned that forgetting the carriage is what precedes the drowning."""),

4: ("**Qaḍā: One Verb, Three Registers of Divine Speech**",
"""The verb *qaḍā* is one of the most theologically loaded in the Qur’an, and its range explains why the commentators divided over this verse. It can mean to decree irrevocably, as at 41:12, *“And He decreed (fa-qaḍāhunna) seven heavens in two days”*; it can mean to command, as at 2:117, *“When He decrees a matter (qaḍā amran), He says only 'Be,' and it is”*; and it can mean to inform or announce a judgment, as here, where al-Ṭabarī reads it as God’s having communicated the future to Israel through the Torah itself. Ibn ʿĀshūr argues for the third reading on contextual grounds: the phrase *fī al-kitāb* — “in the Book” — is attached to the verb, and a decree recorded in the Preserved Tablet would not need to be described as being “in the Book” that Israel possessed.

The distinction matters for a reason the classical theologians pressed. If the two corruptions were written in the Torah, then Israel received them as a *warning*, and a warning presupposes the capacity to avert. The classical doctrine of the two tablets supplies the framework: 13:39, *“God erases what He wills and establishes, and with Him is the Mother of the Book”* — the *Umm al-Kitāb*, the unchanging decree, alongside a register in which matters are recorded conditionally and may be altered by repentance. ʿUmar ibn al-Khaṭṭāb’s reported supplication makes the point existentially: *“O God, if Thou hast written me among the wretched, erase it, for Thou erasest what Thou willest and establishest.”* Whether one takes al-Ṭabarī’s reading or al-Qurṭubī’s, the verse’s function is identical: Israel was told in advance, in its own scripture, and could not claim surprise."""),

5: ("**Jāsū: A Word Used Once, and Why**",
"""The verb *jāsa* occurs exactly once in the entire Qur’an, and the singularity is worth pausing over. Its sense is not simply to attack but to move back and forth through an interior space — to range between the houses, searching. The Qur’an elsewhere describes destruction from outside: the wind that levels (46:25, *“destroying everything by the command of its Lord, so that they became such that nothing was seen save their dwellings”*), the cry that overtakes (11:67), the stones that descend (11:82). None of those verbs puts the destroyers *inside* the quarters. Al-Zamakhsharī notes that the choice conveys occupation rather than bombardment: the enemy is in the streets, at the doors, in the rooms.

This is why the object is *al-diyār* — the dwellings, the homes — and not the city, the walls, or the temple. The Qur’an could have said *fa-dammarnā madīnatahum*; it says instead that they ranged through the dwellings. Devastation that reaches the interior of the house is total in a way that devastation of the perimeter is not, because the home is where a people’s ordinary life is stored: the meal, the sleep, the naming of children, the privacy that makes a community something other than a population. Ibn Kathīr’s catalogue of what the reports include — the plunder, the desecration, the burning of the Torah, the killing of its readers — describes the sequence in which a civilization loses itself: first the place of worship, then the book, then the people who can read it. The verse compresses all three into a single verb of interior movement, and the singularity of that verb is the measure of what it describes."""),

6: ("**Imdād: Reinforcement, Not Mere Giving**",
"""The verb *amdada* is chosen with precision, and it differs from the ordinary verb of giving. *Aʿṭā* means to hand over; *razaqa* means to provide; *amdada* means to extend support to one already engaged — to send reinforcements. The Qur’an uses it of military aid at 3:124, *“Your Lord will reinforce you (mumiddukum) with three thousand angels sent down,”* and at 8:9, and of increase in general at 23:55 and 7:201. When it is used of the restoration of Israel here, it implies that the wealth and the children arrived as *strategic support* to a people being rebuilt, not as undirected bounty. The exegetes note the consequence without needing to state it: reinforcements given for a purpose become an indictment if converted to another use, which is exactly the transition from verse 6 to the second rising of verse 4.

The three gifts named — wealth, children, numbers — are the Qur’an’s standard inventory of worldly strength, and their recurrence is deliberate. 3:14 lists them as the objects of beautified desire: *“Beautified for mankind is the love of desires — women, sons, heaped-up heaps of gold and silver.”* 18:46 makes them the definition of this world’s adornment: *“Wealth and sons are the adornment of the life of this world, but the enduring good deeds are better with thy Lord in reward and better in hope.”* 8:28 warns that they are a trial: *“And know that your wealth and your children are a trial (fitnah), and that with God is a tremendous reward.”* The verse therefore reads as a restoration and a setup at once. The turn has been given; the instruments of strength have been supplied; and the sūrah has already shown, eight verses earlier, what the same instruments produced the first time."""),

7: ("**Why the devastators Are Not Named**",
"""One of the most instructive features of this passage is what it declines to say. The agents of both devastations are never identified, and the exegetes who supply names — Goliath, Sennacherib, Nebuchadnezzar, the Romans — do so from outside the text, with al-Rāzī and Ibn Kathīr both flagging that the reports conflict and that the chronology is confused. This is not an oversight in the revelation; it is its method. A named enemy can be resented, studied, blamed, and eventually forgotten as a historical episode. An unnamed agent forces the reader to look at the *condition* that summoned him. The Qur’an’s interest is not in who burned the Temple but in what made the burning possible, which is why verse 7 inserts the moral rule before describing the event.

The rule is stated in a construction of exacting symmetry: *in aḥsantum aḥsantum li-anfusikum wa in asaʾtum fa-lahā*. The verb of doing good is repeated with a reflexive beneficiary — you do good *for your own souls* — and the verb of doing evil is followed by a pronoun that the grammarians read as referring back to the same souls: you do evil *against them*. Al-Rāzī draws the inference that the moral order is therefore not a system of divine accounting but a description of what souls are: acts do not travel outward to affect God, who is beyond increase and diminishment, but inward, inscribing themselves in the actor. The verse at 55:60 states the principle as a rhetorical question that admits no answer: *“Is the reward of goodness aught but goodness?”* And 41:46 settles the question of the Agent’s stake in the transaction: *“Whoever does right, it is for his own soul; and whoever does evil, it is against it. And thy Lord is not unjust to the servants.”*"""),

8: ("**Ḥaṣīr: The Prison and the Bed**",
"""The final word of the verse, *ḥaṣīrā*, carries two meanings in Arabic that the commentators preserve rather than choose between, and both are theologically useful. From *ḥ-ṣ-r*, to confine and restrict, it gives a place of imprisonment — Hell as *siijn*, the term the Qur’an uses at 83:7 for the register of the wicked. From the same root comes the woven mat, that which is spread out and upon which one lies, and al-Qurṭubī connects it to 7:41, *“They shall have a bed (mihād) of Hell, and over them coverings (ghawāshin).”* The two senses are not in competition; they are the same image. The inhabitants of the Fire are confined *by* what they lie upon: the bed is the cell.

The pairing with verse 4 completes an argument the sūrah is making about freedom. The Israelites were condemned for *ʿuluww* — rising to great height, the aspiration to unbounded elevation, which verse 4 pairs with *fasād* exactly as 28:83 pairs them: *“That abode of the Hereafter — We assign it to those who seek neither exaltation (ʿuluww) in the earth nor corruption.”* The one who refuses the bounded servitude of a creature will end in the unbounded constraint of a prisoner. Al-Rāzī’s observation is that the Qur’an’s eschatological punishments are consistently the completion of the corresponding sins rather than arbitrary additions to them: the arrogant who would not bow will be unable to rise; the one who would not be limited will find every limit imposed at once. The verse closes the Israelite cycle on this note not to terrify but to explain — the prison is the shape the refusal eventually takes."""),

9: ("**Aqwam and the Claim to Supersede**",
"""The elative *aqwam* makes a comparative claim, and the classical exegetes understood exactly how bold it is. Every revealed law claims to be right; to claim to be *most* upright is to invite comparison with the previous revelations and to assert a rank above them. Al-Zamakhsharī’s grammatical observation sharpens the claim rather than softening it: because the pronoun in *li-llatī* is feminine, the antecedent must be a feminine noun — *ṭarīqah*, a way; *millah*, a creed; *khillah* or *ḥālah*, a state — and the guidance is therefore toward a *path* or a *condition*, not toward a catalogue of propositions. The Qur’an’s own formulation of the relationship is at 5:48, which states both confirmation and supersession in a single sentence: *“And We sent down unto thee the Book in truth, confirming what was before it of the Book, and a guardian (muhayminan) over it.”*

The word *muhaymin* is the crux, and Ibn ʿAbbās’s gloss on it — preserved by al-Ṭabarī — is *al-amīn* and *al-shāhid*: the trustee and the witness. The Qur’an is the authority under which the earlier revelations are to be read, tested, and where necessary corrected in their transmission. This is not a claim that the Torah and the Gospel contained falsehood when revealed; it is the claim that what survives in human hands requires a criterion, and that the criterion has been provided. The practical consequence for the reader of this verse is that the standard by which he evaluates any religious claim, including claims made in the name of earlier scriptures, is whether it accords with *that which is most upright* — and verse 89 of this same sūrah will assert that every kind of parable and proof needed for that evaluation has already been supplied."""),

10: ("**Iʿtād: The Preparation That Runs in Both Directions**",
"""The verb *aʿtadnā* — We have prepared — is one the Qur’an applies with equal grammar to the Garden and to the Fire, and the symmetry is theologically significant. Of the Garden: 3:133, *“And hasten toward forgiveness from your Lord and a Garden whose breadth is the heavens and the earth, prepared (uʿiddat) for the reverent”*; and 76:5, where the righteous drink from a cup whose mixture is *kāfūr* from *“a spring from which the servants of God drink.”* Of the Fire: 3:131, *“And fear the Fire that has been prepared (uʿiddat) for the disbelievers”*; and here, *aʿtadnā lahum ʿadhāban alīmā*. Neither destination is improvised at the moment of judgment; both stand ready, which means the judgment is the *assignment* of a person to a place that already exists rather than its construction in response to him.

The commentators also note the deliberate asymmetry of *description* beneath the symmetry of *preparation*. The Qur’an’s accounts of the Garden are extended, sensory, and specific — rivers, shade, fruits within reach, spouses, couches, no idle speech — while its accounts of the Fire are brief and largely negative: heat, boiling water, *zaqqūm*, darkness, no coolness and no drink (78:24–25). Ibn ʿĀshūr draws the inference that the revelation’s rhetorical aim is to make the reward *desirable* rather than to make the punishment *terrifying*, and that the mention of *ʿadhāb alīm* here functions as a boundary rather than a spectacle. The verse is placed second in a pair for that reason: the primary content of the glad tidings is the great reward, and the painful punishment is announced as the condition under which the reward remains meaningful — a moral order with no settlement would make uprightness a loss rather than a gain."""),

11: ("**Three Outcomes of Supplication, and the Verse That Explains Them**",
"""This verse is the Qur’an’s diagnosis of why people stop praying, and the Prophetic tradition builds its practical doctrine directly upon it. The diagnosis is that the human being is epistemically limited and temporally impatient at once: he cannot see the chain of consequences that a granted request would set in motion, and he cannot wait long enough to discover it. Al-Ṭabarī’s inference is severe — if every supplication were answered as uttered, human beings would be destroyed by their own tongues — which reframes the unanswered prayer as frequently an act of protection rather than neglect.

The tradition supplies the corresponding framework. A report recorded by Aḥmad (11133) and al-Ḥākim, and widely cited by the commentators on this verse, states:

> *“There is no Muslim who supplicates to God with a supplication in which there is neither sin nor severing of kinship, but that God gives him one of three things: either He hastens for him what he asked, or He stores it for him in the Hereafter, or He turns away from him an equivalent evil.” They said: 'Then we will ask much.' He said: 'God is more abundant.'”* (Aḥmad 11133; al-Ḥākim, graded ṣaḥīḥ by al-Albānī in *Ṣaḥīḥ al-Targhīb*)

The three outcomes together close the gap the verse opens: nothing sincere is wasted, and the form the answer takes is not the supplicant’s to specify. The discipline that follows is the one al-Bukhārī (6340) records — *“The supplication of one of you is answered so long as he does not hasten, saying: 'I supplicated and was not answered'”* — which identifies haste not as a defect of technique but as the specific thing that nullifies the practice. The hasty man asks for the object; the instructed man asks for the good, and leaves the identification of the good to the One who can see the whole chain."""),

12: ("**Maḥawnā: The Effaced Sign and the Borrowed Light**",
"""The verb *maḥā* — to efface, to wipe out — is applied by the majority of the early commentators, following Ibn ʿAbbās, to the moon, and the reading yields one of the Qur’an’s most elegant natural metaphors. The sign of the night is described as *effaced* because the moon has no light of its own: it is a body that reflects, waxing and waning, sometimes absent altogether. The sign of the day, by contrast, is *mubṣirah* — sight-giving, blazing, self-evident. Al-Ṭabarī preserves the report that the effacement refers to the darkness the moon carries, and al-Zamakhsharī notes the grammatical idiom by which the day is called “seeing” when what is meant is that one sees *in* it, as one says “a sleepless night” for a night in which one does not sleep. The theological content of both readings is identical: everything luminous in the created order is reflecting a light that is not its own, which is what 24:35 asserts in a single phrase — *“God is the Light of the heavens and the earth.”*

The verse then names two purposes, and their pairing is what makes it more than cosmology. The first is economic: *li-tabtaghū faḍlan min rabbikum*, that you may seek of your Lord’s bounty — the day exists for work, and the Qur’an nowhere treats the pursuit of livelihood as inferior to worship, as 62:10 confirms: *“And when the prayer is concluded, disperse in the land and seek of the bounty of God.”* The second is calendrical: *wa li-taʿlamū ʿadada al-sinīna wa-l-ḥisāb*, that you may know the number of years and the reckoning. This is not incidental detail. Islamic obligation is indexed to celestial motion — the five prayers to the sun’s position, Ramadan and the pilgrimage to the moon, zakāt to the completion of a year — so a religion of this kind requires a cosmos whose motion is regular, knowable, and intended. The verse grounds the entire structure of practice in the physics of the sky, and it is why the calculation of time was understood in Muslim civilization as an act of obedience rather than a technical specialty."""),

13: ("**The Neck, and the Prohibition of Reading Omens**",
"""The verse performs a piece of theological demolition and reconstruction in a single image, and the demolition is aimed at a specific pre-Islamic practice. The *ṭāʾir* is the bird, and from it the omen, because the Arabs — like the Romans with their *auspicia* — determined the advisability of an undertaking by the flight of startled birds. The Prophet ﷺ abolished the practice explicitly. Al-Bukhārī (5757) and Muslim (2220) record:

> *“There is no ʿadwā [contagion as the pagans understood it], no ṭiyarah [augury], no hāmah, and no ṣafar.”* (al-Bukhārī 5757)

And al-Bukhārī (5776) preserves the positive replacement: *“The best of it is al-faʾl — the good word one hears.”* The distinction the ḥadīth draws is precise: augury reads a random external event as a verdict on one’s future, and thereby transfers the sense of agency from the person to the world; *faʾl* is a hopeful word that encourages action without claiming knowledge. The verse completes the substitution by relocating the omen entirely: what is fastened to your neck is not a bird’s direction of flight but your own record.

The anatomy of the image is exact, and al-Rāzī explains why the neck was chosen. The neck is where both honor and shame are displayed: the necklace of rank hangs there, and the collar of servitude is fastened there. Whatever is on the neck is visible to others, inseparable from the person, and travels wherever he goes. Al-Ṭabarī adds that the neck is the point at which the head is joined to the body — the seat of direction — so that what is bound there determines where the person goes. The modern reader recognizes the phenomenon under other names: the criminal record that precedes the applicant, the debt that follows the borrower, the reputation that arrives before the person. The verse’s claim is that the moral version is more inescapable than any of them, and that its publication is deferred rather than cancelled."""),

14: ("**Two Reckonings, and the One That Is Private**",
"""The verse establishes that the decisive judgment is self-pronounced, and the Prophetic tradition describes the scene in which it happens. Al-Bukhārī (6539) and Muslim (2768) record from ʿAdī ibn Ḥātim:

> *“There is none of you but that his Lord will speak with him, with no interpreter between them. He will look to his right and see nothing but what he sent forward; he will look to his left and see nothing but what he sent forward; he will look before him and see nothing but the Fire facing him. So guard yourselves from the Fire, even with half a date.”* (al-Bukhārī 6539)

The absence of an interpreter is the detail that matters most, because it is the ḥadīth’s parallel to this verse’s *“your soul suffices as a reckoner against you.”* There is no external prosecutor whose argument the accused may contest; the conversation is between a person and the record he authored, conducted in a language that admits no ambiguity. Al-Qurṭubī’s formulation of the book remains the sharpest available: *“Your tongue is its pen, your saliva is its ink, your limbs are its pages; you dictate it to your own memory.”*

The practical discipline that the tradition builds on this verse is *muḥāsabat al-nafs* — the daily self-reckoning — which ʿUmar ibn al-Khaṭṭāb formulated in the sentence preserved by al-Tirmidhī (2459): *“Reckon yourselves before you are reckoned, and weigh yourselves before you are weighed; for it is lighter for you to reckon yourselves today in preparation for the great Reckoning.”* The practice is not an ascetic invention but an anticipation of the verse, and its value is diagnostic rather than punitive. Most of ordinary life consists in not reading the record — the promise broken, the kindness omitted, the sentence spoken in anger — and the energy spent maintaining that non-reading is measurable in the avoidance of silence. The command *iqraʾ kitābaka* is therefore available now, and the person who reads his book daily will not be surprised by it on the Day."""),
}
p='expanded/017.md'
s=open(p,encoding='utf-8').read()
parts=re.split(r'(?m)^(## Sūrah al-Isrāʾ 17:\d+)$', s)
d={int(parts[i].split(':')[1]):[parts[i],parts[i+1]] for i in range(1,len(parts),2)}
for n,(h,t) in ADD.items():
    body=d[n][1]
    hs=[m.start() for m in re.finditer(r'(?m)^\*\*(?!Expanded Commentary).+?\*\*$', body)]
    assert hs, n
    ins=hs[-1]
    d[n][1]=body[:ins]+'**'+h+'**\n\n'+t.strip()+'\n\n'+body[ins:]
out=[parts[0]]
for i in range(1,len(parts),2):
    n=int(parts[i].split(':')[1]); out.append(d[n][0]); out.append(d[n][1])
open(p,'w',encoding='utf-8').write(''.join(out))
import statistics
wc=[len(d[n][1].split()) for n in d]
print('added',len(ADD),'sections | words now',len(''.join(out).split()),'| avg/verse',round(statistics.mean(wc)),'| min',min(wc))
