import re
ADD = {
43: ("**Tanzīh as a Trained Reflex**",
"""The formula appears at this point in the Qur’an with a regularity that indicates a pedagogical intention rather than a stylistic habit. Al-Ṭabarī and Ibn Kathīr catalogue its occurrences after the mention of false deities or of children attributed to God: 6:100, 10:18, 16:1, 21:22, 23:91, 28:68, 30:40, 37:159 and 180, 39:67, 43:82, 52:43, 59:23. Al-Rāzī’s explanation of the pattern is that the revelation trains the reader’s response: upon encountering a misdescription of God, the correct reaction is not analysis first but glorification. A mind habituated to answering a false claim about God with *subḥānahu* develops a reflex of reverence that protects it from casual theological error, in the same way that a practiced musician’s hand moves correctly before his thought arrives.

The two terms divide the work of *tanzīh* between them. *Subḥānahu* declares God free of every deficiency; *taʿālā* declares Him high; and *ʿuluwwan kabīran* — a cognate accusative of intensification — declares the elevation to be great. The phrase became doctrinally significant in the discussion of the divine attributes, and the classical discipline for handling it is the formula attributed to Mālik ibn Anas when he was asked how God is established upon the Throne: the elevation is known, the *how* is unknowable, belief in it is obligatory, and questioning about the *how* is innovation. Ibn Taymiyyah argued from *ʿuluwwan kabīran* that transcendence is not a mere abstraction but includes God’s being above His creation in a manner befitting His majesty, without resemblance to created elevation — and that the verse’s own word *greatly* indicates that whatever elevation is meant, it exceeds the category.

The devotional consequence is direct. Al-Bukhārī (6682) and Muslim (2694) record:

> *“Two words are light on the tongue, heavy in the scale, and beloved to the Compassionate: *Subḥāna Allāhi wa bi-ḥamdih, subḥāna Allāhi al-ʿaẓīm*.”* (al-Bukhārī 6682)

The verse is the scriptural model of the practice, and the practice is the verse’s intended effect: the one who says the words regularly finds, when a false claim about God reaches him, that the answer is already formed."""),

44: ("**Do the Mountains Actually Praise? The Debate and Its Ethics**",
"""The verse’s scope is total — *wa in min shayʾin illā yusabbiḥu bi-ḥamdih*, there is not a thing but that it glorifies Him with His praise — and the commentators divided over whether the praise is literal, with the division producing one of the tradition’s more tender practical rulings. The first position, held by many of the Salaf and by Ibn Kathīr, is that the praise is real, in a manner appropriate to each creature, known to God and not to us — which is exactly what the verse states: *wa lākin lā tafqahūna tasbīḥahum*, you do not understand their glorification. Al-Ṭabarī preserves the opinion that *subḥāna Allāh* is the universal prayer of all creatures. The second position, associated with the rationalist exegetes, is that the praise is the “speech of the case” (*lisān al-ḥāl*): every creature testifies to its Maker by its existence, order, and dependence, as a well-made object testifies to its maker without speaking.

The verse’s own wording favors the first reading, and the commentators who press the point do so on a precise ground: if the praise were merely the evident fact of design, it would be comprehensible, since design is exactly what reflection discerns. The statement that we do not understand their praise is only necessary if the praise is of a mode beyond our apprehension. From this reading al-Ṭabarī draws an inference of unusual tenderness: since every creature possesses spirit and glorifies God, one should never show disrespect to any animal or any creature. The doctrine of universal praise is therefore not a metaphysical curiosity but a re-ordering of the human being’s relation to the natural world — the bird in the tree is engaged in worship you cannot hear, and your treatment of it is the treatment of a worshipper.

This is the theological ground of the extensive Islamic legislation on animal welfare, and the Prophetic formulation is explicit. Abū Dāwūd (2877) records:

> *“God has written excellence (iḥsān) upon everything. So when you kill, kill well; and when you slaughter, slaughter well. Let one of you sharpen his blade and spare suffering to the animal he slaughters.”* (Muslim 1955)

The verse closes the polemic of verses 40–43 with this argument: everything in the heavens and the earth is subordinate, dependent, and turned toward the One God, so to worship any of it — even as an intermediary — is to be ignorant of what it is. The contingency of the whole cosmos is the proof of the Necessary One, which is why 41:37 concludes, *“Prostrate not unto the sun nor unto the moon, but prostrate unto God Who created them.”*"""),

45: ("**The Veil That Cannot Be Seen From Inside**",
"""The participle *mastūr* — covered, concealed — applied to a veil produces a doubling that al-Rāzī treats as the verse’s central feature: a veil that is itself veiled, so that the person behind it does not know he is behind it. This is the most unsettling aspect of the image. The disbeliever does not experience the barrier as a barrier; he experiences only incomprehension, or boredom, or irritation, and he cannot locate the obstacle because it is invisible from his side. The same device appears at 41:5, where the disbelievers themselves describe their condition — *“Our hearts are under coverings from that to which thou callest us, and in our ears there is deafness, and between us and thee is a veil”* — which the commentators note as an acknowledgment rather than a complaint: they know they are not receiving, and they prefer it that way.

Al-Ṭabarī and al-Jaṣṣāṣ record two readings of the veil’s function, and the exegetes often hold both. The first: the veil prevents the disbelievers from comprehending the recitation and deriving benefit from it, which is consistent with the coverings and deafness of the following verse. The second, favored by al-Rāzī: the veil protects the Prophet ﷺ from their harm while he recites. The specification of the audience — *those who do not believe in the Hereafter* — repeats the exact qualification of verse 10, and for the same reason: denial of the Hereafter removes the disposition that makes reception possible, since a person who does not expect to be questioned has no reason to attend to a message whose entire content is the questioning. The veil is therefore not an arbitrary obstruction but the form taken by an antecedent refusal.

The verse’s pastoral function is what has made it important across the tradition. The Prophet ﷺ recited to assemblies that produced nothing, and the Qur’an explains the failure without attributing it to a defect in the recitation. The same reassurance appears at 27:80–81 — *“Truly thou canst not make the dead hear, nor make the deaf hear the call when they have turned their backs”* — and at 28:56, *“Truly thou guidest not whom thou lovest, but God guides whom He wills.”* Anyone who has attempted to discuss faith with a person committed to disbelief recognizes the phenomenon: the words are heard but not received, and the argument is answered without being engaged. The verse names it, locates it, and thereby releases the speaker from measuring his success by the hearer’s response."""),

46: ("**The Sequence of Sealing, and What It Warns Against**",
"""That God *places* the coverings raises the question of responsibility, and the classical answer rests on sequence. Al-Ṭabarī and al-Rāzī both argue that the sealing follows the refusal rather than causing it, and the Qur’an states the sequence explicitly at 61:5: *“And when they turned aside, God turned aside their hearts.”* And at 6:110: *“And We shall turn their hearts and their sight, as they did not believe in it the first time.”* The initial turning away is the human act; the sealing is the divine confirmation of a chosen state. The person who repeatedly refuses to look eventually loses the capacity to see, and the loss is real, and it is his — though it is God who enacts it. This is among the Qur’an’s most serious warnings, because it means that refusal has cumulative consequences that are not fully reversible.

The two terms are precise. *Akkinnah*, the plural of *kinān*, denotes an enclosure rather than a film — al-Qurṭubī compares it to a quiver or a sheath — and it prevents *fiqh*, the deep comprehension that goes beyond hearing words to grasping their meaning. *Waqr* is a heaviness in the ear, a partial deafness rather than a total one, since they do hear the recitation. The verse therefore distinguishes two levels: the sounds arrive, the understanding does not. 2:7 states the same condition with the verb of sealing — *“God has set a seal upon their hearts and upon their hearing, and upon their sight is a covering”* — and the placement of that verse immediately after descriptions of those who *chose* deception is what fixes the order of cause and effect.

The clause about mentioning the Lord *alone* identifies the precise point of rupture, and it is diagnostic. Al-Bayḍāwī and al-Rāzī explain that the reference is to verses affirming God’s Oneness and refuting partners. It was not the Qur’an’s moral teaching, its narratives, or its eschatology that produced the recoil; it was the exclusive claim. The historical evidence is striking: al-Walīd ibn al-Mughīrah, one of the Quraysh’s most accomplished judges of Arabic, heard the Qur’an and said of it that it was not the speech of mankind, and that it shatters what is below it and rises above it — and he still did not believe. The verse therefore supplies a test available to any reader: observe not what in the message you find hard to understand, which is an intellectual matter, but what makes you want to leave the room. That point is where the message is touching something you have enthroned."""),

47: ("**The Variety of the Accusations as Evidence Against Them**",
"""The charge recorded here — *rajulan masḥūrā*, a man bewitched — is one of a shifting set, and al-Rāzī turns the shifting into an argument. The Quraysh described the Prophet ﷺ variously as bewitched, as a poet (21:5, 37:36, 52:30), as possessed (15:6, 23:70, 34:8, 44:14, 68:51), as taught by a human being (16:103), and as a liar. The commentators note that these characterizations are mutually exclusive: a poet is not a madman, a madman is not composing verse of acknowledged excellence, and a man deceived by sorcery is not a deliberate deceiver. The multiplicity is the evidence. A conclusion reached by observation is stable; a charge selected to serve a purpose changes as the purpose changes, and the trial of each description in turn is the behavior of people searching for an accusation rather than reporting a finding.

The accusation is also a reflex rather than an evaluation, and the Qur’an documents its recurrence across the entire prophetic history. 51:52 states the pattern: *“Likewise no messenger came to those before them but they said: 'A sorcerer, or a madman!'”* Ṣāliḥ was called bewitched at 26:153, Shuʿayb at 26:185, and Moses in this very sūrah at verse 101. The content of such an accusation therefore tells one nothing about the truth of the message, and its recurrence should alert the hearer to its character — a point with obvious application to any age in which an unwelcome messenger is met with a standard vocabulary of dismissal.

The verse’s first clause is the more penetrating of the two. *Naḥnu aʿlamu bimā yastamiʿūna bihi* — We know best *what they listen for* — extends divine knowledge to the purpose of the listening rather than merely its content. Al-Bayḍāwī and al-Rāzī explain that they listened not for guidance but for material to mock, and the distinction is one of the Qur’an’s most exact observations about hostile attention. Two people can hear identical words; one listens for truth and the other for a flaw, and the second is not engaged in inquiry but in gathering ammunition. The posture is invisible to the speaker and frequently to the listener himself, which is why the verse needs to assert it rather than demonstrate it. The secret conference (*najwā*) receives the same treatment throughout the Qur’an — 4:114 concedes an exception for those who enjoin charity, kindness, or reconciliation, which implies that most secret conference has another purpose — and 58:10 supplies the diagnosis: *“Their secret converse is only from Satan, that he may grieve those who believe.”*"""),

48: ("**Premature Explanation as a Closed Door**",
"""The imperative *unẓur* — see, look — invites the Prophet ﷺ and the reader to examine the accusations as objects, and the examination is itself the refutation. Al-Rāzī makes the argument explicit: a man who is a poet is not a madman; a man who is mad is not composing verse of acknowledged excellence; a man bewitched is not a deliberate deceiver. The Quraysh tried each description in turn, which is the behavior of people searching for a charge rather than stating a finding, and the invitation to look is an invitation to notice the incompatibility. The command is rhetorical rather than evidential: no new fact is supplied, because the facts were already in the objectors’ hands and the difficulty was not information.

The clause *fa-ḍallū fa-lā yastaṭīʿūna sabīlā* — they have gone astray and cannot find a way — states the consequence, and al-Qurṭubī explains the mechanism: their very act of describing him wrongly is what closed the path. This is a subtle claim about error, and it is more interesting than a simple condemnation. Error is not merely a wrong belief but a *closure*. Once the mind settles on an explanation — even a poor one — it stops investigating, because the feeling of having understood substitutes for the work of understanding. The Quraysh’s descriptions were not conclusions reached by inquiry but substitutes for inquiry, and having adopted them, they could not find a way out. The verb *ḍalla* means to lose the way, and *sabīl* is a road, so the image is of people who have mislaid the road and cannot locate another.

The phenomenon is universally recognizable and the verse describes it with clinical accuracy. The person who has decided what something is — a political opponent, a religious claim, a colleague’s motive — no longer investigates it, and the decision feels like knowledge from the inside. This is why premature explanation is more obstructive than ignorance: the ignorant person may still ask, while the person with a settled explanation has no reason to. The verse’s practical instruction is therefore negative and useful: when you find that you have a complete account of something you have not examined, the completeness is itself the signal to look again. The disbelievers of Makkah had a complete account of the Prophet ﷺ within weeks of his public preaching, and the completeness is what the verse identifies as their undoing."""),

49: ("**Quoting the Objection in Full: The Qur’an’s Evidential Honesty**",
"""The verse reproduces the skeptical question in direct speech with its incredulity intact — the opening interrogative, the emphatic *a-innā la-*, the tone of *what, us?* — and this practice is a feature of the Qur’an’s method rather than an incidental detail. It does not caricature its opponents’ arguments; it states them accurately and answers them. The objection from decomposition is not frivolous but the strongest empirical argument available against resurrection, and the Qur’an engages it repeatedly — 23:35 and 82, 36:78, 37:16–17, 56:47, 79:10–11, and again at verse 98 of this sūrah — rather than dismissing it.

The two nouns mark the two stages of dissolution with precision. *ʿIẓām*, bones, is the hardest part remaining after decay; *rafāt* is what has been crushed to powder. Together they cover the objection completely: the objector is not asking about a recently dead body but about dust. The phrase *khalqan jadīdā* — a new creation — names the specific claim he finds incredible: not mere revival but re-creation.

The structure of the answer that follows is logical rather than rhetorical, and its three parts address three distinct components of the objection. Verses 50–51 concede the material premise and then exceed it: were you stone or iron — materials infinitely further from life than bones — the answer would be the same. The agent is then identified: the One who originated you the first time. Finally, the question of timing is handled separately. The verse’s own argumentative force lies in the asymmetry it exposes. The objector concedes that he was created once from nothing; he then denies that the same agent can reconstitute what He made. The re-creation is therefore the *less* demanding of the two acts, not the more, since the origination had no precedent.

The Qur’an locates the objection’s source not in evidence but in wish, and the diagnosis is careful. 75:3–5: *“Does man think that We shall not assemble his bones? Yes indeed — We are able to reshape his very fingertips. But man desires to deny what is before him (yurīdu li-yafjura amāmah).”* The phrase identifies the motive: the denial of resurrection is a desire to continue without constraint. This is a claim about motivation rather than about argument, and it is made without denying that the objector has reasons; it says that his reasons are powered by a preference. Anyone who has watched a person resist a conclusion because of what accepting it would require recognizes the description."""),

50: ("**The Hypothetical That Makes the Opponent Finish the Sentence**",
"""The verse is a fragment, and its incompleteness is the device. The imperative *kūnū* is not a command to become stone but a hypothetical — *suppose you were* — and the apodosis is left for verse 51 to supply. The Qur’an uses this construction repeatedly, and its effect is to require the interlocutor to complete the thought himself, which is more persuasive than being handed the conclusion. The objector must finish: *if we were stone or iron... He could still bring us back.* Having said it, he has conceded the point in his own words.

The selection of the two materials is precise, and al-Zamakhsharī explains the reasoning. Stone and iron were, to the Arab imagination, the substances most remote from life: the hardest, the most inert, the most resistant to change. Stone does not decay and iron does not soften. If the objector’s difficulty is that bones and dust are too far gone, the answer escalates to materials infinitely further from life than bones ever were — and the escalation cannot be evaded, because verse 51 immediately invites him to name anything harder still. Al-Zamakhsharī states the resulting inference sharply: bones were once alive by God’s act; stone and iron never were. The resurrection of a human being is therefore the easier of the two, and the objector has misjudged the difficulty.

The argument depends on a specific conception of divine power, and identifying it clarifies why the objection fails. If creation were the rearrangement of pre-existing material, then stone and iron would present a genuine obstacle, since nothing in them is disposed to life. Because creation is *origination* — the bestowal of existence rather than the manipulation of substance — the material is irrelevant, and the only question is whether the Maker wills. 30:27 states the principle directly: *“He it is Who originates creation, then brings it back again, and it is easier for Him (wa huwa ahwanu ʿalayhi).”* The commentators note that “easier” is relative to human estimation rather than to God, for whom nothing is easier than anything, and that the phrase is accommodated to the way a human being compares two acts.

This is why the Qur’an’s resurrection argument is inseparable from its creation argument. A person who cannot conceive of making something from nothing cannot conceive of resurrection, and a person who accepts the first has already accepted the second. The objector’s position is therefore unstable: he knows he came into being, and he has either answered the question of how or left it open. If he has answered it, resurrection follows; if he has left it open, he has no standing to declare resurrection impossible, since he cannot account for his own existence. 52:35 states the trilemma in its cleanest form: *“Or were they created from nothing? Or are they the creators?”*"""),

51: ("**Two Fingers, and the Nearness That Is Personal**",
"""The three questions in this passage — what will be raised, by whom, and when — are answered in order, and the third answer is the one that has entered Muslim consciousness most deeply. The gesture is preserved in two reports. Al-Bukhārī (6504) and Muslim (2950) record:

> *“I and the Hour have been sent like these two” — and he joined his index and middle fingers.* (al-Bukhārī 6504)

The image is of two things so close that nothing can fit between them. Al-Ṭabarī connects the verse’s *ʿasā an yakūna qarībā* — it may well be nigh — to the commentators’ observation that *ʿasā* spoken by God indicates something that will certainly occur rather than something merely possible, the same principle applied to *ʿasā* in verse 8 of this sūrah. The answer is therefore not a date but a warning with the force of a promise.

The general rule elsewhere in the Qur’an is refusal. 7:187: *“They ask thee about the Hour, when it will come. Say: the knowledge of it is only with my Lord; none shall manifest it at its time but He.”* And 67:25–26: *“They say: when is this promise, if you are truthful? Say: the knowledge is only with God, and I am only a clear warner.”* The exception here is granted for a specific reason, which al-Rāzī identifies: the nearness is true for every hearer personally, whatever the cosmic schedule, because each person’s Hour arrives at his death. 63:11 states the personal version of the same law: *“And God will never delay a soul when its term has come.”* The answer thus defeats the deflection, since the objector who asks *when* in order to postpone has been told that the postponement is shorter than he assumes.

The head-shaking described in the verse — *fa-sayunghiḍūna ilayka ruʾūsahum*, they will wag their heads at thee — is reported with unusual vividness, and al-Ṭabarī explains it as the universal gesture of mocking dismissal. The gesture completes the diagnostic begun in verse 49: having failed to refute the possibility, the objector demands a date, which is a deflection rather than an inquiry. The Qur’an identifies such demands as bad faith elsewhere, and the reasoning is that a person who makes his belief conditional on his own terms has already decided that the terms, rather than the evidence, will govern. The cosmic nearness is stated at 54:1 — *“The Hour has drawn near, and the moon has split”* — and at 21:1, *“The reckoning of mankind has drawn near, yet they turn away in heedlessness.”*"""),

52: ("**The Collapse of Duration, and the Recalibration It Demands**",
"""The verse’s final clause — *wa taẓunnūna in labithtum illā qalīlā*, you will reckon that you tarried but a little — is one of the Qur’an’s most consistently repeated eschatological claims, and the consistency is itself significant. The estimate is specified across a range of verses with remarkable agreement: a day or part of a day (18:19, 23:113), an hour of a day (10:45, 30:55, 46:35), an evening or its morning (79:46). The commentators offer two explanations and both are illuminating. The first is comparative: the Hereafter is eternal, and any finite duration, however long, is negligible beside it — a thousand years is nothing next to forever. The second is phenomenological: the intensity of the Day compresses the memory of everything preceding it, as a great event compresses the years before it in the recollection of anyone who has lived through one.

The Qur’an makes the comparative argument explicitly at 23:115: *“Did you think that We created you in vain, and that you would not be returned to Us?”* The question presupposes the disproportion: a life spent entirely within a brief interval, on the assumption that the interval is the whole, is the specific error the verse identifies. The universal praise with which the summoned respond — *fa-tastajībūna bi-ḥamdih* — is explained by al-Qurṭubī and al-Ṭabarī as arising from three recognitions now inescapable: God as Creator, His power to resurrect, and the blessings He bestowed. Al-Zamakhsharī adds that the response is immediate and unhesitating, unlike the response to the same call in worldly life, which is what gives the scene its tragedy: the commentators are careful to note that this recognition and obedience bring no benefit to those who refused both in earthly life, since 40:85 records the principle — *“Their faith did not avail them when they saw Our might — the wont of God which has passed among His servants.”*

The verse’s practical force does not require accepting the eschatology to be felt. Every person who has reached the end of anything — a career, a marriage, a life — reports the same collapse: it seemed long while it was happening and short in retrospect. The Qur’an takes that universal experience to its limit and uses it to recalibrate the scale on which decisions are made. Most of what consumes a person’s attention is urgent within a frame that this verse declares to be brief, and Sūrah al-ʿAṣr states the resulting loss in a single sentence: humanity is in loss except those who believe, do good, and counsel one another to truth and patience. The loss is precisely the spending of the brief interval on what does not survive it."""),

53: ("**Aḥsan as a Selection Rule, Not a Command to Be Nice**",
"""The elative *aḥsan* — the better, the best — implies a set of alternatives, and that is what makes the verse an instruction rather than a sentiment. Among the true things one could say, choose the better one. Al-Zamakhsharī reads it as a general command to speak gently without harshness, and al-Qurṭubī supplies the reported occasion: ʿUmar ibn al-Khaṭṭāb was insulted by an Arab and cursed or threatened him in return, and the verse instructed pardon instead. The elided feminine noun most commonly supplied is *kalimah*, so that the phrase reads “say the word that is best,” and al-Ṭabarī records the identification of that word with the testimony of faith — a reading that makes the verse’s object not merely tone but content.

The reasoning al-Rāzī gives is consequentialist in a way that is worth noticing inside a revealed text. Harsh speech provokes the opponent to answer in kind and entrenches him in his opposition, so the moral quality of a statement is not determined solely by its truth; its effects enter into the evaluation. The Qur’an states the same principle at 6:108 with an argument of unusual force: *“And revile not those whom they call upon besides God, lest they revile God in enmity without knowledge.”* The prohibition on reviling false gods — which deserve nothing — is justified by its consequence, which would be blasphemy against God. A true statement delivered so as to harden the hearer against truth has failed in the very purpose for which speech exists. Al-Qurṭubī preserves the recommended form of reply to an insult: *“May God have mercy upon you”* — a formula that converts the exchange entirely, since there is nothing to answer.

The second half of the verse identifies the adversary’s method with precision. *Yanzaghu* is from *n-z-gh*, to insert, to intrude, to prod, and it denotes a small sharp intervention that sets something in motion — a wedge driven into a joint. Al-Rāzī’s observation is that Satan does not usually attack faith directly but attacks *relationships*, and the Qur’an’s case studies confirm it: 5:91 describes the enmity sown through wine and gambling, and 12:100 records Joseph telling his brothers, *“It was Satan who incited evil between me and my brothers”* — a family destroyed not by an external enemy but by an internal provocation no one recognized at the time. The practical discipline is therefore testable in daily life: before speaking in conflict, the question is not “am I right?” but “is this the better word, among the true things I could say?” Often the better word is shorter, softer, or absent — which is why al-Bukhārī (6474) records the Prophet ﷺ compressing the whole matter into a single instruction: *“Whoever believes in God and the Last Day, let him speak good or remain silent.”*"""),

54: ("**The Grief of the Messenger, and the Office That Could Not Carry It**",
"""The verse addresses a specific pain in the Prophet’s ﷺ life, and the Qur’an speaks to that pain directly in two other places. 18:6: *“Perhaps thou wouldst kill thyself with grief that they believe not in this discourse.”* 35:8: *“Let not thy soul waste away in grief over them.”* The reports of his distress at the rejection of his people are numerous, and the verse’s final clause is the structural answer: *wa mā arsalnāka ʿalayhim wakīlā* — We have not sent thee as a guardian over them. The *wakīl* is the trustee who answers for the outcome, and the Prophet ﷺ is explicitly not that. His function is conveyance, and what happens after conveyance is between the hearer and God.

The Qur’an repeats this delimitation with a persistence that indicates how necessary it was. 5:92: *“If you turn away, know that upon Our Messenger is only the clear conveyance.”* 10:108: *“Whoever is guided is guided for his own soul, and whoever goes astray goes astray only to its detriment — and I am not a guardian over you.”* 88:21–22 states it most starkly: *“So remind; thou art only a reminder. Thou art not a dictator (muṣayṭir) over them.”* And 28:56 settles the matter of outcome: *“Truly thou guidest not whom thou lovest, but God guides whom He wills.”*

The clause about mercy and punishment — *in yashaʾ yarḥamkum aw in yashaʾ yuʿadhdhibkum* — is read by al-Qurṭubī and al-Rāzī in two ways, both pastoral: that God may deliver the believers from persecution or leave them under it, or that He may guide the disbelievers to faith or punish them for rejecting it. Either way the point for a community being tortured in Makkah is that the arrangement of worldly affairs is not a verdict on spiritual standing. Bilāl under the stone, the family of Yāsir, and Khabbāb on the coals were not being punished for their faith, and their oppressors were not being rewarded for their unbelief; the timing belonged to God and disclosed nothing.

The discipline this verse supplies is one every teacher, parent, and preacher needs. The alternative to accepting the limit is not greater effectiveness but either coercion or despair: the person who believes himself responsible for another’s response will eventually try to produce it by force, or will collapse under the failure. The verse locates the boundary precisely, and its location is what makes sustained effort possible without either distortion."""),

55: ("**Rank Among the Prophets, and the Believer’s Non-Distinction**",
"""The verse states a hierarchy and the Qur’an elsewhere forbids a distinction, and the reconciliation of the two is a settled point in the tradition. 2:253 states the ranking: *“Those messengers — We favored some of them above others. Among them are those to whom God spoke, and some He raised in degrees.”* 2:285 states the non-distinction: *“The Messenger believes in what was sent down to him from his Lord, and so do the believers... We make no distinction between any of His Messengers.”* Al-Ṭabarī’s resolution is that the believer makes no distinction *in belief* — he accepts all of them as prophets — while acknowledging that God *gave* them different gifts and stations. The two statements concern different things: the object of faith and the distribution of favor.

The highest ranks are named rather than left abstract. The *ulu al-ʿazm*, the messengers of steadfastness, are identified at 46:35; Abraham is described as God’s *khalīl*, intimate friend, at 4:125; Moses as the one to whom God spoke directly at 4:164. The Prophet Muhammad ﷺ is described in this sūrah by the title *ʿabd* — servant — at verse 1, and his distinction is established by the journey and the vision rather than by a competing claim of rank, which is a structurally significant choice: the sūrah that opens with the greatest honor conferred on a human being describes that honor in the language of servitude.

David is selected as the example of differential favor because his gifts were unusually varied: kingship and prophethood together, the Psalms, the softening of iron (34:10), the submission of the mountains and birds to his praise (38:18–19), the speech of birds (27:16), and the judgment he rendered alongside Solomon (21:78–79). Al-Qurṭubī records the description of the *Zabūr* as a revealed book containing no religious law but only praise and glorification, which if accepted makes David’s gift distinctive in kind — a scripture of worship rather than of legislation — and consistent with the Qur’an’s account of him at 34:10–11, *“And We gave David favor from Us: 'O mountains, hymn with him, and you birds!'”* The verse’s placement after the argument against intermediary worship is what gives it its function: genuine excellence exists, and excellence is a *gift* rather than a divinity. The one who receives a scripture remains a servant, and the angels who received the command to prostrate were themselves servants — which is the point verses 56 and 57 will press."""),

56: ("**The Public Test, and the Argument From Crisis**",
"""The command is *say* — announce it — and the publicity is part of the argument. The challenge is not a private refutation but a test anyone can run, so that the failure is visible to all. The verb *zaʿama* — to claim, to assert — carries in Arabic a connotation of unsupported assertion, and the Qur’an uses it of false claims at 4:117 and 6:148; the choice of verb is a quiet verdict on the claim before the experiment begins. The two powers denied cover every form of relief: *kashf al-ḍurr*, the removal of harm, and *taḥwīl*, its transfer elsewhere. A being that can do neither has nothing to offer, and al-Qurṭubī notes that the exclusion of both closes every possibility of assistance.

The Qur’an’s strongest version of this argument is phenomenological rather than theoretical, and it appeals to observed behavior. In a crisis the idolater calls only on God. 29:65: *“And when they embark upon a ship, they call upon God, sincere to Him in religion; but when He has brought them safely to land, behold, they associate.”* 10:12: *“And when affliction touches man, he calls upon Us, whether lying on his side, or sitting, or standing; but when We remove his affliction from him, he passes on as though he had never called upon Us.”* 6:40–41 poses it as a direct question: *“Will you call upon other than God, if you are truthful? Nay, but to Him you will call, and He will remove that for which you call upon Him, if He wills, and you will forget what you associated.”*

The claim is that the idolater’s own behavior in extremis testifies against his theology, and this sūrah will make the point concretely at verses 67–69 using the experience of the sea. The anthropology beneath it is the doctrine of *fiṭrah*: the human being is not ignorant of God but inconsistent, and the crisis strips away the acquired theology to expose the unacquired knowledge beneath. The one who calls on his god in a storm and receives nothing learns more from the silence than from any argument, which is why the verse proposes the test rather than supplying the conclusion.

The argument retains its force in modern form, since the structure of the error is unchanged. Whatever a person treats as the source of relief in extremity — a market, a diagnosis, a patron, a technique — occupies the position that the verse reserves for God, and the test of a crisis will disclose which. The verse’s demand is therefore not that the reader abandon his means but that he stop attributing to them a power they do not possess: the means are used, and the outcome is sought from the One who governs them."""),
}
p='expanded/017.md'
s=open(p,encoding='utf-8').read()
parts=re.split(r'(?m)^(## Sūrah al-Isrāʾ 17:\d+)$', s)
d={int(parts[i].split(':')[1]):[parts[i],parts[i+1]] for i in range(1,len(parts),2)}
for n,(h,t) in ADD.items():
    body=d[n][1]
    hs=[m.start() for m in re.finditer(r'(?m)^\*\*(?!Expanded Commentary).+?\*\*$', body)]
    assert hs, n
    ins=hs[-1]
    d[n][1]=body[:ins]+'**'+h+'**\n\n'+t.strip()+'\n\n'+body[ins:]
out=[parts[0]]
for i in range(1,len(parts),2):
    n=int(parts[i].split(':')[1]); out.append(d[n][0]); out.append(d[n][1])
open(p,'w',encoding='utf-8').write(''.join(out))
print('added',len(ADD),'| words now',len(''.join(out).split()))
