import re
ADD = {
85: ("**Al-Rūḥ min Amri Rabbī: The Answer That Declines the Question**",
"""This verse is one of the most discussed in the Qur’an, and its method of answering is more significant than its content. Al-Ṭabarī records the occasion: a delegation asked the Prophet ﷺ about the *rūḥ*, and the answer came immediately. The exegetes divided over what was being asked, and al-Ṭabarī catalogues the readings — the soul that gives life to the body, the Qur’an itself, the angel Gabriel, or a class of angels described as an army of God. The majority reading is the soul, and the answer addresses it in a way that changes the subject deliberately.

The answer has two parts, and the second is the substantive one. *Qul al-rūḥu min amri rabbī* — say: the spirit is of the command of my Lord. The commentators, following al-Rāzī and al-Ghazālī, distinguished between the *ʿālam al-khalq*, the world of creation, which comprises things brought into being through materials, causes, and intervals, and the *ʿālam al-amr*, the world of command, which comprises things that come into being by the word *kun*, be, without a material antecedent. 7:54 makes the same distinction: *“His is the creation and the command.”* The soul is placed in the second category, and the consequence is that the methods appropriate to the first — observation, decomposition, inference from parts — do not apply to it.

The second clause is the verse’s real answer: *wa mā ūtītum min al-ʿilmi illā qalīlā* — and you have been given of knowledge only a little. Al-Rāzī reads it as the ground of the refusal rather than a rebuke: the questioner is being told that his apparatus is inadequate to the question, not that the answer is being withheld arbitrarily. This is a claim about epistemic scope, and it has an obvious modern parallel — the demand that a thing be explained in the terms of a method that cannot reach it. The verse does not say the soul is unknowable in itself; it says that what has been given to the questioner does not reach it.

The verse’s placement is significant. It sits between the account of the Qur’an as a healing (v. 82) and the statement of its contingency (v. 86), and the three together make a single claim: the revelation heals, it is a gift that could be withdrawn, and there are questions it will not answer. The refusal is therefore part of the gift’s character rather than a limitation of it. 5:101 records the same principle in legislation: *“O you who believe, ask not about things which, if made plain to you, may grieve you.”* The Qur’an’s method throughout is to answer the question that matters and to decline the one that does not, and this verse is the clearest instance of the second."""),

86: ("**If We Willed, We Would Take It Away: The Contingency of the Revelation**",
"""The verse asks the Prophet ﷺ to consider the absence of what he has been given, and the exercise is the point. *Wa la-in shiʾnā la-nadhhabanna bi-alladhī awḥaynā ilayka* — and if We willed, We would surely take away what We have revealed to thee. The double particle *la-in* with the emphatic *la-nadhhabanna* makes the statement as strong as Arabic allows: not a possibility but a certainty held back by nothing but the divine will. Al-Qurṭubī explains the function: the blessing is not measured while it is held but by the consideration of its removal, and the verse instructs the reader to perform that consideration.

The clause that follows — *thumma lā tajidu laka bihi ʿalaynā wakīlā*, then thou wouldst find no trustee for thyself with Us concerning it — is the third use of *wakīl* in this passage, after verses 65 and 68, and the accumulation is deliberate. In verse 65 God is sufficient as trustee for the believers; in verse 68 the disbeliever finds none; here the Prophet ﷺ himself would find none. The verse thereby establishes that the relation of dependence is universal and ungraded — no one holds the revelation as a possession, and no one has standing to claim it.

The theological content is the contingency of the revelation. The Qur’an does not exist by necessity; it exists because it was sent, and the sending could have been withheld or withdrawn. Al-Rāzī draws the consequence: a gift that could be withdrawn is a gift, and the recipient’s obligation is gratitude rather than entitlement. 2:106 states the same principle in the register of legislation: *“Whatever verse We abrogate or cause to be forgotten, We bring one better than it or like it — knowest thou not that God has power over all things?”*

The verse’s placement after the statement that the spirit belongs to the world of command produces a striking sequence. The human being is told that he has been given little knowledge, and then that the greatest thing he has been given is held only by another’s will. The two statements together are the Qur’an’s anthropology in miniature: the creature is dependent in his knowing and dependent in his having, and both dependencies are stated to produce gratitude rather than despair — since the alternative to a contingent gift is not a necessary one but nothing.

The devotional tradition read the verse accordingly, and the practice it produced is *dhikr al-niʿmah*, the remembrance of the blessing, which al-Qurṭubī describes as the discipline of recalling what one has been given in the form of what one would lose. 14:7 supplies the motive: *“If you are grateful, I will surely increase you; and if you are ungrateful, My punishment is severe.”*"""),

87: ("**Illā Raḥmatan min Rabbika: The Exception That States the Whole Ground**",
"""The verse completes the preceding one with the exception that explains it. *Illā raḥmatan min rabbik* — except by mercy from thy Lord. The grammatical construction is an exception from an implied negative: the revelation would have been taken away, and nothing prevented it except mercy. Al-Ṭabarī and al-Qurṭubī both note that the exception removes the possibility of any other ground — not the Prophet’s ﷺ merit, not the community’s worthiness, not the necessity of the message, but mercy. The verse is therefore a statement of grace in its purest Qur’anic form.

The clause that follows makes the point quantitative: *inna faḍlahu kāna ʿalayka kabīrā* — indeed His bounty toward thee is great. The word *kabīr*, great, is the same intensive description used at verse 43 of the divine elevation, *ʿuluwwan kabīrā*, and the parallel is not accidental: the transcendence stated there is exercised here as bounty. Al-Rāzī enumerates what the bounty comprises, and the list is effectively the whole of the sūrah — the Night Journey, the revelation, the confirmation at the point of pressure, the praiseworthy station, and the preservation of the message.

The verse’s theological significance is that it forecloses a specific error. A messenger who has received what no one else received might conclude that he holds it by right, and the community that receives a revelation might conclude that it possesses it. The Qur’an closes both conclusions in two clauses: the ground of the gift is mercy, and its extent is great. 3:164 records the same description of the sending itself: *“God conferred a favor upon the believers when He raised among them a messenger from themselves.”*

The practical consequence is the one the tradition drew consistently. A person who understands that his knowledge, his faith, and his access to the revelation are gifts rather than achievements relates to them differently: he cannot be arrogant about them, since they are not his, and he cannot be secure in them, since they are held by another’s will. 49:17 states the point bluntly to those who claimed credit for their belief: *“They consider it a favor to thee that they have submitted. Say: count not your submission as a favor to me — nay, God confers the favor upon you that He has guided you to faith, if you are truthful.”*

The verse thus completes the sequence begun at verse 85 in a single movement. The human being has been given little knowledge; what he has been given is held by another’s will; and the reason it is held there is mercy. The three statements together produce the disposition the sūrah has been building toward, which is the gratitude of verse 107 and 109 — prostration, weeping, and the glorification with which the sūrah ends."""),

88: ("**The Challenge, and the Fourfold Failure**",
"""This verse is the Qur’an’s fullest statement of its inimitability, and its form is a challenge with a specified condition. *Qul la-ini ijtamaʿat al-insu wa al-jinnu ʿalā an yaʾtū bi-mithli hādhā al-Qurʾāni lā yaʾtūna bi-mithlih* — say: if mankind and the jinn gathered to bring the like of this Qur’an, they would not bring the like of it. The condition combines the two classes of rational beings, and the commentators note that the inclusion of the jinn is significant: the challenge is not merely to human eloquence but to every articulate intelligence, and the Arabs of the seventh century — who believed in jinn and attributed poetry to them — could not dismiss the challenge as addressed to a weaker party.

The phrase *wa law kāna baʿḍuhum li-baʿḍin ẓahīrā*, even if some of them were helpers to others, adds the condition of cooperation and closes the last escape. Al-Zamakhsharī observes that the challenge is thus set at its most favorable to the challengers: all rational beings, cooperating fully. The Qur’an issues the same challenge three other times at descending scales — 10:38, bring a sūrah like it; 11:13, ten sūras like it, invented; 2:23, a single sūrah like it, with the invitation to call your witnesses besides God if you are truthful — and the descent is instructive, since the final and smallest demand was never met.

The doctrine of *iʿjāz*, inimitability, was developed systematically by al-Bāqillānī and after him by al-Khaṭṭābī, ʿAbd al-Qāhir al-Jurjānī, and al-Rāzī, and they identified three dimensions. The linguistic: the Qur’an’s composition (*naẓm*) is unlike any known form — neither poetry, since it does not observe meter, nor prose, since it observes a rhythmic structure of its own. The informational: it contains reports of the unseen, past and future, delivered by a man who could not read and had not studied. The legislative: its law has governed civilizations for fourteen centuries without requiring replacement. Al-Jurjānī’s contribution was to locate the inimitability in the *naẓm* — the specific arrangement of words in relation to meaning — rather than in any individual word or figure, which makes the challenge structurally impossible to meet by imitation, since imitation reproduces features rather than the principle of arrangement.

The historical attempts are recorded and are instructive in their failure. Musaylimah’s compositions were mocked by his own contemporaries; Ibn al-Muqaffaʿ, the greatest prose stylist of the second Islamic century, is reported to have attempted a chapter and abandoned it, saying that this is not the speech of mankind. The failure is the evidence, and the verse states in advance that it was not a matter of effort.

The verse’s function in the argument is to close the demands of verses 90–93. The opponents asked for a spring, a garden, a house of gold, a ladder to heaven, and a piece of the sky; the Qur’an answers that the sign they already possess is one that all of creation, cooperating, cannot reproduce — which reframes the demand entirely. The problem was never the insufficiency of evidence."""),

89: ("**Ṣarrafnā: The Variety of Illustration, and the Refusal That Followed It**",
"""The verb *ṣarrafa* is from the intensive form of *ṣ-r-f*, to turn, and in this context it denotes the varying and repeating of a thing in different forms. Al-Ṭabarī glosses it: We have set forth for mankind in this Qur’an, of every kind of likeness and argument, in varied and repeated forms. The verse is therefore a statement about method: the Qur’an does not present a truth once and move on, but returns to it from different angles, in different registers, with different illustrations.

The same verb is used of the Qur’an’s method at 6:105, 20:113, 25:33, 30:58, and 39:27, and the recurrence indicates a deliberate pedagogy. 39:27 states the reasoning: *“And We have set forth for mankind in this Qur’an every kind of likeness, that they may remember.”* The variation is not redundancy; it is the recognition that a single formulation reaches some minds and not others, and that a truth must be met from several directions before it is grasped. 6:65 states the same: *“See how We make the signs clear, that they may understand.”*

The second clause is the verse’s point: *fa-abā aktharu al-nās illā kafūrā* — but most people refuse, except in ingratitude. The construction *abā illā* is emphatic, denoting a refusal that admits nothing else. The verse therefore makes a claim that is central to the Qur’an’s diagnosis of unbelief: the obstacle was never the availability of evidence. 6:25 states the mechanism: *“And among them are those who listen to thee, but We have placed veils over their hearts so that they understand it not, and in their ears deafness.”* 41:44 supplies the confirmation from the objectors’ own mouths: had the Qur’an been revealed in a foreign tongue, they would have objected that its verses were not explained in detail — the objection was therefore ready before the explanation.

The word *kafūr*, intensive in form, denotes ingratitude as a settled character rather than a single act, and it echoes verse 67’s *wa kāna al-kāfiru kafūrā*. The pairing establishes that the refusal described here is the same disposition described there: the one who turns away after rescue. The verse’s argument is thus cumulative — the evidence has been varied and repeated, the refusal has persisted through every variation, and the persistence discloses that the cause of the refusal lies elsewhere.

Al-Rāzī draws the practical consequence for the one who conveys the message. Since the variety of illustration has not produced acceptance in most, the measure of success cannot be the hearer’s response; it must be the completeness of the delivery. The verse therefore releases the teacher from an impossible standard while raising another: the obligation is to vary the presentation until every available route has been tried, and then to leave the result. 5:92 states the same limit: *“Upon Our Messenger is only the clear conveyance.”*"""),

90: ("**Four Demands, and the Diagnosis Beneath Them**",
"""The verse records the conditions the Quraysh set for belief, and the list is specific enough to be historically useful. Al-Ṭabarī preserves the reports: a group of the Quraysh leaders said to the Prophet ﷺ that they would not believe until he produced a spring gushing from the earth for them, or a garden of dates and grapes with rivers flowing through it, or caused the sky to fall upon them in pieces as he had claimed, or brought God and the angels before them face to face, or had a house of gold, or ascended into heaven — and would not believe the ascent either until he brought down a book they could read.

The four demands divide into two pairs, and the division is diagnostic. The first pair — a spring, a garden, a house of gold — asks for material proof of prosperity, which is the criterion by which the Quraysh measured standing. The second pair — the ascent, the descending book — asks for a supernatural demonstration. Al-Rāzī observes the structure of the escalation: each demand is framed so that its fulfillment would produce the next. This is the character of a demand made not to obtain evidence but to avoid a conclusion, and the Qur’an identifies it as such at 6:109: *“They swear by God their most solemn oath that if a sign came to them they would believe in it. Say: signs are only with God — and what will make you aware that if it came they would not believe?”*

The Qur’an records the same pattern across the prophetic history, which is what makes the verse a general claim rather than a report. 2:55 records the demand to see God openly. 4:153 records the People of the Book asking for a book to come down from heaven, and answers it: *“We sent down to Moses clear signs.”* 6:124 records the demand for the prophethood to be given to the notables instead. 74:52 states the underlying disposition: *“Nay, every one of them desires that he be given pages spread open.”* The pattern is consistent: the demand is for terms rather than for truth, and the terms are set by the one who has already decided.

The verse’s answer is not a refusal but a redirection, and it is given in the following verses: the sign is already present in a form that cannot be reproduced (v. 88), the messenger cannot produce what is not his to produce (v. 91), and the objection to his humanity is an objection to the nature of messengership itself (vv. 94–95). The practical lesson is the one every person who has argued with a determined skeptic recognizes: a demand that escalates is not a search for evidence, and the correct response is to name the pattern rather than to meet the next demand."""),

91: ("**Basharan Rasūlā: The Two Nouns That Answer the Objection**",
"""The verse records the most extreme of the demands and gives the sūrah’s shortest and most important answer. *Aw tusqiṭa al-samāʾa kamā zaʿamta ʿalaynā kisafā* — or that thou cause the sky to fall upon us in pieces, as thou hast claimed. The demand invokes the Prophet’s ﷺ own warning, turning it into a test: if you say the sky will fall, make it fall. The verb *zaʿama* — to claim, to assert — is used of the warning here by the opponents, and the Qur’an uses the same verb of false claims at 4:117 and 6:148, so the opponents’ choice of word is itself a verdict on the warning.

The answer is the verse’s substance: *qul subḥāna rabbī hal kuntu illā basharan rasūlā* — say: glory be to my Lord; am I anything but a human messenger? The two nouns are the answer, and each does a distinct work. *Bashar* denotes the human being in his physical, mortal, limited aspect — the same word used at 3:47, 19:20, and 12:31, where the women cut their hands and said *this is not a human being*. *Rasūl* denotes the one sent with a message. The two together state the Islamic doctrine of prophethood in four words: the messenger is fully human and fully sent, and neither term cancels the other.

The glorification that precedes the answer is significant. Al-Qurṭubī explains it as the response to the implication of the demand, which was that the Prophet ﷺ claimed divine power; *subḥāna rabbī* removes the implication before the answer is given. The construction *hal kuntu illā* — am I anything but — is a rhetorical question that expects the answer *no*, and the verse thereby makes the opponents answer their own objection: he never claimed to be able to bring down the sky, so the demand is not a test of his claim but a substitution of a claim he did not make.

The Qur’an insists on the messenger’s humanity throughout, and the insistence is a refusal of the two opposite errors. 5:75 states it of Jesus: *“The Messiah, son of Mary, was only a messenger; messengers passed away before him.”* 6:50 gives the Prophet ﷺ his own formula: *“Say: I do not say to you that I have the treasures of God, nor that I know the unseen, nor that I am an angel; I follow only what is revealed to me.”* 41:6 records the command: *“Say: I am only a human being like you, to whom it is revealed that your God is one God.”* The error the verse blocks is the elevation of the messenger to a share in divine power, and the error it blocks at the same time is the reduction of the message to the messenger’s own invention.

The verse therefore completes the argument of the sūrah’s central section. The demands are impossible because the messenger is human; the message is authoritative because the messenger is sent; and the glorification belongs to God alone, which is where the sūrah began."""),

92: ("**The Objection Reversed: What the Demand for a Human Messenger Conceals**",
"""The verse states the objection in its own terms and then exposes what it conceals. *Wa mā manaʿa al-nāsa an yuʾminū idh jāʾahumu al-hudā illā an qālū a-baʿatha Allāhu basharan rasūlā* — and nothing prevented people from believing when the guidance came to them except that they said: has God sent a human being as a messenger? The construction is precise: the obstacle is identified not as a lack of evidence but as an objection to the form of the evidence.

Al-Rāzī’s analysis of the objection is the sharpest available, and it turns on what the objection does not say. The objectors did not claim that a human messenger is impossible — their own tradition affirmed prophets who were human — but that *this* human was not the one they would have chosen. 43:31 states the objection explicitly in those terms: *“And they said: why was not this Qur’an sent down to a great man of the two cities?”* — meaning al-Walīd ibn al-Mughīrah of Makkah or ʿUrwah ibn Masʿūd of Ṭāʾif. 6:124 supplies the answer: *“God knows best where to place His message.”* The objection is therefore not theological but social: it is a claim about who deserves precedence, and it is made by the people who hold it.

The Qur’an records the same objection against every prophet, and the record is what makes the verse a general diagnosis rather than a report. 14:10–11: *“Their messengers said to them: we are only human beings like you, but God confers His favor upon whom He wills of His servants.”* 23:33–34 records the objection against a prophet who ate food: *“What is this but a human being like you? He eats what you eat and drinks what you drink.”* 25:7 records it against the Prophet ﷺ in the same words, adding the demand for an angel or a treasure. The consistency across the prophetic history is the evidence: an objection that recurs identically against every messenger is not about the messenger.

The verse’s own answer is given in the next verse, and it is structural rather than defensive: a messenger must be of the kind of those to whom he is sent, or he cannot be received. The demand for a non-human messenger is therefore a demand for a message that could not be understood, and the objectors’ position is self-refuting — they ask for what would defeat the purpose of the asking.

The practical content of the verse is its account of how objections work. An objection raised against the *form* of a message rather than its content is usually a report about the objector’s expectations, and it is answered not by improving the form but by naming the expectation. The Qur’an does exactly that, and does it in a single clause: what prevented them from believing was what they said."""),

93: ("**Law Kāna fī al-Arḍi Malāʾikah: The Necessity of Congruence**",
"""The verse is the Qur’an’s answer to the objection of verse 92, and the answer is a principle rather than a defense. *Qul law kāna fī al-arḍi malāʾikatun yamshūna muṭmaʾinnīna la-nazzalnā ʿalayhim mina al-samāʾi malakan rasūlā* — say: if there were on earth angels walking about in settled habitation, We would surely have sent down to them from heaven an angel as a messenger. The clause *yamshūna muṭmaʾinnīna* is important: it denotes angels established as inhabitants of the earth, walking upon it in settled life, and al-Qurṭubī glosses it as dwelling and being at ease in it, as human beings do.

The principle is that the messenger must be of the kind of the recipients. Al-Rāzī develops the reasoning across four grounds. First, comprehension: a being of another order could not be understood, since communication requires a shared medium. Second, imitation: the messenger is a model, and a model of a different nature cannot be followed — 33:21 describes the Prophet ﷺ as *uswah ḥasanah*, a good example, which requires that his life be reproducible. Third, endurance: the recipients could not bear the presence of a being of another order, and the Qur’an states this at 6:9: *“Had We made him an angel, We would have made him in the form of a man, and We would have covered them with the very thing they cover themselves with.”* Fourth, verification: a claim made by a being whose nature cannot be tested cannot be checked, and the human messenger’s life is open to inspection.

The Qur’an states the same principle elsewhere with equal clarity. 16:43 and 21:7 both command: *“Ask the people of the remembrance if you do not know”* — and the preceding clause in both is *“We sent not before thee except men to whom We revealed.”* 25:20 generalizes it: *“And We sent not before thee any messengers but they ate food and walked in the markets.”* The eating and the walking are not incidental; they are the evidence of the congruence that makes the message receivable.

The verse therefore turns the objection into its own refutation. The demand for an angelic messenger is a demand for a messenger who could not communicate, could not be imitated, could not be endured, and could not be verified — which is a demand for no messenger at all. Al-Zamakhsharī states the conclusion in one line: the objection proves the necessity of what it objects to.

The practical consequence is a criterion for evaluating any teacher. The one who claims a standing beyond testing, whose life cannot be inspected and whose example cannot be followed, has removed the very features that make teaching possible — and the Qur’an’s insistence on the messenger’s humanity is the permanent guard against that removal. 5:75 states it as a general rule: *“The Messiah, son of Mary, was only a messenger; messengers passed away before him.”*"""),

94: ("**Kafā bi-Allāhi Shahīdā: The Witness That Suffices**",
"""The command *qul* introduces the sūrah’s central formula of sufficiency, and the formula appears twice in these verses — here and again at verse 96. *Qul kafā bi-Allāhi shahīdan baynī wa baynakum* — say: sufficient is God as a witness between me and you. The word *shahīd* denotes a witness in the full legal sense: one who is present, who knows, and whose testimony is accepted. The verse therefore transfers the case from the court of public opinion to a court whose witness is God.

The clause that follows specifies what God witnesses: *innahu kāna bi-ʿibādihī khabīran baṣīrā* — indeed He is, of His servants, All-Aware, All-Seeing. The two divine names are precise and they divide the knowledge between them. *Khabīr* is from *kh-b-r*, to be acquainted with a thing through testing and experience, and it denotes knowledge of the inner reality, the motive beneath the act. *Baṣīr* denotes the seeing of what is manifest. Al-Rāzī observes that the pairing is complete: nothing is hidden from Him either within or without, which is what makes His testimony sufficient where human testimony is not.

The verse’s function is consolatory, and its placement makes that clear. It follows the demands of verses 90–93 and the objection to the messenger’s humanity, and it answers them not by argument but by referral. The messenger who has been asked to produce springs and gardens and to bring down a book from heaven is told that the case does not need to be won in that forum, because the forum is not competent. 10:29 makes the same move: *“Say: is any of your partners able to guide to the truth? Say: God guides to the truth.”* 48:28 states the same sufficiency in the register of the message’s destiny: *“He it is Who sent His Messenger with the guidance and the religion of truth, that He may make it prevail over all religion — and sufficient is God as a witness.”*

The second use of the formula at verse 96 is shorter and sharper — *qul kafā bi-Allāhi shahīdan baynī wa baynakum* repeated — and the repetition indicates that the point needed making twice. 13:43 uses it in the same context of rejection: *“And those who disbelieve say: thou art not a messenger. Say: sufficient is God as a witness between me and you, and whoever has knowledge of the Book.”* 29:52 uses it to close an argument: *“Say: sufficient is God as a witness between me and you; He knows what is in the heavens and the earth.”*

The practical content of the verse is the discipline it supplies to anyone who has been required to prove himself to people who have already decided. The effort is not merely futile but misdirected, since the case is not before them. The verse does not counsel silence — the Prophet ﷺ continued to convey the message for thirteen more years — but it relocates the verdict, and the relocation is what makes sustained effort possible without either coercion or despair."""),

95: ("**The Alternative Universe, and What It Proves**",
"""The verse completes the principle stated at verse 93 by describing the counterfactual explicitly. *Wa law kāna fī al-arḍi malāʾikatun yamshūna muṭmaʾinnīna la-nazzalnā ʿalayhim mina al-samāʾi malakan rasūlā* — and had there been on earth angels walking in settled habitation, We would have sent down to them from heaven an angel as a messenger. The verse thus constructs the alternative universe in which the objectors’ demand would have been correct, and shows that even there the rule holds: the messenger is of the kind of the recipients.

Al-Qurṭubī explains the phrase *yamshūna muṭmaʾinnīna* as denoting settled inhabitants, at ease upon the earth as human beings are — and the specification matters, because it excludes the angels who descend on errands. The verse is not about visiting angels but about a population. The reasoning is then airtight: if the inhabitants were angels, the messenger to them would be an angel, because only an angel could live among them, speak to them, and be imitated by them. The congruence is not a preference but a requirement of communication.

Al-Rāzī draws the corollary that closes the objection of verse 92. The demand for an angelic messenger from human beings is a demand for a messenger who would be to them what an angel would be to angels — but the recipients are human, and a messenger of another order cannot be received by them. The demand is therefore not merely unreasonable but incoherent: it asks for the conditions of a different world while remaining in this one.

The verse also answers an objection that had not yet been raised explicitly, which is why al-Zamakhsharī treats it as a preemptive answer. The objection would run: if the messenger must be of the recipients’ kind, why are the angels messengers at all? The answer is that the angels are messengers *to the prophets*, not to the communities — 22:75, *“God chooses messengers from the angels and from mankind”* — and the communication from angel to prophet is of a different order than the communication from prophet to people, which is why the prophets experience it as a weight and the people receive it as speech. 26:193–194 describes the descent: *“The trustworthy Spirit brought it down upon thy heart, that thou mayest be among the warners.”*

The practical consequence of the two verses together is a rule for every form of teaching. The teacher who is unlike his students in kind cannot reach them, and the students who demand a teacher of another kind are demanding not to be taught. This is why the Qur’an insists on the Prophet’s ﷺ humanity with such persistence — it is not a limitation to be excused but the condition of the message’s arrival, and 12:109 states the rule in its general form: *“We sent not before thee except men to whom We revealed, from the people of the towns.”*"""),

96: ("**The Second Sufficiency, and the Knowledge of the Servants**",
"""The verse repeats the formula of sufficiency and adds a specification. *Qul kafā bi-Allāhi shahīdan baynī wa baynakum* — say: sufficient is God as a witness between me and you. The repetition of the formula from verse 94 within two verses is unusual in the Qur’an and indicates emphasis, and al-Qurṭubī notes that the second occurrence is shorter, which sharpens rather than weakens it.

The added clause specifies the content of the divine witness: *innahu kāna bi-ʿibādihī khabīran baṣīrā* — He is, of His servants, All-Aware, All-Seeing. The word *ʿibād*, servants, is the term the Qur’an uses of human beings in their relation of dependence, and its appearance here is significant: the ones being witnessed are not described as believers and disbelievers but as servants, which places both parties in the same relation and removes the possibility of one party’s claiming a standing the other lacks.

The two names divide the knowledge between the hidden and the manifest, and the division is what makes the testimony sufficient. *Khabīr* denotes acquaintance with the inner reality — the motive, the intention, the state of the heart; *baṣīr* denotes the seeing of what is outward. A human witness can testify to the second and not to the first, which is why human testimony requires corroboration and divine testimony does not. 5:117 records the Prophet ʿĪsā making exactly this distinction: *“I was a witness over them while I was among them, but when Thou didst take me, Thou wast the Watcher over them — and Thou art Witness over all things.”*

The verse’s function within the argument is to close the sequence begun at verse 90. The demands have been answered, the objection to the messenger’s humanity has been turned into a proof, and the case has been referred to a competent witness. The Qur’an does not leave the messenger to argue the case further, and the referral is not a retreat but a conclusion: there is nothing left to establish, because the establishment is not in the messenger’s hands.

The practical application of the verse is available to anyone who has been required to prove his sincerity to people who have decided against it. The effort to establish sincerity by demonstration is not merely difficult but structurally unavailable, since sincerity is inward and demonstration is outward — which is why the Qur’an’s repeated answer to such demands is not more evidence but the naming of the Witness. 29:52 makes the same move at the close of an argument, and 46:8 poses the question that the verse answers: *“Say: do you see what you call upon besides God? Show me what they have created in the earth.”*"""),

97: ("**Gathered Upon Their Faces: The Completion of the Blindness**",
"""The verse states the outcome and then describes it with an image of unusual severity. *Wa naḥshuruhum yawma al-qiyāmati ʿalā wujūhihim ʿumyan wa bukman wa ṣummā* — and We shall gather them on the Day of Resurrection upon their faces, blind, dumb, and deaf. The commentators offer two readings of *ʿalā wujūhihim* and both are attested. The literal: they will be dragged upon their faces, and al-Ṭabarī preserves the report that a companion asked how the disbeliever would walk upon his face and the Prophet ﷺ answered that the One who made him walk upon his feet in this world is able to make him walk upon his face in the next. The figurative: they will be gathered in humiliation, as one says of a man disgraced that he has fallen on his face.

The triple privation — blind, dumb, deaf — completes the sequence begun at verse 72, where the one who is blind in this world is blind in the next, and at verse 46, where the coverings and the deafness are described. The Qur’an’s account is therefore continuous rather than punitive: the faculties that were not used are not restored but confirmed in their atrophy. 20:124–126 makes the same point in dialogue, and the answer given to the blind man’s question — *thus it is, Our signs came to thee and thou didst forget them* — locates the cause in the worldly life.

The word *maʾwāhum*, their abode, denotes a place of dwelling and return rather than a temporary station, and the verse’s final clause describes the fire’s persistence: *kullamā khabat zidnāhum saʿīrā* — whenever it abates, We increase for them a blaze. The verb *khaba* denotes a fire that dims and loses its flame, and al-Qurṭubī explains the clause as the rekindling of a fire that would otherwise go out — the punishment is not a fixed quantity that is exhausted but a condition that is renewed. 4:56 states the same: *“Whenever their skins are roasted through, We shall change them for other skins, that they may taste the punishment.”*

The verse’s placement after the argument about the messenger’s humanity is significant. The objections of verses 90–95 are answered, and the verse supplies the consequence of persisting in them. The sequence is not a threat appended to an argument but the argument’s completion: a message refused has an outcome, and the outcome is described in the same terms as the refusal — blindness for those who would not see, deafness for those who would not hear, and silence for those who would not speak the truth they recognized.

The pastoral reading of the verse is the one the tradition drew from it. The descriptions of the Hereafter are not decorations but the completion of dispositions formed here, and the completion is what makes the present moment consequential. 39:56 supplies the corresponding appeal, addressed to the one still able to act: *“Lest a soul should say: alas, my grief for what I neglected of my duty toward God, and I was among the mockers.”*"""),

98: ("**The Objection Repeated Verbatim: The Argument’s Structural Closure**",
"""The verse repeats the objection of verse 49 almost word for word, and the repetition is the sūrah’s most striking structural device. *Wa qālū a-idhā kunnā ʿiẓāman wa rifātan a-innā la-mabʿūthūna khalqan jadīdā* — and they say: what, when we are bones and dust, shall we indeed be raised up as a new creation? The same three elements return — the bones, the powdered remains, the new creation — and the same incredulous interrogative opens the sentence.

The effect of the verbatim repetition is to mark the objection as unanswered by the objector rather than by the Qur’an. Between verse 49 and verse 98 the Qur’an has supplied the argument from origination (vv. 50–51), the collapse of duration (v. 52), the account of the Day (vv. 71–72, 97), and the demonstration from the greater creation. The objection returns unchanged, which is itself the finding: the difficulty was never argumentative. 6:109–110 states the mechanism explicitly: *“And even if We sent down to them the angels, and the dead spoke to them, and We gathered all things before them face to face, they would not believe unless God willed — but most of them are ignorant.”*

The verse’s answer is the same one given at verse 51, now with the argument made explicit: *a-wa lam yaraw anna Allāha alladhī khalaqa al-samāwāti wa al-arḍa qādirun ʿalā an yakhluqa mithlahum* — have they not seen that God, Who created the heavens and the earth, is able to create the like of them? The argument is from the greater to the lesser, and the Qur’an uses it repeatedly: 36:81, *“Is not He Who created the heavens and the earth able to create the like of them? Yes indeed, and He is the All-Knowing Creator.”* 40:57 states the comparative explicitly: *“The creation of the heavens and the earth is greater than the creation of mankind, but most people know not.”* 79:27–28 supplies the cosmological premise.

The clause *mithlahum*, the like of them, has been read two ways by al-Ṭabarī, and both are held: the recreation of the same individuals, and the creation of others like them. The first is the reading the resurrection requires, and the second strengthens the argument rather than weakening it, since a being able to produce a like from nothing is a fortiori able to restore what He already made.

The verse’s placement completes the sūrah’s argument about the Hereafter, which began at verse 10 with the denial of it and returns at verses 49, 52, 72, 97, and here. The repetition of the objection at both ends of the section, with the argument between them, is the Qur’an’s method of demonstrating that the obstacle is not intellectual — and the demonstration is made not by assertion but by the objector’s own unchanged words."""),
}
p='expanded/017.md'
s=open(p,encoding='utf-8').read()
parts=re.split(r'(?m)^(## Sūrah al-Isrāʾ 17:\d+)$', s)
d={int(parts[i].split(':')[1]):[parts[i],parts[i+1]] for i in range(1,len(parts),2)}
for n,(h,t) in ADD.items():
    body=d[n][1]
    hs=[m.start() for m in re.finditer(r'(?m)^\*\*(?!Expanded Commentary).+?\*\*$', body)]
    assert hs, n
    ins=hs[-1]
    d[n][1]=body[:ins]+'**'+h+'**\n\n'+t.strip()+'\n\n'+body[ins:]
out=[parts[0]]
for i in range(1,len(parts),2):
    n=int(parts[i].split(':')[1]); out.append(d[n][0]); out.append(d[n][1])
open(p,'w',encoding='utf-8').write(''.join(out))
print('added',len(ADD),'| words now',len(''.join(out).split()))
