import re
ADD = {
71: ("**Bi-Imāmihim: One Word, Four Readings, and What Each Implies**",
"""The word *imām* in this verse has generated more exegetical discussion than any other in the sūrah, and the plurality of readings is instructive rather than confusing, because each is attested and each produces a coherent account of the Day. Al-Ṭabarī catalogues them. The first, from Ibn ʿAbbās and a number of the Salaf: *imām* means the prophet — every community will be called by its prophet, who will testify to what he conveyed. The second: the scripture — the people of the Torah called by the Torah, the people of the Gospel by the Gospel, the people of the Qur’an by the Qur’an. The third: the book of deeds, which the following verse appears to support with *fa-man ūtiya kitābahu bi-yamīnih*, whoever is given his book in his right hand. The fourth: the leader whom the people followed, whether prophet or false guide — 25:41 records the mockery of the false leader, and 2:166–167 describes the followers disowning the followed.

The Qur’an itself uses *imām* in each of these senses, which is why the exegetes could sustain all four. 11:17 describes the Qur’an as preceded by the Book of Moses *imāman wa raḥmah* — a guide and a mercy. 15:79 uses it of a road, *ʿalā imāmin mubīn*. 36:12 uses it of the record in which everything is inscribed, *fī imāmin mubīn*. 2:124 uses it of a human leader, *“I will make thee an imām for mankind.”* The word therefore spans the meanings of guide, model, record, and road, and the verse exploits the range.

Al-Qurṭubī adds the Shīʿite reading — that the *imām* is the imām of the age, whose obedience or neglect determines the community’s standing — and records the report attributed to ʿAlī that the verse refers to the imāms of every age. The exegetes treat this as a possible specification rather than a contradiction, since it falls under the fourth reading. The reports that the communities will be called by their mothers’ names rather than their fathers’ appear in the collections in connection with this verse, and al-Qurṭubī preserves the reasoning: the mother’s name is certain.

The verse’s function is to establish that the summons is not anonymous. The individual is not called as a member of an undifferentiated mass but by reference to what he followed, what he was given, and what he was sent. Al-Rāzī draws the consequence: the calling by the *imām* means the standard is fixed in advance and cannot be renegotiated, which is why the following verse describes the immediate consequence — reading one’s own record — with such precision. The verse that closes the passage, 71’s own final clause, states the outcome in two lines: whoever is given his book in his right hand will read it with pleasure and will not be wronged the width of a date-stone’s thread."""),

72: ("**Blind Here, Blind There: The Continuity Rather Than the Reversal**",
"""The verse is one of the Qur’an’s clearest statements that the Hereafter is not a reversal of the earthly condition but its completion. *Wa man kāna fī hādhihī aʿmā fa-huwa fī al-ākhirati aʿmā wa aḍallu sabīlā* — whoever is blind in this life is blind in the Hereafter, and further astray from the way. The comparative *aḍallu sabīlā* is the crucial word: the blindness is not merely continued but intensified, and the intensification has a reason.

Al-Ṭabarī records the two readings of the first blindness and holds both. The first: blind to God’s blessings and evidences, unable to see the signs that are set before him. The second: blind to the arguments and the guidance, which is the condition described at verses 45–46 with the coverings and the deafness. The two are related as symptom and cause, and the verse treats the blindness as a settled state rather than an event — *kāna fī hādhihī aʿmā*, he *was* blind in this, using the verb of being rather than of becoming.

The Qur’an supplies the mechanism elsewhere, and 20:124–126 states it with a dialogue that makes it concrete. The one who turns away from God’s remembrance is given a constricted life and raised blind on the Day; he asks, *“My Lord, why hast Thou raised me blind, when I was seeing?”* — and the answer is not a punishment imposed from outside but a disclosure: *“Thus it is — Our signs came to thee and thou didst forget them, and likewise today thou art forgotten.”* The blindness in the Hereafter is the worldly blindness, now permanent and now visible to its possessor. This is why it is worse: the man who could not see in a world where seeing was optional cannot see in a world where seeing is the only activity.

The theological principle beneath the verse is that the soul’s dispositions survive death. The faculties that were atrophied by disuse do not become functional at the resurrection, and the ones that were trained do not become atrophied. 35:43 states the corollary: *“Do they await anything but the way (sunnah) of the former peoples? Thou wilt find no change in the way of God.”* And 6:110 describes the process: *“And We shall turn their hearts and their sight, as they did not believe in it the first time.”*

The pastoral weight of the verse is therefore on the word *kāna* — was. The condition is acquired over time, in this life, by a series of refusals, none of which seemed decisive. The verse is a warning about accumulation rather than about a single act, and it locates the moment of decision not in the Hereafter but in the ordinary Tuesday on which a person decides not to look."""),

73: ("**They Very Nearly Made You Lean: The Pressure at the Point of Concession**",
"""The occasions recorded for this verse are among the most historically specific in the Qur’an, and the verse’s candid reporting of the Prophet’s ﷺ near-inclination is one of the strongest evidences of its own authenticity. Al-Ṭabarī preserves the reports at length. One group of them concerns the delegation of the Thaqīf from Ṭāʾif, who proposed conditions: that the valley of Ṭāʾif be granted to them, that wine and interest be permitted them for a period, that the idol al-Lāt not be broken, and that they be exempt from the prayer’s prostration. Another concerns the Quraysh leaders who offered a reciprocal arrangement — that the Prophet ﷺ cease reviling their gods and they would cease opposing him, or that the poor believers be driven from his assembly so that the notables might sit with him. 6:52 records the answer to the second proposal, and 80:1–10 records the rebuke when the Prophet ﷺ turned away from a blind man to address the notables.

The grammar of the verse is precise. *Wa in kādū la-yaftinūnaka* — they very nearly tempted thee away from what We revealed to thee — uses the construction of near-occurrence, and al-Qurṭubī notes that *kāda* in Arabic, when followed by the imperfect without an accompanying statement of occurrence, indicates that the thing did not happen. The verse therefore records an approach that was withstood, not a lapse. The phrase *li-taftariya ʿalaynā ghayrah*, that thou shouldst invent something other than it against Us, names the exact demand: not the abandonment of the message but its modification.

This distinction is the verse’s permanent content. The pressure on a messenger is rarely to abandon the truth outright, since that would be recognized and refused; it is to adjust it — to soften one clause, to grant one exemption, to accommodate one interest. The verse identifies the offer precisely, and identifies the reward offered for it: *wa idhan la-ittakhadhūka khalīlā*, and then they would have taken thee as an intimate friend. The price of the modification is friendship with the people whose demands were modified, which is to say that the accommodation purchases the accommodation’s own reward. 68:8–9 states the same offer in its shortest form: *“They wish that thou shouldst be pliant, so that they may be pliant (waddū law tudhinu fa-yudhinūn).”*

The verse’s theological significance is that *ʿiṣmah*, the protection of the prophets, is protection under pressure rather than immunity from it. The near-inclination was real — the following verse says so explicitly — and what prevented its realization was divine confirmation, which is stated as a fact rather than as a merit of the Prophet ﷺ. The lesson for anyone who carries a message is the one the verse models: the pressure will come in the form of a reasonable proposal, and the test will not feel like a test."""),

74: ("**Wa Lawlā an Thabbatnāka: The Firmness That Is Not Self-Generated**",
"""The verse completes the preceding one, and its construction is a conditional whose antecedent is negated: *and had We not made thee stand firm, thou wouldst very nearly have inclined toward them a little*. Al-Qurṭubī and al-Rāzī both note the Arabic principle that *kāda* with the imperfect negates the action — “he very nearly did” means he did not — so the verse asserts both the reality of the pressure and the fact of its resistance, and attributes the resistance to God.

The verb *thabbata* is from the intensive form of *th-b-t*, to make firm, to establish, to fix in place, and it is the Qur’an’s standard term for the divine confirmation of the believer. 14:27 states the general promise: *“God confirms those who believe with the firm word (bi-l-qawl al-thābit) in the life of this world and in the Hereafter.”* 8:11 describes the confirmation at Badr: *“...that He might thereby confirm the hearts.”* 3:146 records the prayer of the steadfast: *“Our Lord, pour patience upon us and make our feet firm (wa thabbit aqdāmanā).”* And 22:15 supplies the challenge implicit in all of it: whoever thinks God will not help His Messenger should stretch a rope to the ceiling and cut it off.

The clause *wa idhan la-kādū yastafizzūnaka min al-arḍ* — and then they would very nearly have provoked thee to leave the land — records the second stage of the pressure: having failed to modify the message, the opponents move to remove the messenger. The Qur’an states the rule that follows in the next verse, and history supplied the confirmation: the expulsion was attempted, the Hijrah occurred, and the one expelled returned to the land eight years later.

The pastoral content of the verse is its account of where steadfastness comes from. It is not a natural virtue that some people possess and others lack; it is a confirmation conferred, and it is conferred in proportion to the pressure rather than in spite of it. The person who concludes from his own wavering that he is unfit has misread the verse, since the verse reports wavering in the most steadfast of human beings and locates the remedy outside him. 3:103 states the means by which the confirmation is normally given: *“And hold fast, all of you together, to the rope of God, and be not divided.”*

The final clause of the verse is the one that has made it a text of consolation across the tradition. Having recorded that the pressure was severe and the inclination real, the Qur’an adds: *wa idhan lā yalbashūna khilāfaka illā qalīlā* — and then they would not have remained after thee except a little. The threat to the opponents is that the arrangement they sought would have been brief, which is the standard answer to every accommodation: what is purchased by modifying the truth does not last long enough to be worth the modification."""),

75: ("**Double in This Life and Double in Death: The Weight of Station**",
"""The verse states a principle that runs through the Qur’an’s treatment of those closest to God: the greater the station, the greater the accountability. *Idhan la-adhaqnāka ḍiʿfa al-ḥayāti wa ḍiʿfa al-mamāt* — then We would have made thee taste double in this life and double in death. The word *ḍiʿf* means a multiple, and the commentators explain the doubling as the punishment of one who had received what no one else received: the revelation, the direct confirmation, and the rank. Al-Qurṭubī connects it to 33:30, addressed to the Prophet’s ﷺ wives: *“O wives of the Prophet, whoever of you commits a manifest indecency, the punishment for her will be doubled — and that is easy for God.”*

The logic is stated most clearly in the same passage of Sūrah al-Aḥzāb, where the doubling is paired with its opposite: *“And whoever of you is obedient to God and His Messenger and does righteousness, We shall give her reward twice over”* (33:31). The multiplication runs in both directions and follows from the same premise — nearness to the source increases the weight of everything done in relation to it. 2:286 states the general rule of proportionality, *“God does not burden a soul beyond its capacity,”* and the verse here is the specific application to the one whose capacity was greatest.

The final clause — *thumma lā tajidu laka ʿalaynā naṣīrā* — repeats the formula of verses 68 and 69, where the disbeliever finds no *wakīl* and no *tabīʿ*. Its application to the Prophet ﷺ is not a warning about him but a statement about the structure: no one, at any rank, has a helper against God. The most honored of human beings stands in the same relation to the divine judgment as everyone else, and the honor is precisely what makes the relation weightier.

The verse’s general application has been drawn by the tradition consistently. The scholar, the judge, the preacher, and the leader carry a doubled accountability, since their error is not merely their own — it is transmitted, imitated, and cited. The Prophetic formulation is at Muslim 1017: *“Whoever sets a good precedent in Islam will have its reward and the reward of all who act upon it after him, without that diminishing their reward in any way; and whoever sets an evil precedent in Islam will bear its burden and the burden of all who act upon it after him, without that diminishing their burden in any way.”* The mechanism the verse describes is therefore already familiar in the ethical register: influence multiplies consequences in both directions."""),

76: ("**The Attempted Expulsion, and the Rule That Would Have Followed It**",
"""The verse records a plot and states the divine practice that governs such plots. *Wa in kādū la-yastafizzūnaka min al-arḍ li-yukhrijūka minhā* — they very nearly provoked thee to leave the land, to expel thee from it. Al-Ṭabarī preserves the reports: the Quraysh convened to decide the Prophet’s ﷺ fate and settled on the plan that 8:30 describes — *“And when those who disbelieved plotted against thee to imprison thee, or kill thee, or expel thee; they plot, and God plots, and God is the best of plotters.”* The three options in that verse are the historical alternatives, and the third was chosen: the expulsion, which became the Hijrah.

The verse’s second clause states the *sunnah* that would have applied: *wa idhan lā yalbathūna khilāfaka illā qalīlā*, and then they would not have remained after thee except a little. Al-Qurṭubī explains it as the established practice with the prophets — a people who expel their messenger is destroyed shortly after, and the commentators cite the cases of Ṣāliḥ and Lot. The statement is thus a counterfactual with a known antecedent, and history supplied the confirmation in a form the verse did not predict: the expulsion occurred, the destruction of the expellers did not, and the one expelled returned to the city within eight years. The reason, on the exegetes’ account, is the same one given at verse 59 for the withholding of the sign: the reprieve was extended so that most of the expellers might believe, and most of them did.

The verse’s third clause generalizes the case: *sunnata man qad arsalnā qablaka min rusulinā* — the way of those We sent before thee among Our messengers. The Qur’an treats the history of prophecy as a source of law rather than of anecdote, and the word *sunnah* — practice, established way — is the technical term for it. The following verse makes the constancy explicit, and the pairing produces the Qur’an’s philosophy of history: events are not unique but instances, and the instances are governed by rules that can be known.

The practical consequence for a reader is that the verse supplies a diagnostic for persecution. A community that expels those who tell it what it does not wish to hear is following a pattern with a known outcome, and the outcome does not depend on the strength of the expellers. 22:40–41 states the same principle from the other side, describing those who were expelled from their homes for saying *our Lord is God*, and promising that God will surely support those who support Him."""),

77: ("**Lan Tajida li-Sunnatinā Taḥwīlā: The Constancy of the Divine Way**",
"""The verse is the shortest and the most consequential statement of the Qur’an’s philosophy of history. *Sunnata rabbinā* — the way of thy Lord — is described with two negations: no *taḥwīl*, no alteration, and no *tabdīl*, no substitution. The distinction between the two words has been pressed by the commentators. *Taḥwīl* is the transformation of a thing into something else while it remains itself; *tabdīl* is its replacement by another. The verse therefore denies both that the divine practice changes in its operation and that it is superseded by a different practice, and the double denial is exhaustive.

The formula appears at four other places in the Qur’an, always in the same sense and always attached to a historical claim. 33:62: *“The way of God with those who passed away before — thou wilt find no change in the way of God.”* 35:43: *“...the evil plot encompasses only its makers. Do they await anything but the way of the former peoples? Thou wilt find no change in the way of God, and thou wilt find no alteration in the way of God.”* 40:85 uses it of the failure of a faith adopted only at the moment of punishment. 48:23 uses it of the victory granted to the messengers. The consistency of the formula indicates that the Qur’an treats God’s dealings with human communities as law-like rather than as a sequence of unrelated interventions.

Al-Rāzī draws the epistemological consequence, and it is a strong one: if the divine practice is constant, then the past is evidentially available to the present. This is the ground of the Qur’an’s repeated commands to travel and observe — 3:137, *“Say: travel in the earth and see what was the end of those who denied”*; 6:11, 12:109, 22:46, 29:20, 30:42, 40:21, 47:10. The ruins are not decoration but data, and the sūrah made the point concretely at verse 58 with the cities destroyed before their inhabitants’ term.

The modern reader can state the verse’s claim without theological vocabulary: history has regularities, the regularities are moral as well as material, and a society that violates them will experience the consequences regardless of its power. The verse’s function in the argument of the sūrah is to close the sequence begun at verse 73. The opponents proposed a modification, then an expulsion; the Qur’an answered that both have been tried before, by others, with known results, and that the results are not negotiable. 21:5 supplies the shortest form of the same point: *“Or has there come to them a reminder which the former peoples did not receive?”* — the answer being that the reminder is the same one they received, and so is the outcome."""),

78: ("**Li-Dulūki al-Shams: Legislation at the Heart of the Argument**",
"""The sūrah pauses here, in the middle of its argument with the Quraysh, to legislate the prayer times, and the placement is itself a statement. Al-Ṭabarī records the linguistic dispute over *dulūk*, and the majority position — held by Ibn ʿAbbās, Ibn ʿUmar, and most of the jurists — is that it denotes the sun’s decline from the meridian, so that the verse’s first clause covers the midday and afternoon prayers. The minority reading takes it as the sun’s setting, covering the evening prayer. The verse’s remaining clauses cover the rest: *ghasaqi al-layl*, the darkening of the night, gives the night prayer, and *qurʾāna al-fajr* gives the dawn prayer.

The verse is therefore one of the principal scriptural grounds of the five daily prayers, and the jurists read it together with its parallels: 11:114, *“And establish the prayer at the two ends of the day and in the hours of the night”*; 20:130, *“...and glorify thy Lord before the rising of the sun and before its setting, and in the hours of the night”*; and 30:17–18, which enumerates the times explicitly — evening and morning, and in the afternoon and at noon. The Prophetic elaboration is the ḥadīth of the two times for each prayer, recorded by Muslim (612), in which Gabriel leads the Prophet ﷺ through each prayer at its earliest and its latest time across two consecutive days and says: *“The time is between these two.”*

The phrase *qurʾāna al-fajr* is read by al-Ṭabarī and Ibn Kathīr as denoting the dawn prayer itself, the recitation being named for the prayer as a whole by way of its most distinguishing element. The clause *inna qurʾāna al-fajri kāna mashhūdā* — the recitation of the dawn is witnessed — is explained by the commentators with reference to the reports that the angels of the night and the angels of the day attend it together, which is why the congregation at that hour is described as attended by witnesses unseen. 50:40 and 52:49 use the same device of naming the prayer by its recitation.

The structural point is what makes the verse matter here. The sūrah has just argued that the opponents’ proposals are impossible, that the messenger cannot be modified or expelled without consequence, and that the divine practice is unchanging; and then it turns to the messenger and tells him when to pray. The sequence asserts that the response to opposition is not counter-argument but worship, and 20:130 makes the connection explicit: *“And be patient over what they say, and glorify thy Lord with the praise of thy Lord before the rising of the sun and before its setting.”* The legislation is placed inside the polemic because the polemic is not the point — the establishment of worship is."""),

79: ("**Al-Maqām al-Maḥmūd, and the Night Prayer as Its Means**",
"""The verse commands the night prayer and promises a station in the same breath, and the connection between the two is the verse’s substance. *Wa min al-layli fa-tahajjad bihi nāfilatan laka* — and part of the night, keep vigil with it as an addition for thee. The verb *tahajjad* is from *h-j-d*, which denotes both sleeping and waking at night, and the form used here means to shake off sleep for the sake of prayer — the commentators note that the word contains the effort. *Nāfilah* is an addition, a supererogatory act beyond the obligatory, and al-Qurṭubī records the view that the night prayer was obligatory specifically for the Prophet ﷺ and supererogatory for the community, on the strength of the phrase *laka*, for thee.

The promise is *maqāman maḥmūdā*, a praiseworthy station, and the identification of this station with the intercession on the Day of Resurrection is established in the collections. Al-Bukhārī (4718) records the ḥadīth of the gathering:

> *“The people will fall to their knees on the Day of Resurrection, and every nation will follow its prophet saying: O so-and-so, intercede for us — until the intercession comes to me. That is the day on which God will raise me to the Praiseworthy Station.”* (al-Bukhārī 4718)

Muslim (194) preserves the longer form in which the people go first to Adam, then to Noah, Abraham, Moses, and Jesus, each of whom declines and refers them onward, until they come to the Prophet ﷺ who says: *“I am for it, I am for it.”* The word *maḥmūd* is from the same root as the name Muḥammad, and the commentators note the correspondence: the one named “the Praised” is raised to “the Praiseworthy Station.”

The verse’s pairing of the means and the end is the part with continuing application. The station promised is not obtained by claim but by the vigil, and the Qur’an states the same relation at 73:6–7: *“Indeed, rising by night is more firm in tread and more upright in speech. Indeed, thou hast by day a long occupation.”* The night prayer is described there as the condition of steadiness, and the reasoning is given: the day is full of demands, and the one who has no hour in which he is alone with God has no ground from which to meet them.

The verse therefore supplies both a discipline and its rationale. The discipline is an hour of the night given to recitation; the rationale is that the capacity to stand under opposition — the subject of verses 73 to 77 — is produced in that hour and nowhere else. Al-Ṭabarī preserves the report that the night prayer was obligatory on the early community for a year until 73:20 abrogated its obligation, and that the abrogation left it as the highest of the voluntary acts, which is its standing in the tradition to this day."""),

80: ("**Mudkhal Ṣidq and Mukhraj Ṣidq: The Prayer for Honest Entrances**",
"""The supplication the verse teaches is among the most used in the Islamic devotional tradition, and its two halves cover the whole of a person’s movement through the world: *wa qul rabbi adkhilnī mudkhala ṣidqin wa akhrijnī mukhraja ṣidqin* — my Lord, make me enter an entrance of truth and make me leave an exit of truth. The attachment of *ṣidq* to the entrance and the exit rather than to the person is the grammatical feature that the commentators press: what is requested is not merely that the one entering be truthful but that the entering itself be true — legitimate in its grounds, honorable in its manner, and sound in its end.

Al-Ṭabarī catalogues the interpretations and does not exclude any of them. The first: the entrance into Madinah at the Hijrah and the exit from Makkah, which is the reading connected to the occasion of the verse and is supported by 2:286’s pairing and by the sūrah’s preceding verses about expulsion. The second: the entrance into the grave and the exit from it at the resurrection. The third: the entrance into every affair and the exit from it — a general reading that al-Qurṭubī favors, since it makes the supplication applicable to every day. The fourth: the entrance upon the truth in belief and the exit from the world upon it. The four are not competing but nested, and the general reading contains the others.

The ḥadīth literature supplies the practical use. Al-Tirmidhī (3406) records the Prophet’s ﷺ form of the same request at the point of entering a place:

> *“Whoever enters a place and says: ‘I seek refuge in the perfect words of God from the evil of what He created’ — nothing will harm him until he leaves that place.”* (Muslim 2708)

The pairing of the two supplications indicates the intention: the entrance is a real exposure, and the exit a real deliverance.

The verse’s placement after the command to the night prayer is significant. The vigil produces the steadiness, and the steadiness is exercised in the entrances and exits of the day — the meeting, the office, the household, the conversation, the decision. Al-Qurṭubī draws the ethical content of *ṣidq* in this position: an entrance of truth is one whose grounds one would be willing to state aloud, and an exit of truth is one that leaves nothing behind that one would wish to conceal. The supplication is therefore a request for consistency between the private and the public, which is the same consistency the night prayer trains.

The closing clause — *wa jʿal lī min ladunka sulṭānan naṣīrā* — asks for an assisting authority from God’s own presence. The commentators note the word *ladun*, which denotes proximity, and *sulṭān*, which denotes a proof or an authority that compels assent. The request is not for power over people but for the authority of truth supported by God, which is the only authority that survives the entrances and exits the verse has just described."""),

81: ("**Truth Cast and Falsehood Vanquished: A Physics Rather Than a Battle**",
"""The verse states its claim in two verbs, and the choice of the second is what makes the verse remarkable. *Wa qul jāʾa al-ḥaqqu wa zahaqa al-bāṭil* — say: the truth has come and falsehood has vanished. The verb *zahaqa* does not mean merely to depart; it denotes perishing, being extinguished, ceasing to have substance — al-Zamakhsharī distinguishes it from *dhahaba*, to go, precisely because it carries destruction rather than movement. Falsehood does not retreat before the truth; it is undone by it.

The Qur’an supplies the mechanism at 21:18: *“Nay, We hurl the truth upon falsehood and it shatters its brain (fa-yadmaghuhu), and behold, it perishes.”* The image is not of two combatants but of a solid striking a hollow thing. The reason is ontological rather than rhetorical: truth has being, falsehood does not. Al-Rāzī develops the point — falsehood is parasitic on truth, since every false claim borrows its plausibility from some element of the real, and the exposure of the borrowed element is what destroys it. This is why falsehood requires maintenance and truth does not; a lie must be defended, patched, and remembered, while a fact requires only not being forgotten.

The historical fulfillment was recorded within the Prophet’s ﷺ lifetime. Al-Ṭabarī and Ibn Kathīr note that the verse was revealed in Makkah and that its fulfillment came at the conquest, when the Prophet ﷺ entered the Kaʿbah and struck the idols with a stick while reciting it, the idols falling as he passed them. The report is preserved in al-Bukhārī (4287) in connection with the entry into Makkah. The interval between the statement and its fulfillment — roughly eight years, through exile, defeat at Uḥud, and the siege of the Trench — is the verse’s practical content: the truth’s victory was announced while the truth looked weakest, and the announcement is what sustained the community through the interval.

The second clause generalizes the claim: *inna al-bāṭila kāna zahūqā* — falsehood is by nature vanishing. The intensive form *zahūq* makes perishing a property rather than an event, and 34:49 states the same: *“The truth has come, and falsehood originates nothing and brings nothing back.”* The denial of origination and of return is a complete negation: falsehood cannot begin a thing and cannot restore one.

The verse’s application does not require a battlefield. Every person holds false beliefs that persist because they have not been examined rather than because they have been defended, and the verse describes what happens when the truth arrives: not a debate but a collapse. This is why the Qur’an’s method throughout is not argument alone but exposure — the presentation of the fact in a form the hearer cannot hold alongside his error."""),

82: ("**What Descends as a Healing, and the Loss It Adds**",
"""The verse is the Qur’an’s own statement of its function, and its two clauses describe opposite effects from the same source. *Wa nunazzilu min al-Qurʾāni mā huwa shifāʾun wa raḥmatun li-l-muʾminīn* — and We send down of the Qur’an that which is a healing and a mercy for the believers. The particle *min* has been read in two ways, and al-Ṭabarī holds both: as partitive, indicating that some of what is revealed is healing, and as explicative, indicating that the Qur’an as a whole is healing — the second being the reading favored by al-Qurṭubī, on the ground that the Qur’an describes itself entirely in these terms at 10:57, *“O mankind, there has come to you an admonition from your Lord, and a healing for what is in the breasts.”*

The two senses of *shifāʾ* are both attested in the tradition. The primary sense, and the one the commentators give first, is the healing of the diseases of the heart — doubt, hypocrisy, ignorance, and disordered desire. Al-Rāzī explains the mechanism: the diseases of the soul are false beliefs and disordered loves, and the Qur’an addresses the first by argument and the second by re-ordering the objects of hope and fear. The secondary sense is physical healing, and the jurists built on it the legislation of *ruqyah*, recitation over the sick. Al-Bukhārī (5736) records the case of the companion who recited al-Fātiḥah over a tribal chief stung by a scorpion and was given a flock of sheep for it, and the Prophet ﷺ approved the practice and asked for his share. 16:69 uses the same word of honey, *“in which there is healing for mankind,”* which establishes that *shifāʾ* is used in the revelation of bodily cure as well as of spiritual.

The second clause is the harder and more instructive: *wa lā yazīdu al-ẓālimīna illā khasārā* — and it increases the wrongdoers only in loss. The same text produces healing in one and loss in another, and the difference is not in the text. Al-Qurṭubī explains the mechanism: the revelation obligates, and the one who is obligated and does not comply has added to his account; the one who complies has been healed. The Qur’an states the same phenomenon at 9:124–125, where a sūrah revealed increases the believers in faith and increases the one in whose heart is a disease in filth. The parallel with verse 60 of this sūrah — the tree of Zaqqūm made a trial — is exact: the same datum, two opposite effects, and the effect determined by the receiver.

The verse therefore supplies a warning to the reader about his own reading. Exposure to the revelation is not neutral; it either heals or indicts, and the variable is not the amount heard but the response made. 41:44 states the point with a comparison: had the Qur’an been made a foreign tongue, they would have said, *“Why are its verses not explained in detail? What — a foreign tongue and an Arab?”* The objection was never about comprehension."""),

83: ("**Despair and Elation: The Two Modes of an Unstable Soul**",
"""The verse describes a psychological pattern rather than a moral failing, and its precision is what makes it useful. *Wa idhā anʿamnā ʿalā al-insān aʿraḍa wa naʾā bi-jānibih* — and when We bestow favor upon man, he turns away and draws aside. The verb *aʿraḍa* is the same one used at verse 67 of the man who turns away after being rescued from the sea, and *naʾā bi-jānibih* — he draws aside with his side — describes the physical gesture of withdrawal, the turning of the shoulder that expresses disengagement. The second mode follows: *wa idhā massahu al-sharru kāna yaʾūsā*, and when evil touches him he is despairing.

The two modes are the only two the verse describes, and their pairing is the diagnosis. In favor, the human being is disengaged; in adversity, he is without hope. Neither state is the correct one: the first is ingratitude and the second is despair, and both are failures of the same faculty, which is the capacity to hold a stable relation to God across changing circumstances. 41:51 supplies the fuller version and adds a third detail of clinical accuracy: *“And when We bestow favor upon man, he turns away and draws aside; but when evil touches him, he is full of extensive supplication (fa-dhū duʿāʾin ʿarīḍ).”* The word *ʿarīḍ* — broad, extensive — describes the length and elaborateness of the prayer made in distress, which contrasts sharply with the silence of the prosperous hour. 11:9–10 gives the two character-words that name the modes: in favor after adversity, *la-fariḥun fakhūr*, exultant and boastful; in adversity after favor, *la-yaʾūsanna kafūr*, despairing and ungrateful.

Al-Rāzī draws the theological inference: the pattern shows that the untrained soul has no fixed relation to God but a reactive one, determined entirely by circumstance. The person in this condition is not irreligious so much as unstable, and the instability is invisible to him because each mode feels appropriate at the time — the prosperity feels earned and the adversity feels total. The Qur’an’s remedy is the discipline of remembrance, and 13:28 states it with the diagnosis attached: *“Those who believe, and whose hearts find rest in the remembrance of God — truly in the remembrance of God do hearts find rest.”*

The verse’s practical use is as a self-test with two questions, and both are answerable in a moment. In the last week of ease, did you pray? In the last week of difficulty, did you hope? The one who answers no to the first and no to the second has identified precisely the condition the verse describes, and the identification is the beginning of its correction — which is why the verse is addressed to the reader in the second person rather than describing an abstract type."""),

84: ("**Shākilah: Acting From Disposition, and the Knowledge That Follows**",
"""The command *qul* introduces a general statement about human action, and the word at its center has been read three ways. *Kullun yaʿmalu ʿalā shākilatih* — everyone acts according to his *shākilah*. Al-Ṭabarī records the glosses: *ʿalā ṭarīqatih wa jānibih*, upon his way and his side; *ʿalā dīnih*, upon his religion; and *ʿalā niyyatih*, upon his intention. The root *sh-k-l* denotes form, manner, and resemblance, and the word carries the sense of the shape a thing takes — hence the commentators’ consensus that it denotes the disposition from which a person’s acts proceed, whether that disposition is a creed, a character, or a settled intention.

The verse therefore states a claim about predictability. A person’s actions are not a series of unrelated events but the expression of a structure, and the structure can be known. This is why the following clause draws the conclusion it does: *fa-rabbukum aʿlamu bi-man huwa ahdā sabīlā* — your Lord knows best who is best guided in the way. The divine knowledge is stated in the comparative — *aʿlam*, *ahdā* — which is the same comparative construction used at verse 57 of the beings seeking *ayyuhum aqrab*, which of them is nearer. The pairing is deliberate: the human being judges by the act, God judges by the disposition that produced it, and the one who knows the disposition knows the acts before they occur.

Al-Rāzī develops the ethical consequence, and it runs in two directions. The first is about others: since acts flow from dispositions, an act performed by a person of settled virtue is more creditable than the same act performed by one who stumbled into it, and the Qur’an weights the two differently. The second is about the self: since your acts reveal your disposition, you can read your own character from what you habitually do rather than from what you intend. The Prophetic formulation of the same principle is at al-Bukhārī (52) and Muslim (1907):

> *“Actions are by intentions, and every person has only what he intended. So whoever’s migration was to God and His Messenger, his migration was to God and His Messenger; and whoever’s migration was for a worldly thing or a woman he would marry, his migration was to that for which he migrated.”* (al-Bukhārī 1)

The verse’s placement after the discussion of the Qur’an as a healing is what gives it its function. The revelation is described as producing opposite effects in different receivers, and the verse explains why: each receiver acts from his *shākilah*, so the same text meets a different structure in each. The practical conclusion is the one the sūrah has been building toward — that the work is on the disposition rather than on the individual act, since the disposition is what will produce the acts long after the decision has been forgotten."""),
}
p='expanded/017.md'
s=open(p,encoding='utf-8').read()
parts=re.split(r'(?m)^(## Sūrah al-Isrāʾ 17:\d+)$', s)
d={int(parts[i].split(':')[1]):[parts[i],parts[i+1]] for i in range(1,len(parts),2)}
for n,(h,t) in ADD.items():
    body=d[n][1]
    hs=[m.start() for m in re.finditer(r'(?m)^\*\*(?!Expanded Commentary).+?\*\*$', body)]
    assert hs, n
    ins=hs[-1]
    d[n][1]=body[:ins]+'**'+h+'**\n\n'+t.strip()+'\n\n'+body[ins:]
out=[parts[0]]
for i in range(1,len(parts),2):
    n=int(parts[i].split(':')[1]); out.append(d[n][0]); out.append(d[n][1])
open(p,'w',encoding='utf-8').write(''.join(out))
print('added',len(ADD),'| words now',len(''.join(out).split()))
