import re
ADD = {
15: ("**Before the Messenger Comes: The People of the Interval**",
"""The verse’s final clause — *wa mā kunnā muʿadhibīna ḥattā nabʿatha rasūlā* — became the scriptural ground for one of the most consequential discussions in Islamic theology: the status of those who lived where no messenger reached them, the *ahl al-fatra*. The question was not academic. It arose concretely whenever Muslim jurists encountered peoples beyond the reach of the message, and al-Ghazālī addressed it at length in the *Fayṣal al-tafriqah bayna al-islām wa-l-zandaqah*, concluding that the overwhelming majority of the humans of his own century — including those in distant lands who had received only distorted and caricatured reports of Islam — fell outside the category of the condemned, because what reached them was not the message but a distortion of it that made its truth impossible to recognize. Ibn Taymiyyah argued the same conclusion from the same verse.

The principle the verse establishes is that liability is not inherited and not retroactive: it arises at the moment of notification and not before. This distinguishes the Qur’anic position sharply from any system in which human beings are condemned for an ancestral fault. Compare 2:134, *“Those are a people who have passed; theirs is what they earned, and yours is what you earn, and you will not be asked concerning what they used to do”* — a verse that forecloses the transfer of guilt in both directions. The Prophetic tradition supplies the anthropological premise: al-Bukhārī (1385) records, *“Every child is born upon the fiṭrah; it is his parents who make him a Jew, a Christian, or a Magian.”* The human being arrives oriented toward recognition and is deflected by circumstance; the messenger’s arrival is what converts that orientation into a decision for which he is answerable. Read together, the three clauses of this verse form the Qur’an’s complete theory of justice — responsibility is individual, burden is non-transferable, and liability requires notification — and each clause closes an avenue of complaint that the others leave open."""),

16: ("**Amarnā Read Against 7:28: How the Tradition Constrains a Word**",
"""The interpretive history of *amarnā* is a case study in how the exegetical tradition disciplines a difficult word by subordinating it to a clear one. Read literally, the verse says that when God intends to destroy a town He commands its luxurious class — and they then commit iniquity, which places the command and the transgression in an unsettling order. Al-Zamakhsharī confronts the difficulty directly and resolves it by insisting on a metaphorical reading: since the Qur’an states categorically at 7:28, *“Say: God does not command indecency (al-faḥshāʾ); do you attribute to God what you do not know?”*, the command here cannot be a command to evil, and what is meant is that by granting such people the means, the power, and the impunity to transgress, it is *as if* He had commanded it. Al-Rāzī, writing from the other side of the same debate, accepts the literal command as a command to *obedience* which the *mutrafūn* refuse, and reconciles the foreknowledge by distinguishing eternal knowledge from temporal occurrence.

What the episode reveals is a working rule of classical exegesis: an ambiguous verse is read in the light of an unambiguous one, and 7:28 functions as such a *muḥkam*. The third reading — the variant vocalization *ammarnā*, “We made them rulers” — is preserved by al-Ṭabarī and al-Rāzī precisely because it harmonizes all three concerns at once: God places the luxurious in authority, they transgress, and the sentence falls. The sociological observation is identical under every reading, and it locates the origin of communal ruin where ordinary analysis does not look. When an institution fails, the visible symptoms appear at the bottom — disorder, poverty, crime — while the cause sits at the top, among those with the most to lose from correction and the most power to prevent it. The Qur’an’s *mutrafūn* are not merely the rich; they are the beneficiaries of the existing order, which is why 34:34 records their answer to every warner: *“We disbelieve in that with which you were sent.”*"""),

17: ("**The Ruins on the Caravan Road: Evidence Rather Than Story**",
"""The generations invoked in this verse were not abstractions to the first audience; they were landmarks. The Quraysh caravan route to Syria passed within sight of the Nabataean rock-cut tombs of al-Ḥijr, the settlement of Thamūd, and the Qur’an addresses them as sightseers rather than as students of history: 15:80, *“And the Companions of al-Ḥijr denied the messengers”*; and 27:69, *“Say: Travel in the land and see what was the end of the criminals”*; and 22:46, *“Have they not traveled in the land, so that they might have hearts by which to understand, and ears by which to hear? Truly it is not the eyes that go blind, but the hearts within the breasts.”* The ruined cities function in Qur’anic rhetoric exactly as precedent functions in a legal argument: they establish that the rule being announced has been enforced before, and therefore can be enforced again.

The word *qarn* — generation, or the people of an era — is used deliberately in the indefinite plural *kam min al-qurūn*, and al-Zamakhsharī notes that the unbounded quantity is more effective than a number would be. A specified figure invites the hearer to catalogue the cases and dismiss them as a closed set; an unnumbered multiplicity places him inside a pattern he cannot totalize. The verse’s closing pair, *khabīran baṣīrā*, supplies the reassurance that the pattern requires: the One who destroyed those generations is *khabīr* — acquainted by direct testing, not merely informed — and *baṣīr*, seeing with insight rather than glancing. It is the same pairing that closed verse 12 of the sūrah and will close verse 30 and verse 96, and its recurrence marks the points at which the sūrah addresses the believer’s sense that wrongdoing goes unrecorded. The destroyed generations are the answer to that sense: the file was kept, the accounting occurred, and nothing was missed."""),

18: ("**Al-ʿĀjilah Is Not Evil — It Is Fast**",
"""The Qur’an’s name for this world is not a moral verdict but a description of speed, and the distinction is theologically important. *Al-ʿājilah* is the active participle of *ʿ-j-l*, haste — “the hastening one” — and it is paired throughout the revelation with *al-ākhirah*, the final. 75:20–21 states the diagnosis in two lines: *“Nay, but you love the hastening, and neglect the Hereafter.”* 76:27 adds the consequence: *“Truly these love the hastening and leave behind a heavy Day.”* The world is not called corrupt or vile in this vocabulary; it is called *quick*, and quickness is precisely what makes it attractive and what makes it deceptive. Al-Rāzī’s reading of the verse’s threefold qualification is what dismantles the inference most people draw from worldly success: God hastens for the seeker *“whatsoever We will”* — not what the seeker asked for — *“for whomsoever We desire”* — not for every seeker. The transaction is therefore not a wage.

This is why the Qur’an repeatedly refuses to read prosperity as endorsement. 89:15–16: *“As for man, when his Lord tries him and honors him and favors him, he says: 'My Lord has honored me.' But when He tries him and straitens his provision, he says: 'My Lord has humiliated me.' Nay!”* — the “nay” rejecting both readings at once. And 23:55–56: *“Do they think that what We provide them of wealth and sons — We hasten unto them good things? Nay, but they do not perceive.”* The ḥadīth tradition states the believer’s relation to this economy in a single image, recorded by Muslim (2956): *“The world is a prison for the believer and a garden for the disbeliever”* — not because the believer suffers more, but because his horizon is elsewhere, so that what satisfies one confines the other. The severity of verse 18 lies in the closure of the transaction rather than in the punishment: you asked for the immediate, you received the immediate, and the door through which anything further would have come has been locked from the inside."""),

19: ("**Saʿyahā: The Effort the Goal Deserves**",
"""The grammar of this verse carries its doctrine. *Wa saʿā lahā saʿyahā* uses the cognate accusative (*al-mafʿūl al-muṭlaq*), in which the verb’s own verbal noun is repeated in the accusative to intensify it: he strove for it *the striving it deserves*. The construction removes any reading of the verse as satisfied by token effort. Al-Rāzī’s enumeration of the three conditions — intention, earnest striving, and belief — is drawn from the sequence itself, and he notes the feature that makes the verse unusually generous: it requires neither success nor completion. The one who intends good, strives genuinely, and is prevented by death or incapacity has fulfilled every condition the verse states.

The Prophetic tradition confirms this reading with a ruling of extraordinary breadth. Muslim (131) records from Ibn ʿAbbās, in the account of the Prophet ﷺ transmitting from his Lord:

> *“Truly God wrote down the good deeds and the bad deeds, then He made it clear: whoever intends a good deed and does not do it, God writes it with Himself as a full good deed; and if he intends it and does it, God writes it with Himself as ten good deeds, up to seven hundred times, and many times over. And whoever intends a bad deed and does not do it, God writes it with Himself as a full good deed; and if he intends it and does it, God writes it as one bad deed.”* (al-Bukhārī 6491; Muslim 131)

The asymmetry in that report — the abandoned sin recorded as a good deed, the unexecuted good recorded as a full one — is the practical expression of this verse’s doctrine that the accounting is of orientation and effort rather than outcome. Al-Zamakhsharī cites the ḥadīth of intentions, *“Deeds are only according to intentions”* (al-Bukhārī 1; Muslim 1907), at exactly this verse, and the two ḥadīth together explain the verse’s final word: *mashkūrā* — thanked. That the Infinite describes Himself as thanking the finite is among the most striking features of Qur’anic theology, stated directly at 4:147, *“What would God do with your punishment if you are grateful and believe? And God is Ever Thankful (shākir), Knowing.”*"""),

20: ("**Why Indiscriminate Provision Makes Faith Possible**",
"""The verse’s refusal to distribute the *ʿaṭāʾ* according to spiritual merit is not a concession to the way things happen to be; al-Rāzī argues that it is a condition of the possibility of genuine faith. If provision tracked righteousness, belief would be compelled, because believing would visibly pay and disbelieving would visibly cost. The Qur’an forecloses compelled belief as worthless in two places: 2:256, *“There is no compulsion in religion; the right direction is distinct from error”*; and 10:99, *“If thy Lord had willed, all who are on earth would have believed together. Wouldst thou then compel mankind until they become believers?”* For faith to be a free act, its worldly consequences must be indeterminate — and the indiscriminate gift is what makes them so. The verse is therefore not an apology for injustice but a statement about the epistemic conditions under which belief can be anything other than calculation.

The tradition supplies the practical companion to this doctrine in the concept of *rizq* as decreed. Ibn Mājah (2144) records, with a chain al-Albānī graded ṣaḥīḥ:

> *“There is no soul that dies until it has completed its provision. So fear God, and be measured in your seeking.”* (Ibn Mājah 2144)

The ḥadīth does not license passivity — the same report commands measured seeking — but it removes provision from the category of things one can secure by anxiety or by grasping, which is the psychological burden the verse lifts. Its two practical effects are worth naming. The first is the release from interpreting other people’s success as a verdict on their character, a habit that produces envy in one direction and self-righteousness in the other. The second is the release from interpreting one’s own lack as a verdict on one’s standing. Provision, on this account, is material for stewardship and for testing, not a report card — and the believer’s task is not to audit the distribution but to use what he has been given."""),

21: ("**Ghibṭah and Ḥasad: The Two Ways of Looking Upward**",
"""The command *unẓur* — see, observe — makes inequality an object of attention rather than a subject of complaint, and the tradition draws a distinction that determines what the looking produces. Al-Bukhārī (73) and Muslim (815) record:

> *“There is no envy (ḥasad) except in two: a man whom God has given wealth and enabled to spend it rightly, and a man whom God has given wisdom and he judges by it and teaches it.”* (al-Bukhārī 73)

The word translated here as “envy” is *ḥasad*, but the commentators explain that what the ḥadīth commends is *ghibṭah* — the wish to possess a like good without wishing the other to lose his — and that *ḥasad* proper, which wishes the other’s loss, is what the same tradition condemns. The distinction is the difference between the two possible responses to the gradation this verse commands us to observe: one produces emulation, the other produces resentment, and the outward object of attention is identical in both.

The two Qur’anic explanations of why the gradation exists are functional rather than punitive, and together they answer the complaint the verse anticipates. The first, at 43:32, is mutual dependence: *“We have apportioned among them their livelihood in the life of this world, and raised some of them above others in rank, that some of them may take others into service. And the mercy of thy Lord is better than what they amass.”* A society of identical means would have no division of labor and no occasion for the exchange of services. The second, at 6:165, is testing: *“And He raised some of you above others in degrees, that He might try you in what He gave you.”* The abundant are tested by abundance and the constrained by want, with different question papers and the same examiner. The verse then outbids the whole arrangement: the ranking of the Hereafter is *akbar darajātin wa akbaru tafḍīlā* — greater in rank and greater in favor — and the criteria are different. Al-Bukhārī (3256) describes the result in an image meant to motivate rather than to wound: *“The people of the Garden will look up at those in the elevated chambers above them as you look at a brilliant star on the horizon.”*"""),

22: ("**Shirk as Enthronement: The Qur’an’s Own Diagnosis**",
"""The verb *tajʿal* — to appoint, to posit — determines the meaning of the prohibition, and it relocates shirk from metaphysics to practice. The Qur’an does not deny that other gods exist in order to forbid worshipping them; it denies the category and then forbids the human act of establishing something within it. This is why the Qur’an can describe shirk as widespread among people who would deny holding it. 12:106 is the verse the classical theologians cite most often on this point: *“And most of them believe not in God except while associating partners (wa mā yuʾminu aktharuhum bi-Allāhi illā wa hum mushrikūn).”* Ibn ʿAbbās’s gloss, preserved by al-Ṭabarī, is that this refers to those who say, when asked who created the heavens and the earth, “God” — and then direct their supplication elsewhere. The theological belief is intact; the practical enthronement has occurred.

The tradition names the subtler forms explicitly. Aḥmad (27742) records the Prophet ﷺ addressing his Companions:

> *“Shall I not tell you of what is more to be feared for you than the False Christ (al-Masīḥ al-Dajjāl)? The lesser shirk (al-shirk al-aṣghar): that a man stands and prays, and beautifies his prayer because he sees a man looking at him.”* (Aḥmad 27742; Ibn Mājah 4204, graded ḥasan)

The category is defined by the mechanism rather than by the object: whatever a person appoints to the position God occupies — as the object of ultimate reliance, ultimate fear, or ultimate regard — has been made *ilāh*, whatever he calls it. This is why the prohibition opens a moral code rather than appearing within it. Each command that follows fails at a specific point: kindness to parents fails when the parent’s approval becomes ultimate; honest measure fails when wealth does; chastity fails when desire does; truthfulness fails when reputation does. In every case the commandment breaks precisely where something created has been enthroned, and the verse at the end of the code will repeat this one to close the frame."""),

23: ("**The Limits of Obedience, and the Rank of the Duty**",
"""The verse’s command is not unconditional, and the Qur’an supplies the boundary in a passage the jurists treat as its necessary companion. 31:15: *“And if they strive with thee to make thee associate with Me that of which thou hast no knowledge, then obey them not; but keep company with them in this world kindly (maʿrūfan), and follow the way of one who turns to Me.”* The structure of the ruling is precise: obedience in sin is refused, and kindness in this world is commanded — the two clauses sit in the same sentence, so that the refusal does not license coldness. The Prophetic formulation is categorical, recorded by Aḥmad (1098) and al-Nasāʾī: *“There is no obedience to a creature in disobedience to the Creator.”* Al-Qurṭubī states the resulting rule: the parent’s right is to companionship, provision, and honorable speech; it does not extend to the child’s conscience.

The rank of the duty is fixed by its placement in the hierarchy of deeds. Al-Bukhārī (5970) records the exchange in full:

> *“I asked the Prophet ﷺ: 'Which deed is most beloved to God?' He said: 'The prayer at its time.' I said: 'Then which?' He said: 'Then goodness (birr) to parents.' I said: 'Then which?' He said: 'Then jihād in the path of God.'”* (al-Bukhārī 5970)

That *birr al-wālidayn* is placed above jihād — the highest physical sacrifice in the tradition — is the measure of its weight, and the reason is structural rather than sentimental. Parental love is largely instinctive and requires no legislation; filial gratitude is not, because the natural current of life runs the other way. The Qur’an legislates where nature is weakest, which is why the command is located at the precise point of maximum difficulty: *ʿindaka*, in your care, in your house, when the parent has become dependent and can give nothing back. Al-Rāzī’s argument *a fortiori* from the prohibition of *uff* closes the loophole: if a sigh is a violation, then raising the voice, striking, and abandonment are violations by a greater measure, and the verse forbids the least so that the greater is understood to be included."""),

24: ("**Janāḥ al-Dhull: An Image Drawn From the Bird**",
"""The metaphor is one of the Qur’an’s most carefully constructed, and its rhetorical force depends on the reversal it performs. Al-Zamakhsharī classifies it as an *istiʿārah* — a borrowed image — drawn from the bird that lowers its wing over its young to shelter them, and lowers its wing to another bird as a gesture of submission and non-aggression. The verse transfers the gesture to the child before the parent: the one who was sheltered under a wing now lowers his own. The word *dhull* is chosen with equal care, and the commentators distinguish it sharply from *dhill* in the sense of degradation. Willing lowness before one worthy of honor is a virtue; humiliation imposed by another is an injury. The Qur’an uses the same word of the believers toward one another at 5:54, *“humble (adhillah) toward the believers, mighty toward the disbelievers”* — the same posture, in that verse, toward the community.

The practical target of the command is specific: the adult child’s superiority in education, income, and worldly standing, which is precisely the temptation that old age creates. Al-Qurṭubī notes the extremity of the required posture — total non-assertion — and the qualifier *min al-raḥmah* supplies the interior state that makes it bearable: mercy arising from *memory*, the recollection of the parent’s tenderness toward one’s own helplessness. The duty outlives the parent, which is unusual in Islamic law. Muslim (1631) records:

> *“When a man dies, his deeds cease except for three: a continuing charity, a knowledge from which benefit is gained, or a righteous child who prays for him.”* (Muslim 1631)

Abū Dāwūd (5142) specifies what remains after death: prayer for them, seeking forgiveness for them, fulfilling their pledges, honoring their friends, and maintaining the ties of kinship that exist only through them. The child’s prayer thus continues to benefit a person who can no longer benefit from anything else, and the obligation is one of the few in the law that the death of the obligee does not extinguish."""),

25: ("**Awwāb: The One Whose Characteristic Is Returning**",
"""The plural *al-awwābūn* is the intensive form of *āʾib*, one who returns, and the form indicates frequency: not the person who repents once but the person whose settled characteristic is turning back. Al-Qurṭubī’s definition, transmitted from al-Ḥasan al-Baṣrī, is the shortest available: the *awwāb* is the one who does not persist. The definition is not about never falling but about not remaining down, and it makes the verse address the actual condition of nearly every moral life rather than an idealized one. The verse is placed where it is for that reason — immediately after the two most demanding verses on parents in the Qur’an — and its function is to keep an exacting standard livable by disclosing that repentance is part of the standard rather than a concession outside it.

The theological precision of the verse lies in the relationship between two clauses. God knows what is in the souls — including the flash of irritation, the unspoken complaint, the resentment that surfaces and is pushed down — and yet the promise is attached to righteousness, not to the absence of interior noise. The distinction is supplied by al-Bukhārī (5269) and Muslim (127):

> *“God has overlooked for my community what their souls whisper to them, so long as they do not act upon it or speak it.”* (al-Bukhārī 5269)

The knowledge in this verse is therefore not a threat of punishment for every passing thought; it is the assurance that God sees the effort, the regret, and the intention, none of which appear in the outward act. The corresponding discipline is the one the tradition calls *istiqāmah*, and its classical formulation is the ḥadīth of Muslim (38): *“Say: I believe in God — then be upright (fa-staqim).”* Uprightness in that formulation is not the absence of deviation but its continuous correction, which is the same content as *awwāb* stated as a command. The person who internalizes this does not lower the standard; he stops treating each failure as evidence that the standard was never meant for him."""),

26: ("**The Hierarchy of Claims: Why the Kinsman Comes First**",
"""The order of the three recipients in this verse is not incidental, and 2:215 states the principle explicitly: *“They ask thee what they should spend. Say: whatever you spend of good is for parents and kinsmen, orphans, the indigent, and the wayfarer.”* Charity in the Qur’an begins with those nearest and moves outward, and the term used for the kinsman’s portion is *ḥaqq* — a right — rather than *ṣadaqah*, which transforms the transaction from benevolence into justice and removes the giver’s discretion. A favor may be withheld; a right may not. The jurisprudential concept is *ṣilat al-raḥim*, and its name supplies its theology: the *raḥim* is the womb, so the tie is named after the organ from which both parties emerged, and severing it is not a social disagreement but a denial of a fact.

Muslim (2555) records the metaphysical weight the tradition attaches to it:

> *“God created the creation, and when He finished, the *raḥim* stood and said: 'This is the standing of one who seeks refuge in Thee from severance.' He said: 'Yes — are you not content that I maintain whoever maintains you, and sever whoever severs you?' It said: 'Indeed.' He said: 'That is yours.'”* (al-Bukhārī 4830; Muslim 2555)

The wayfarer’s entitlement is the other striking feature. *Ibn al-sabīl* — literally “son of the road” — is the traveler who has run out of means even if he is wealthy at home, and 9:60 lists him among the eight categories entitled to zakāt. Al-Ṭabarī explains the duty as food and lodging, and in a world without banks, embassies, or hotels this verse established hospitality as a legal claim rather than a courtesy — the ground on which the Muslim world later built the *khān*, the *ribāṭ*, and the charitable endowments for travelers. The prohibition that closes the verse regulates the manner: al-Qurṭubī identifies the three forms of *tabdhīr* as giving beyond one’s means, giving for reputation, and giving to those without a claim while those with a claim go unfed — the third being the most common and the least noticed."""),

27: ("**Tabdhīr, Isrāf, Bukhl: Three Vices With Different Names**",
"""The classical exegetes distinguish the economic vices with a precision that the English vocabulary blurs, and the distinction is preserved in a report from Ibn Masʿūd and Ibn ʿAbbās cited by al-Qurṭubī: *isrāf* is spending in what is lawful beyond the measure of need, while *tabdhīr* is spending in what is unlawful at all. The first is excess within the permitted; the second is misdirection of the resource altogether. *Bukhl* — miserliness — is the third term, and 25:67 defines the correct position between the first and the third: *“And those who, when they spend, are neither wasteful (musrifūn) nor miserly (muqtirūn), but stand between that, uprightly (qawāmā).”* The word *qawām* is from the same root as *aqwam* in verse 9, so that the economic virtue is presented as an instance of the uprightness the whole sūrah is about.

The Prophetic formulation of the rule is practical rather than ascetic. Al-Bukhārī (5783) records:

> *“Eat, and drink, and give charity, and wear clothing — without extravagance (saraf) or pride (makhīlah).”* (al-Bukhārī 5783; al-Nasāʾī 2559)

The verse’s pairing of waste with satanic brotherhood is the strongest language the sūrah uses about money, and al-Qurṭubī supplies the chain of reasoning: waste is the misuse of a trust; every trust misused is an act of ingratitude; ingratitude is Satan’s defining characteristic, since his original sin was *kufr al-niʿmah* — the refusal to acknowledge a favor received; therefore the waster is Satan’s brother in the quality that defines him. There is a second, economic link: the resources squandered are the resources unavailable to the *miskīn* and the *ibn al-sabīl* named in the preceding verse, so the person who discards what another needs has taken it from him. The contemporary form of the vice is more visible than in any previous century, since consumer economies are structurally organized around *tabdhīr* — overpackaging, planned obsolescence, the disposal of edible food — and the verse’s criterion is precise enough to diagnose it: waste is not the amount spent but its proportion to need and to the claims of others."""),

28: ("**Qawl Maysūr: What a Refusal Owes the Refused**",
"""The verse legislates a situation every generous person eventually faces, and it identifies the specific injury that a refusal can inflict even when the refusal is justified. Al-Qurṭubī records that when the Prophet ﷺ was asked for something he did not have, he would remain silent rather than refuse — waiting for provision rather than saying no — and that the verse instructed him to replace silence with speech. The correction is instructive: silence, however well-intentioned, leaves the petitioner suspended in uncertainty, and uncertainty is itself a harm. The person who has asked needs to know where he stands, and the verse treats that knowledge as something owed to him.

The word chosen for the required speech is *maysūrā*, from *y-s-r*, ease — the same root as the Prophetic maxim *“the religion is easy (yusr)”* and as 54:17, *“And We have made the Qur’an easy to remember.”* An easy word is one that does not burden its hearer: it does not lecture, moralize, or imply that the asking was an imposition. Al-Qurṭubī preserves a second reading in which the command is to speak *for* them easy words — to supplicate on their behalf — and the two readings together describe the complete duty: explain gently, and pray for the one you could not help. The reported alternative occasion sharpens the point further: al-Qurṭubī records that the verse may have been revealed after the Prophet ﷺ declined a request from people he knew would use the funds for corruption, so that the refusal was itself a seeking of mercy. The command applies equally to that case, which means the justified refusal — the one grounded in wisdom rather than in lack — carries the same obligation of gentleness as the refusal forced by poverty.

The verse’s placement between the prohibition of waste and the prohibition of both miserliness and excess is what gives it its place in the code. A person told not to squander will sometimes have to say no, and the Qur’an anticipates the psychological drift: the one who learns to refuse may learn to refuse coldly. Generosity is measured not only by what leaves the hand but by what enters the other person’s heart, and the verse legislates the second as carefully as verses 26–27 legislate the first."""),
}
p='expanded/017.md'
s=open(p,encoding='utf-8').read()
parts=re.split(r'(?m)^(## Sūrah al-Isrāʾ 17:\d+)$', s)
d={int(parts[i].split(':')[1]):[parts[i],parts[i+1]] for i in range(1,len(parts),2)}
for n,(h,t) in ADD.items():
    body=d[n][1]
    hs=[m.start() for m in re.finditer(r'(?m)^\*\*(?!Expanded Commentary).+?\*\*$', body)]
    assert hs, n
    ins=hs[-1]
    d[n][1]=body[:ins]+'**'+h+'**\n\n'+t.strip()+'\n\n'+body[ins:]
out=[parts[0]]
for i in range(1,len(parts),2):
    n=int(parts[i].split(':')[1]); out.append(d[n][0]); out.append(d[n][1])
open(p,'w',encoding='utf-8').write(''.join(out))
import statistics
print('added',len(ADD),'| words now',len(''.join(out).split()))
