import re
ADD = {
29: ("**Two Hands, Two Failures, and the Jurisprudence of the Third**",
"""The verse draws its two pictures from the body, and the legal tradition built a substantial body of ruling on the space between them. The hand bound to the neck is not merely unwilling but *unable* — the miser’s wealth does nothing, for him or for anyone else, which is why 47:38 describes miserliness as self-harm rather than self-protection: *“And whosoever is miserly is only miserly toward himself. God is the Rich, and you are the poor.”* The hand extended to its full span is equally disordered, because once fully open it cannot be closed to protect what remains; and the one who has given away his household’s means has not performed charity but created a second claimant where there was one. The Islamic ideal is therefore neither maximum giving nor minimum giving but *qawām* — a measured standing — stated at 25:67 and named with a word from the same root as *aqwam* in verse 9 of this sūrah.

The jurisprudence is explicit and traces directly to this verse. When Saʿd ibn Abī Waqqāṣ, ill and expecting to die, proposed to bequeath his wealth, the exchange recorded by al-Bukhārī (1295) and Muslim (1628) established the limit:

> *“'Two-thirds?' 'Too much.' 'Half?' 'Too much.' 'A third?' 'A third — and a third is much. Truly, leaving thy heirs wealthy is better than leaving them poor, begging from people.'”* (al-Bukhārī 1295)

The ruling generalizes: voluntary charity may not be given at the expense of dependents, and the claims of the wife, the children, and the parents take precedence over supererogatory generosity. The psychological insight beneath the two prohibitions is that both extremes arise from the same defect — an inability to relate to wealth as a measured trust. The miser over-values it and the spendthrift under-values it, and neither has achieved the relationship the verse presupposes, in which wealth is a resource with a purpose, distributed according to a hierarchy of claims that must be re-judged at every request."""),

30: ("**The Verse as a Pun on the Miser’s Hand**",
"""Read against the verse immediately before it, this one functions as a deliberate contrast, and the wordplay is close enough that the commentators treat it as intended. Verse 29 forbids the human hand from being *maghlūlah* — shackled to the neck. Verse 30 declares that God’s action is *yabsuṭu*, outspreading, from the same root as the divine Name *al-Bāsiṭ*, the Expander. And 5:64 states the corresponding denial in terms the Qur’an treats as blasphemy: *“The Jews say, 'God’s Hand is shackled.' Shackled are their hands, and cursed are they for what they say. Nay, but His two Hands are outspread (mabsūṭatān); He spends as He wills.”* The miser is thus measured against a generosity whose opposite is precisely what he has become, and the condemnation is theological before it is moral.

The pairing of *yabsuṭu* with *yaqdir* — He expands and He straitens — appears as a fixed formula at 13:26, 28:82, 29:62, 30:37, 34:36 and 39, 39:52, and 42:12, and al-Rāzī draws from it the two consequences that dismantle both extremes of verse 29. If God expands, hoarding is futile, because hoarding does not add to what has been apportioned. If God straitens, spending beyond one’s means is equally futile, because expenditure does not force provision open. Both vices are therefore not only wrong but pointless, which is a stronger argument than prohibition alone. The closing pair, *khabīran baṣīrā*, supplies the pastoral ground: the distribution proceeds from One who sees each servant’s condition, so the person whose provision is straitened should not read it as abandonment, and the person whose provision is expanded should not read it as endorsement. Both readings of one’s own circumstances are forbidden by the same attribute, and the Prophet ﷺ stated the underlying principle in the report of Muslim (2643), in which the angel is commanded to write four things before birth: provision, life span, deeds, and whether the person is wretched or happy."""),

31: ("**Two Verses, Two Orderings: The Precision of the Provision**",
"""The commentators noted a difference between this verse and its parallel at 6:151 that is small enough to miss and exact enough to be deliberate. There the wording is *min imlāq* — “out of poverty,” i.e., from poverty already present — and the assurance runs *“We provide for you and for them,”* placing the parents first. Here the wording is *khashyata imlāq* — “for fear of poverty,” i.e., poverty anticipated but not yet present — and the assurance runs *“We provide for them and for you,”* placing the children first. Al-Rāzī states the inference: when poverty is already present, the parents’ need is the pressing concern, so they are named first; when poverty is merely feared, the child’s provision is the concern, so the child is named first. The variation is a small masterpiece of precision, and it demonstrates that the Qur’an’s word order carries meaning at the level of a single sequence.

The theological correction beneath the prohibition is what makes it more than a legal ruling. The fear of poverty rests on a false belief about who provides: if the parent believes the child will consume the household’s sustenance, killing the child appears rational; if he understands that the child arrives with provision apportioned by God, the fear loses its premise. This is why the sin is joined to shirk in the report of al-Bukhārī (6871) and Muslim (86), in which the Prophet ﷺ ranks the gravest sins and places the slaying of one’s child for fear that he will eat with him second only to making a rival for God. To believe that provision comes from anywhere but God is already to have set up a rival. The classification of the act as *khiṭʾ kabīr* — a great sin — places it among the *kabāʾir* in the technical vocabulary of the law, the same category the Qur’an assigns to intoxicants and gambling at 2:219, and the jurists extended its principle to every situation in which a human being is treated as an economic liability: the aged parent whose care is costly, the disabled child whose upbringing is expensive, the dependent relative who consumes resources."""),

32: ("**Lā Taqrabū: The Legal Principle of Blocking the Means**",
"""The verb is not *lā tafʿalū* — do not commit — but *lā taqrabū*, do not come near, and al-Qurṭubī treats the choice as the foundation of a general jurisprudential principle: *sadd al-dharāʾiʿ*, the blocking of the means, which holds that what leads to the forbidden is itself forbidden. A prohibition on the act alone can be observed while every road to it remains open; a prohibition on approach closes the roads. The same construction appears at 2:187 concerning the fast, at 2:229 concerning the transgression of limits, and at 6:151 in the parallel list, which indicates that the device is a settled feature of Qur’anic legislation rather than a rhetorical variation.

The Prophetic tradition supplies the mechanism the prohibition targets. Al-Bukhārī (6243) and Muslim (2657) record:

> *“The eyes commit zinā and their zinā is the look; the ears commit zinā and their zinā is listening; the tongue commits zinā and its zinā is speech; the hand commits zinā and its zinā is the touch; the foot commits zinā and its zinā is the step; and the heart desires and wishes — and the private part confirms that or denies it.”* (al-Bukhārī 6243)

The ḥadīth does not equate these with the legal sin; it describes the sequence by which the legal sin is approached, which is exactly what the verse’s verb forbids. The social logic is stated in the verse’s own terms: *fāḥishah* denotes an excess beyond measure, and *sāʾa sabīlā* — an evil way — describes a trajectory rather than an event. The placement between two prohibitions of killing is the key to the classical reading: the jurists organized the whole of the law around five protected interests — religion, life, intellect, lineage, and property — and verses 31 to 34 of this sūrah cover three of them in order, with zinā destroying *nasab* (lineage). A child of uncertain paternity was, in the pre-modern world, without inheritance, protection, or standing, so the destruction of lineage functions as a form of social killing, which is why it stands between two literal ones."""),

33: ("**Sulṭān With Three Options: How a Chain of Vengeance Was Cut**",
"""The verse’s central achievement is not the authorization of retaliation but its *discretion*, and the difference abolished a mechanism that had produced generations of tribal war. Pre-Islamic Arabia operated on mandatory vengeance, extended to the kin: the killing of one man could justify the killing of his kinsman of equal or greater status, escalating indefinitely, as in the war of al-Basūs that ran for forty years over a single camel. This verse transfers the decision to a specific individual — the *walī*, the near relative with standing — and gives him three options: to demand execution in retaliation (*qiṣāṣ*), to pardon, or to accept the blood-money (*diyah*). 2:178 states the same structure and then recommends the merciful option: *“But whosoever is pardoned somewhat by his brother, let the following be honorable and the payment be with kindness.”*

The clause *fa-lā yusrif fī al-qatl* — let him not be excessive in slaying — is the clause that ends the chain. Al-Ṭabarī explains it as the requirement that retaliation fall only on the actual perpetrator and not extend to his family or tribe; al-Qurṭubī adds the prohibition of torture, mutilation, or disfigurement before execution. The two together convert vengeance into law: the punishment is proportionate, individual, and executed by authority rather than by the aggrieved. Al-Bukhārī (2434) records the incentive attached to mercy:

> *“Whoever has a right of retaliation and he pardons, it is an expiation for him.”* (al-Bukhārī 2434)

And 5:45 states the principle as a moral ranking: *“And We ordained for them therein a life for a life... and whosoever forgoes it in charity, it is an expiation for him.”* The verse’s assurance that the heir *kāna manṣūrā* — will be helped — is directed at the family of the murdered, the people most likely to take the law into their own hands precisely because they feel no one else will act. The historical use of the verse is worth noting for its limits: Ibn Kathīr records that ʿAmr ibn al-ʿĀṣ invoked it at the arbitration after Ṣiffīn to argue that Muʿāwiyah, as *walī* of the slain ʿUthmān, possessed *sulṭān* in the sense of political authority, and the exegetes generally decline to endorse the extension of a right of retribution into a claim to the caliphate."""),

34: ("**Badāran an Yakbarū: The Guardian’s Specific Temptation**",
"""The Qur’an legislates the orphan’s property twice, and the second formulation names the temptation so precisely that it functions as a diagnosis. 4:6: *“And test the orphans until they reach marriageable age; then if you perceive in them sound judgment, deliver to them their property, and consume it not wastefully and hastily, anticipating that they will grow up (badāran an yakbarū).”* The final clause identifies the exact pressure on a guardian: the child cannot yet ask, cannot yet account, and will one day arrive with the right to demand. The interval between the death of the father and the maturity of the son is therefore a period in which the only check on the guardian is his own conscience, which is why the prohibition here is on *approach* rather than on consumption — the guardian may not place himself where the wealth is within his casual reach.

The permissions in the phrase *illā bi-llatī hiya aḥsan* are correspondingly careful. Al-Ṭabarī and al-Qurṭubī specify the cases: where the property is land or animals, the guardian may use it in ways that maintain rather than deplete it; an indigent guardian may take what is strictly necessary; and the guardian may trade the property in order to increase it. The governing standard is comparative — every act must be *aḥsan*, better than the alternative — and 4:2 supplies the sanction: *“Truly those who consume the property of orphans unjustly consume nothing but fire into their bellies.”*

The second command, on the covenant, is not a separate topic but the same one stated more generally, since guardianship *is* a covenant. The grammatical striking of the closing phrase is what gives it force: *inna al-ʿahda kāna masʾūlā* — the covenant itself is described as questioned, not the person who made it. Al-Rāzī explains the construction as a rhetorical intensification, as though the promise were a witness summoned to testify. The device belongs to a family of Qur’anic images in which the instruments of human action become witnesses — the tongue and hands at 24:24, the skin at 41:20–22 — and its application is uncomfortably current: the casual assurance, the verbal commitment, the contract signed without reading, all acquire a weight that ordinary life does not assign them."""),

35: ("**Al-Qisṭās: A Foreign Word Placed in the Moral Code**",
"""The word *qisṭās* is a loanword, most likely from Greek, meaning a balance or scale, and its presence in the middle of a code that opens with tawḥīd and closes with the prohibition of shirk is itself a claim. The Qur’an could have used the native *mīzān*, which it does use elsewhere — 55:7–9, *“And the heaven He raised, and He set the balance, that you not transgress in the balance — so establish the weight with justice and diminish not the balance.”* The choice of a commercial foreign term anchors the command in the actual marketplace of the audience rather than in an abstract register, and it places the counting-house inside the moral code rather than beside it.

The command runs in both directions, and Sūrah al-Muṭaffifīn is named for the asymmetry:

> *“Woe to the defrauders, who, when they take measure from mankind, take it in full; but when they measure or weigh for them, they diminish. Do they not think that they will be resurrected for a tremendous Day?”* (83:1–5)

The defrauder takes in full and gives short, which is the structure of most economic dishonesty: the party with more information or more power adjusts the measure in his favor, and the other party cannot verify. This is why al-Qurṭubī and the jurists after him extended the command well beyond physical scales — to wages, to the description of goods, to the concealment of defects, to every exchange in which what is given and what is received are meant to correspond. The mission of Shuʿayb to Midian was substantially economic, which indicates how central the issue is to the Qur’anic conception of a just society: 11:85, *“O my people, give full measure and weight with justice, and withhold not from mankind their goods, and do not act corruptly in the land, making mischief.”*

The closing phrase *aḥsanu taʾwīlā* — better in its outcome — makes a claim about the long run that is counterintuitive enough to require the argument, since in the short run the defrauder plainly profits. The Qur’an does not deny this; it disputes its duration, as at 30:39: *“And whatever you give of usury that it may increase in the wealth of mankind, it increases not with God.”* The economics of the Qur’an run on a longer horizon than the quarter, and the tradition attaches to commercial honesty a rank that indicates how reliable an indicator it is: al-Tirmidhī (1209) records, *“The truthful, trustworthy merchant is with the prophets, the truthful, and the martyrs.”*"""),

36: ("**Qafw and Tajassus: Two Prohibitions About Attention**",
"""The verb *taqfū* is from *q-f-w*, to follow on the heels, to track — the same root as *qāfah*, the tracker who reads footprints in sand — and the image determines the range of the prohibition. Al-Ṭabarī, al-Rāzī and al-Zamakhsharī identify three applications, all supported by the verb. The first is speech: do not say what you do not know, which includes false testimony and the claim to knowledge one does not possess. The second is inquiry: do not investigate private matters in order to expose the faults of others, which is the prohibition stated at 49:12, *“And spy not (wa lā tajassasū), nor let some of you slander others.”* The third is following: do not follow a path or a guide without knowing whether he will guide or mislead, which al-Zamakhsharī reads as a rebuke of *taqlīd* in matters of belief.

The distinction the jurists drew on the third reading is careful and still governing. In law, the non-specialist necessarily follows the rulings of the qualified; in creed, blind following is not permitted, because belief requires knowledge. Al-Rāzī records the related dispute over whether the verse forbids reasoning by analogy (*qiyās*), since analogy involves inference beyond certain knowledge, and the majority response: many necessary determinations — the direction of the qiblah from a distant location, the issuance of a non-binding legal opinion — inherently involve estimation, so the verse prohibits following *without* knowledge, not reasoning *toward* it. The line runs between examined conjecture and unexamined conjecture.

The closing clause supplies the enforcement mechanism, and its two readings are both preserved. Either the person will be questioned about each faculty — how he used his hearing, his sight, and his heart — or the faculties themselves will be questioned, as witnesses, in the manner of 41:20–22, where the skin says, *“God, who gives speech to all things, gave us speech.”* The second reading is the more precise for the verse’s purpose, because it makes the instruments participants rather than neutral channels: the ear that listened to slander, the eye that sought what it should not see, and the heart that entertained what it should not entertain will each give an account. No verse in this sūrah addresses the modern condition more directly, since an environment in which assertion is costless and the forwarding of the unverified costs one tap is a mass implementation of *qafw*. The rule is not a prohibition of ignorance but of acting as though one knows; the person who says “I do not know” has complied."""),

37: ("**Legislating a Gait: Why the Qur’an Addresses the Body**",
"""That a revealed book concerns itself with how a person walks is not a detail but a method, and al-Rāzī explains the reasoning: the body is not separate from the soul but trains it. The relationship runs in both directions — arrogance produces the arrogant gait, and the arrogant gait deepens the arrogance — so prohibiting the visible sign is a practical means of prohibiting the state. This is why the Qur’an’s ethics include so much physical detail: the lowering of the gaze, the moderation of the voice at 31:19 (*“And lower thy voice; truly the most repulsive of voices is the voice of the donkey”*), the humble walk of the servants of the Compassionate at 25:63 (*“who walk upon the earth gently (hawnā)”*). Each is small, repeatable, publicly observable, and formative through repetition.

The noun *maraḥ* denotes exultant, self-conceited walking, and Luqmān’s counsel to his son at 31:18 pairs it with a second gesture: *“And turn not thy cheek from mankind in disdain, nor walk upon the earth exultantly. Truly God loves not any arrogant boaster.”* The tradition preserves the Prophet’s ﷺ own manner as the counter-example, in the description composed by ʿAlī ibn Abī Ṭālib and preserved by al-Ṭabarī in his *Taʾrīkh*: he walked energetically, leaning forward as though descending a slope, but never proudly. The description distinguishes two things a casual observer conflates — vigor and arrogance — and it clarifies the prohibition’s target: not confident, purposeful movement, but movement that performs superiority. Muslim (91) supplies the definition that makes the gait legible as a moral fact:

> *“Pride (kibr) is rejecting the truth and despising people.”* (Muslim 91)

The definition is behavioral rather than emotional, which is why a walk can be legislated. The verse’s rhetorical method for curing self-importance is not exhortation but *scale*: you will not pierce the earth, and you will not reach the mountains in height. However forcefully the arrogant walker strikes the ground, the earth is not impressed, and next to a mountain his stature is nothing. The same technique appears at 40:57 — *“The creation of the heavens and the earth is greater than the creation of mankind, but most mankind know not”* — and its function is identical: the cure offered is not a lecture on humility but a look out of the window."""),

38: ("**Makrūh as an Attribute: The Theology of Divine Aversion**",
"""The verse attributes *dislike* to God, and the classical theologians handled the attribution with care precisely because it is an affective term. *Makrūh* is the passive participle of *kariha*, to find hateful, and the standard Sunni position — articulated by Ibn Taymiyyah and held in different formulations by the Ashāʿirah and Māturīdiyyah — is that the divine attributes are real and not reducible to created affect: God’s dislike is a true attribute whose *reality* is not like ours, and whose *consequence* for the creature is what the verse is concerned to establish. The prohibited acts are therefore not arbitrary taboos but things God finds repugnant, and the Qur’an uses this vocabulary extensively in both directions: *“God loves not the transgressors”* (2:190), *“God loves not any arrogant boaster”* (4:36), *“God loves not any ungrateful sinner”* (2:276), against *“God loves the patient”* (3:146), *“God loves those who purify themselves”* (9:108), *“God loves the doers of good”* (2:195).

The unifying verdict of this verse is therefore a claim of considerable moral seriousness, and its most important effect is what it refuses to rank. Infanticide, adultery, murder, misappropriation of an orphan’s wealth, fraudulent measure, speaking without knowledge, and arrogant bearing are all described as *makrūh* to the same Lord in the same way. A moral code that ended without such a verdict could be read as a list of rules of varying weight, permitting the reader to treat economic dishonesty as a minor matter beside violence. The verse forecloses that reading. The shift to the second person — *ʿinda rabbika*, with thy Lord — is directed to the Prophet ﷺ and through him to every reader, and al-Rāzī notes that this personal form appears at points of consolation. The one who keeps this code will often find himself at odds with the surrounding culture, which practiced infanticide, defrauded in trade, and prized the arrogant gait; the verse assures him that the divergence is not a defect, and that what his society considers normal, his Lord considers loathsome."""),

39: ("**Why the Code Is Called Ḥikmah and Not Only Law**",
"""The designation of verses 22–39 as *ḥikmah* — wisdom — rather than as *aḥkām*, rulings, is a claim about their epistemic status, and the classical tradition debated its implications at length. Al-Rāzī’s position is that the inherent rightness of these injunctions is evident to reason, which is why they are found in every religion and every creed and why they are never abrogated: unlike ritual details, which vary between revelations, the moral core does not change. A report preserved by al-Rāzī and al-Ṭabarī states that all of these injunctions were found in the tablets given to Moses, and the claim is contextually pointed, since the sūrah has been discussing the Children of Israel since verse 2. This is the scriptural ground for the position that the moral law is both revealed and rational — the view of the Māturīdiyyah and of many Muʿtazilīs, and substantially shared by the Ashāʿirah with respect to the *content* of the good even where they located its *obligatoriness* in the command. Ibn Taymiyyah reached the same conclusion by another route: revelation and sound reason never conflict, because both issue from a single source.

Al-Zamakhsharī’s structural observation explains the frame. Verse 22 opened with *“Do not set up another god along with God”*; verse 39 closes with the identical words, because knowledge of God’s Oneness is the beginning and foundation of all wisdom. Each command between them fails without tawḥīd for a specific reason — kindness to parents fails when the parent’s approval becomes the ultimate standard, honest measure fails when wealth does, chastity fails when desire does, truthfulness fails when reputation does — and in every case the failure occurs precisely where something created has been enthroned. The ḥadīth tradition supplies an independent testimony to the passage’s standing. Al-Tirmidhī (3145) records from ʿAbdullāh ibn Masʿūd:

> *“Whoever wishes to look at the will (waṣiyyah) of Muhammad ﷺ upon which is the seal of his ring, let him read: 'Do not set up another god along with God' — until he completes these verses.”* (al-Tirmidhī 3145, graded ḥasan)

The parallel passage at 6:151–153 contains substantially the same code and is similarly described in the tradition as the testament of the revelation, which indicates that the early community recognized this material as the settled moral floor beneath which a Muslim life does not fall."""),

40: ("**Reductio ad Absurdum: The Qur’an’s Argument From the Opponent’s Prejudice**",
"""The verse’s method is not metaphysical demonstration but *reductio*, and its force depends entirely on a fact the Qur’an states elsewhere with unusual bluntness. 16:57–59 records both halves of the belief it is dismantling:

> *“And they ascribe unto God daughters — glory be to Him! — and for themselves what they desire. And when one of them is given the tidings of a female, his face darkens and he chokes with grief. He hides himself from the people because of the evil of what he has been told: shall he keep her in humiliation, or bury her in the dust? Surely evil is what they judge.”* (16:57–59)

The men who claimed the angels were God’s daughters regarded the birth of a daughter as a calamity, to the point that infanticide was practiced — the very practice verse 31 of this sūrah prohibits. The argument is therefore devastating in its simplicity: you attribute to God the thing you regard as a misfortune for yourselves, and you keep for yourselves the thing you regard as a blessing. 53:21–22 states the logical form explicitly: *“What! For you the male, and for Him the female? That indeed were an unfair division (qismatun ḍīzā).”*

The significance of the method extends beyond this verse. The Qur’an frequently argues against shirk not by abstract proof alone but by exposing the internal incoherence of the belief using the believer’s own standards — at 43:16–19, at 52:39, at 37:149–153. A belief whose holders would reject it if applied to themselves is not a belief but a convenience, and the exposure of the convenience is often more persuasive than any demonstration, because it cannot be denied. The word *ʿaẓīm* — enormous, monstrous — is applied to the *speech* rather than to a private thought, and the choice is deliberate: the condemnation falls on a statement made publicly, defended, and built into a religious system. The diagnostic remains available in modern form, since every generation attributes to God whatever its own culture finds acceptable and refuses what its culture finds distasteful, while insisting that the resulting picture is the truth about God rather than a mirror of the age. The test the verse supplies is simple: if your conception of God differs from your neighbor’s in exactly the places where your culture differs from his, the conception may be doing more work for you than for the truth."""),

41: ("**Ṣarrafnā and Nufūr: The Verse That Divided the Theologians**",
"""The verb *ṣarrafa* is the intensive of *ṣarafa*, to turn in different directions, and its application to the Qur’an’s own composition — at 6:46, 6:65, 6:105, 7:58, 46:27, and 18:54 for the parables — describes a deliberate design. Al-Bayḍāwī explains the variation: the same truth is presented sometimes as rational demonstration, sometimes in an awesome register that inspires fear, sometimes in a gentle register that attracts. Argument, narrative, image, law, warning, promise, dialogue, oath — every mode is employed, because different minds are reached by different approaches. The stated purpose, *li-yadhdhakkarū*, uses a verb from *dh-k-r*, to remember, which implies that the content is not wholly new to the human being but something he once knew and has forgotten; the response the revelation seeks is recognition rather than information.

The verse became a battleground between the Muʿtazilah and the Ashāʿirah, and al-Rāzī preserves both arguments. The Muʿtazilite reading: God varied the signs precisely *so that* different people could reflect, which indicates a universal divine will for human understanding. The Ashʿarite counter-reading: God varied them knowing that some would be increased only in aversion, which indicates that the divine will encompasses the turning away of some. The Sunni synthesis distinguishes the universal will — what God commands and desires for all — from the particular will, what God brings about — and holds the hearer responsible for his response to a guidance genuinely offered. The verse’s own grammar supports this: the variation is *for the sake of* reflection, while the aversion is attributed to the hearers as something that happens *in them*.

The word *nufūr* is stronger than dislike. It is from *n-f-r*, to flee in alarm, to shy away as a startled animal does, and it denotes a reflexive recoil rather than a considered rejection. The Qur’an documents the divergence without embarrassment at 2:26 — *“He misleads many thereby and guides many thereby, and He misleads none but the transgressors”* — and at 9:124–25, where the same sūrah increases some in faith and increases others in filth upon their filth. The practical consequence for anyone responsible for conveying truth is a considerable liberation: the outcome is not wholly in the conveyor’s hands, and its failure is not proof that the conveying was defective. The messenger’s task is to vary the approach; the response belongs to the hearer."""),

42: ("**Dalīl al-Tamānuʿ: The Argument From Mutual Prevention**",
"""The verse states a conditional whose logic the later theologians formalized as *dalīl al-tamānuʿ*, the argument from mutual prevention, and its two classical readings correspond to the two ways a rival sovereignty could relate to the true one. Al-Zamakhsharī and al-Qurṭubī read it as competitive: were there other gods, they would seek a path to *dethrone* the Possessor of the Throne and struggle with Him for dominance. Ibn Kathīr and al-Rāzī preserve the submissive reading: the supposed gods would themselves seek nearness to the One God, recognizing His dominance, and would therefore be worshippers rather than objects of worship. The second reading answers the specific Quraysh claim recorded at 39:3 — *“We worship them only that they may bring us near to God”* — with a question: if these were gods, would they not seek nearness for themselves rather than serving as intermediaries for you?

The formal structure appears most clearly at 23:91: *“God has taken no son, nor is there any god along with Him; otherwise each god would have taken away what he created, and some of them would have risen over others.”* The premises are that beings with will contend where their wills differ; that the one whose will is prevented is not omnipotent; and that the observable cosmos displays a single coherent governance rather than the marks of contention. 21:22 supplies the empirical premise: *“Were there gods other than God in them, they would surely have been corrupted.”* The argument is not that contention is inconceivable but that it is absent, and its absence requires a single sovereign.

The verse’s application to intermediary worship is where it retains its force. The Quraysh acknowledged God as creator and placed idols between themselves and Him; the verse closes every available position for the intermediary. Whatever it is, it is either created — in which case it needs a way to God as much as the worshipper does, and cannot confer what it lacks — or uncreated — in which case it is a rival, and the coherence of reality refutes the supposition. There is no third option, which is why the conditional can be stated so confidently. The modern form of the same arrangement is easy to identify: whatever a person treats as the necessary intermediary between himself and ultimate reality — an institution, a lineage, a leader, a ritual system — falls under the same dilemma. Al-Rāzī’s conclusion is that whatever one claims as an object of worship other than God, to the extent that it exists at all, is itself dependent on the One God, and therefore cannot rightly be called a god in any true sense."""),
}
p='expanded/017.md'
s=open(p,encoding='utf-8').read()
parts=re.split(r'(?m)^(## Sūrah al-Isrāʾ 17:\d+)$', s)
d={int(parts[i].split(':')[1]):[parts[i],parts[i+1]] for i in range(1,len(parts),2)}
for n,(h,t) in ADD.items():
    body=d[n][1]
    hs=[m.start() for m in re.finditer(r'(?m)^\*\*(?!Expanded Commentary).+?\*\*$', body)]
    assert hs, n
    ins=hs[-1]
    d[n][1]=body[:ins]+'**'+h+'**\n\n'+t.strip()+'\n\n'+body[ins:]
out=[parts[0]]
for i in range(1,len(parts),2):
    n=int(parts[i].split(':')[1]); out.append(d[n][0]); out.append(d[n][1])
open(p,'w',encoding='utf-8').write(''.join(out))
print('added',len(ADD),'| words now',len(''.join(out).split()))
