import re
ADD = {
57: ("**Al-Wasīlah: The Means, and What the Word Does Not Include**",
"""The word *wasīlah* means a means of approach, that by which one draws near to a thing, and its appearance here in the mouths of the very beings invoked is the verse’s decisive move. Al-Ṭabarī records the occasion from Ibn ʿAbbās: the verse was revealed concerning a group of Arabs who had been accustomed to worship a group of jinn, and those jinn embraced Islam while their former worshippers, unaware of the change, continued to invoke them. The jinn are therefore described as themselves competing in drawing near to God — *ayyuhum aqrabu*, which of them is nearer — and the beings to whom worship was directed were themselves supplicants, ranked, and frightened of the very punishment they were invoked to avert.

The Qur’an uses the same word of the believer’s own duty at 5:35: *“O you who believe, fear God and seek the means of approach to Him (wa btaghū ilayhi al-wasīlah) and strive in His way.”* That verse is the ground of the classical discussion of *tawassul*, and the distinction that governs it is worth stating precisely. Every school agrees that the means of approach include faith, righteous deeds, and supplication itself — the Qur’an praises those who *“seek the means of approach to Him through that which pleases Him”* — and that a supplicant may ask God by reference to his own faith or his love of the Prophet ﷺ. The disputed question is whether one may invoke God by the person or the rank of another, and the disagreement is over evidence rather than principle. What no school claims, and what this verse excludes, is that the invoked party has power in himself: the one nearest to God is nearest *by approach*, not by nature.

The verse’s structure makes the point twice. First, the invoked are described with the three verbs of dependence: they *seek* means, they *hope* for mercy, they *fear* punishment. Hope and fear are the twin dispositions of worship in the Islamic account, and their presence in the object of worship dissolves its claim. Second, the punishment feared is described as *maḥdhūrā* — a thing to be guarded against — which the commentators gloss as a real and specific terror rather than a formal one. The beings appealed to for protection are themselves in danger, which is the shortest possible refutation."""),

58: ("**A Fixed Term for Every City, and the Book That Was Written**",
"""The verse is a universal statement about civilizations, and its placement — immediately after the refutation of intermediary worship and immediately before the account of the withheld sign — is not accidental. Al-Ṭabarī explains the two alternatives as destruction before the Hereafter or a severe chastisement, and both are attested in the preceding narratives: the people of Noah were destroyed, and the people who came after them were punished with the *ʿadhāb alīm* of verse 58 without annihilation. Al-Qurṭubī reads the verse as a direct warning to Makkah, and the historical outcome confirmed it: the city that had driven out the Prophet ﷺ surrendered to him within eight years of the Hijrah.

The phrase *fī al-kitābi masṭūrā* — written in a book, inscribed — connects the verse to the Qur’an’s doctrine of the divine decree, and the commentators are careful about what the doctrine does and does not imply. It does not make human choice irrelevant, since every city’s destruction in the Qur’an is attributed to its own wrongdoing; it means that the pattern is not arbitrary. 7:34 states it as a rule: *“And for every nation there is a term; when their term comes they cannot delay it an hour, nor can they hasten it.”* And 6:6: *“Have they not seen how many generations We destroyed before them? We had established them on earth as We have not established you.”* The Qur’an’s treatment of the past is thus a controlled comparison: power, wealth, fortification, and numbers did not prevent destruction, and the variables that determined the outcome were moral.

Al-Rāzī draws the consequence that gives the verse its modern relevance. The civilization that feels permanent is making an empirical error, and the error is corrected not by speculation but by evidence — the ruins are visible along the trade routes the Quraysh traveled twice a year. The verse’s argument is therefore archaeological before it is theological: look at what remains of the peoples who were stronger than you. The *masṭūr* then adds the dimension that makes the warning personal, because a term that has been written applies to the reader as well. Every institution, and every individual within it, is inside a schedule he did not set."""),

59: ("**The Sign That Was Withheld, and the Rule That Withheld It**",
"""The occasions recorded for this verse are among the most specific in the sūrah. Al-Ṭabarī preserves the report that the Quraysh asked the Prophet ﷺ to turn the hill of Ṣafā into gold, and that Gabriel came and offered it, and the Prophet ﷺ declined, preferring the pattern of prophetic patience. In another report they asked for a spring to gush forth, or for the sky to fall in pieces as he had claimed. The verse supplies the reason the request was not granted, and the reason is a settled divine practice: *wa mā manaʿanā an nursila bi-l-āyāti illā an kadhdhaba bihā al-awwalūn* — nothing prevented Us from sending the signs except that the former peoples denied them.

The commentators explain the mechanism precisely, and it is a mechanism of mercy. A people given an unmistakable sign and then disbelieving it are destroyed; that is the established *sunnah*. 6:158 states the rule: *“On the day some of the signs of thy Lord come, the faith of one who did not believe before will not profit him.”* The Quraysh’s request was therefore a request for their own destruction, and its refusal was the reason they survived to hear the message for thirteen more years and, most of them, to accept it. The verse’s phrase *wa ātaynā thamūda al-nāqata mubṣirah* supplies the case study: the she-camel was given, was denied, and Thāmūd was destroyed — *fa-ẓalamū bihā*, and they wronged themselves by it.

The second half states the positive principle: *wa mā nursilu bi-l-āyāti illā takhwīfā* — We send the signs only as warnings. Al-Rāzī explains that the signs are given to produce reflection, not to satisfy demand, and the distinction matters because a sign demanded on the questioner’s terms is not received as a sign but as a concession. 30:9 supplies the corollary: *“Then consider the end of those who did evil — they denied the signs of God and made a mockery of them.”*

The verse therefore explains why the Qur’an, rather than a miracle, is the central sign of this dispensation: a sign of the intellect can be received by every generation, argued about without coercion, and returned to without being exhausted — and 29:51 makes exactly this claim: *“Is it not sufficient for them that We have sent down to thee the Book, recited to them?”*"""),

60: ("**The Dreamed Vision and the Cursed Tree**",
"""The verse is among the most densely debated in the sūrah, and both its halves were contested in the Prophet’s ﷺ lifetime. The “vision We showed thee” is identified by al-Ṭabarī and Ibn Kathīr with the visions of the Night Journey, and the Qur’an calls them *ruʾyā* — a seen thing, though the classical discussion concerns whether the journey was of body and spirit together or of spirit alone, with the majority holding the former on the strength of 53:11–18 and of the reports. The *shajarah malʿūnah*, the cursed tree, is identified with *Zaqqūm* by an overwhelming consensus of the exegetes, and 37:62–66 describes it: *“Is this a better welcome, or the tree of Zaqqūm? We have made it a trial for the wrongdoers. It is a tree that springs from the bottom of the Hellfire; its spathes are as though they were the heads of devils.”*

The controversy is the verse’s stated subject, since the Qur’an says the tree was made a *fitnah* — a trial, a thing that separates people. Al-Ṭabarī preserves the reports of the Makkan response: Abū Jahl is said to have mocked the claim by calling for butter and dates and declaring that this was the Zaqqūm with which the Prophet threatened them, arguing that fire consumes trees and cannot nourish one. The objection is a category error — the fire of the Hereafter is not the fire of this world, and the tree described is not a tree of the botanical kind — but it functioned as a trial because it gave the hearers a reason to disbelieve that felt like a reason. The verse names this dynamic exactly: *wa nukhawwifuhum fa-mā yazīduhum illā ṭughyānan kabīrā*, We frighten them and it increases them only in great insolence.

The doubling of the trial — the vision and the tree — is instructive. Both were given as evidence, and both became occasions of division, because evidence is not self-validating: it is received by a disposition, and the same datum confirms the receptive and hardens the resistant. 74:31 makes the general point about the revelation as a whole: *“God lets go astray whom He wills and guides whom He wills, and none knows the hosts of thy Lord but He — and this is nothing but a reminder to mankind.”* The verse therefore supplies a criterion for reading any difficult text: the difficulty is part of the test rather than an obstacle to it, and the response it produces is what is being measured."""),

61: ("**Iblīs’s Question, and the Fallacy Beneath It**",
"""The command to the angels and the refusal of Iblīs are narrated in seven places in the Qur’an, and each account adds a distinct element; this one adds the question, and the question exposes the reasoning. *A-raʾaytaka hādhā alladhī karramta ʿalayya* — “Do you see this one whom Thou hast honored above me?” — is a challenge to the divine judgment rather than to the command. 38:76 supplies the reasoning behind it: *“I am better than him; Thou didst create me from fire and didst create him from clay.”* The argument is one of material composition, and its structure is a syllogism with a false premise: what is nobler in substance produces what is nobler in being.

Al-Rāzī and Ibn Kathīr dismantle the premise on several grounds. Fire is destructive, unstable, and rises; clay is generative, stable, and receives form. Fire consumes what it touches and clay nourishes what is planted in it. The human being’s composition is precisely what allows knowledge — the receptivity that the angels’ question at 2:30 anticipated — while Iblīs’s composition allows only heat. And the deeper error is that the argument bypasses the divine act entirely: God did not honor Adam for his clay but for what He gave him, namely the *names*, and the angels’ prostration was obedience to a command whose wisdom had been disclosed to them. Iblīs’s refusal is therefore not a considered judgment but the assertion of self-sufficiency — *istikbār* — which 38:75 names directly: *“What prevented thee from prostrating when I commanded thee? He said: I am better than him.”*

The consequence is the delay, and the delay is a mercy whose shape is easily missed. *Ukkhirnī ilā yawmi yubʿathūn* — grant me respite until the day they are raised — is granted as *ilā yawmi al-waqti al-maʿlūm*, until the appointed time, which 15:38 specifies. Had the refusal been answered with immediate annihilation there would be no test, and without the test there would be no distinction between the sincere and the coerced. 14:22 preserves Satan’s own admission that his power was never real: *“God promised you the promise of truth, and I promised you and broke my promise to you; I had no authority over you except that I called you and you answered me — so blame me not, but blame yourselves.”* The verse that follows here states the same limit: *innā ʿibādī laysa laka ʿalayhim sulṭān*."""),

62: ("**A Stated Success Rate: The Enemy’s Own Estimate**",
"""This verse is remarkable for its frankness. The adversary announces his plan and his expected yield in the same breath: *la-aḥtanikanna dhurriyyatahu illā qalīlā* — I will surely take hold of his offspring, except a few. He does not claim all of them. The estimate is stated by the one making the effort, and it is the most compact statement in the Qur’an of the scope of temptation.

The verb is from *ḥ-n-k*, and the commentators explain it variously as to embrace, to encompass, to bring under one’s control, and — in the image al-Qurṭubī prefers — to take hold of the *ḥanak*, the palate, as one who leads a horse by the bridle in its mouth. On that reading the verb describes not a blow but a hold, and the image is of a mount directed by its rider rather than of an enemy striking. Al-Rāzī’s observation is that the tactic is encirclement rather than assault: the person is not attacked once but surrounded gradually, so that every direction of escape leads to the same place. This matches the fourfold strategy of the following verse, which is a program rather than a temptation.

The exception — *illā qalīlā* — is the verse’s hinge, and the Qur’an is consistent about the proportion. 12:103: *“And most of them, though thou art eager, are not believers.”* 38:24 and 7:17 both carry the same qualification. The minority is small and it is specified elsewhere as the sincere servants: 15:40 records the exception from the other side, *“except My servants among them, the sincere ones.”* The two statements together give the structure of the human condition as the Qur’an describes it: the majority is taken hold of, the minority is not, and the difference is not capacity but sincerity.

The practical consequence is uncomfortable and useful. A strategy that expects to succeed against most people is designed for the ordinary rather than for the exceptional, and it will therefore work on anyone who assumes he is the exception without doing the work the exception requires. 14:22 records Satan disclaiming responsibility on the Day: *“I had no authority over you except that I called you and you answered me.”* The admission identifies what actually happened — an invitation that was accepted — and locates the decision where it was made."""),

63: ("**Go: A Permission That Is Not an Approval**",
"""The imperative *idhhab* — go — has generated careful comment, because a divine command ordinarily indicates divine pleasure and this one cannot. Al-Rāzī and al-Ṭabarī resolve it by distinguishing the imperative of endorsement from the imperative of permission (*idhn*), and the distinction is a general principle of Qur’anic theology: God’s granting of a request, or His permitting an act, is not His approving it. The same structure appears at 2:185 and throughout the legislation of concessions — what is permitted is not thereby commended. Al-Qurṭubī adds a second reading: the command carries humiliation in it, as when one says to an insolent person *go and do what you like*, the phrase being itself a threat.

The second clause is the theological center: *wa kafā bi-jahannama jazāʾan* — Hell is sufficient as a recompense. The commentators note the word *jazāʾ*, which is a recompense and a *just* one, and its pairing with *sufficiency* produces a precise claim: the punishment corresponds to the crime and is not exceeded. 4:122 and 29:54 use the same formula of the reward of the believers, *“and it is a sufficient reward,”* which establishes that sufficiency is a term of justice rather than of intensity — each receives what corresponds, no more.

The granting of the delay is then explained in the tradition by a third consideration, which al-Rāzī draws out. The delay is itself a mercy, since it makes the test possible, and the test is the only thing that distinguishes a willing servant from a compelled one. Had Iblīs been destroyed at his refusal, the human being would have had no adversary and therefore no occasion to choose God against a competing claim; there would be obedience but not love, and compliance but not sincerity. The verse’s own wording supports this: Iblīs is sent rather than annihilated, and what is sent is *man istaḥwāhu*, whoever he makes to follow him, which implies a following entered into rather than imposed. 16:99–100 states the limit of the permission with equal precision: *“His authority is only over those who take him as a patron and those who associate partners with Him.”* The permission has a defined range, and the range is set by the human being’s own response."""),

64: ("**Voice, Cavalry, Infantry: Temptation as an Organized Campaign**",
"""The four commands in this verse are the Qur’an’s fullest description of the methods of temptation, and the military metaphor is deliberate: *ajlib* is a command used of driving horses and gathering troops with a shout. Temptation is not presented as a series of unrelated suggestions but as a coordinated operation with distinct arms. Al-Ṭabarī and Ibn Kathīr identify them: the *voice* is the call to disobedience — every summons to sin, including, on one report, singing and idle talk; the *cavalry* is the mounted force, and the commentators gloss it as the temptations that come swiftly and openly; the *foot-soldiers* are those that come on foot, slowly and persistently, and al-Ṭabarī records the specific gloss that every disobedient person on horseback or on foot is among them.

The fourth arm is the most subtle and the most consequential: *wa shārikhum fī al-amwāl wa al-awlād* — share with them in wealth and children. The commentators enumerate the partnerships exhaustively. In wealth: unlawful acquisition, interest, vows made to idols, wealth spent in disobedience, wealth withheld from its due, and the division of inheritance by pre-Islamic custom. In children: children born outside the marriage bond, children raised in disbelief or in corruption, children dedicated to idols, and children used as instruments of disobedience. The verb *shārik* — be a partner — is the sharpest word in the list, because it does not describe theft but co-ownership: the adversary does not take the wealth away, he acquires a share in how it is used. This is why 63:9 warns against it in the strongest terms: *“O you who believe, let not your wealth nor your children divert you from the remembrance of God.”*

The promise that follows — *wa ʿidhum, wa mā yaʿiduhum al-shayṭānu illā ghurūrā* — identifies the mechanism that makes the campaign work: deception about the outcome. The temptation does not present itself as loss but as gain, and the gain is real in the short term, which is precisely what makes the deception effective. 14:22 records the confession: *“I promised you and broke my promise to you.”* The verse’s own summary of the whole enterprise is in its last words: the promise is *ghurūr*, an illusion that looks like a thing.

The modern application requires no translation. Every system that monetizes attention operates by exactly this architecture — a voice, a mounted and a foot-borne reach, and a partnership in the household’s wealth and children — and it presents itself throughout as enrichment. The verse names the pattern, and naming it is the greater part of resisting it."""),

65: ("**The Null Hypothesis: No Authority Over the Servants**",
"""The verse is the exception that defines the promise, and its first word does the work: *ʿibādī*, My servants. Al-Rāzī and al-Qurṭubī both note that the possessive restricts the statement, since not every human being is described in the Qur’an as God’s servant in this sense — the term denotes the one who serves Him sincerely. The immunity is therefore conditional, and the condition is stated in the following words: *wa kafā bi-rabbika wakīlā*, sufficient is thy Lord as a trustee. The one who takes God as his *wakīl* is protected; the one who does not is not, and the verse makes no claim beyond that.

The word *sulṭān* — authority, dominion, compelling power — is what is denied, and the denial is narrow and therefore precise. Satan is not said to be absent from the believer’s life, nor incapable of whispering, nor unable to suggest. What is denied is his *authority*, his power to compel. 16:99–100 states the same limit: *“There is no authority for him over those who believe and rely upon their Lord. His authority is only over those who take him as a patron.”* And 15:40–42 gives the exception from the adversary’s side. The Qur’an’s anthropology here is coherent: temptation is real and universal, compulsion is not, and the distinction between the two is the space in which human responsibility lives.

The verse closes with the sufficiency of God as *wakīl*, and the word has already appeared in this sūrah at verse 3 and verse 54, where the Prophet ﷺ is told that he is not a *wakīl* over the people. The pairing is instructive: the Prophet ﷺ does not hold that office over anyone, and God holds it fully over those who accept it. The one who has God as trustee has delegated the outcome, which is not passivity but the condition of acting without anxiety — the same disposition 65:3 describes as *tawakkul* and attaches to the promise of sufficiency: *“And whoever relies upon God, He is sufficient for him.”*

The psychological consequence is direct. The believer who understands this verse does not experience temptation as evidence of abandonment but as evidence of a fight that he has the standing to win. The one who believes the adversary has authority over him has already conceded the premise on which the adversary operates, and 14:22 shows the adversary disclaiming exactly that premise on the Day: *mā ana bi-muṣrikhikum wa mā antum bi-muṣrikhiyya* — I cannot help you and you cannot help me."""),

66: ("**The Ship as the Paradigm Case of Dependence**",
"""The shift from the argument about Iblīs to the image of the sea voyage is not a change of subject but a change of evidence. Al-Ṭabarī explains the connection: having established that no created being has power over the servant of God, the Qur’an demonstrates the point in the setting where the human being is most aware of his helplessness. The sea voyage was the paradigm case of uncontrollable danger for the pre-Islamic Arab, whose world was the desert and whose relationship to the sea was one of trade and dread, and the Qur’an returns to it repeatedly — 10:22, 16:14, 29:65, 31:31–32, 42:32–34.

The verb *tujrī*, runs, carries the sense of being made to run: the ship is not self-propelled but driven, and the phrase *bi-l-baḥr* rather than *fī al-baḥr* indicates movement through the sea rather than mere location. The clause *bi-faḍlin minhu*, by His favor, is the theological pivot. The wind that fills the sail is not a natural constant but a favor conferred, and the verse thereby removes the possibility of taking the voyage for granted. 45:12–13 makes the same point at length, ending with the purpose: *“...that you may seek of His bounty, and that you may be grateful.”*

The verse’s rhetorical function within the sūrah is to complete the argument begun at verses 56–57. Those verses established the point by argument: the invoked are themselves supplicants, fearful, seeking means of approach. This verse establishes it by experience: in the storm there is no one else to call. Al-Qurṭubī notes the reason the sea is chosen as the setting: it removes the intermediaries physically, since the idols are on shore and the ship is between two elements that no one controls. The result is the purest available test of a person’s actual theology, and the verses that follow record the outcome — which is not what the Qur’an wishes it to be.

The modern parallel is exact in structure. Every person lives inside systems he does not control and mostly does not notice, and the notice comes in the failure: the diagnosis, the market collapse, the flight through turbulence. The verse treats that moment not as an interruption of ordinary life but as a disclosure of what ordinary life actually is — *bi-faḍlin minhu*, by a favor, every hour of it."""),

67: ("**Distress, Invocation, Rescue, Relapse: The Anatomy in Four Steps**",
"""The verse is a sequence rather than a description, and its four steps are stated with clinical precision. First the affliction: *massakum al-ḍarru*, the harm touches you. Second the invocation: *daʿawtumuhu ḍurraʿan*, you call upon Him humbly, the word *ḍurraʿ* denoting the abasement of one who has no alternative. Third the rescue: *kashafa ʿankum*, He removes it from you. Fourth the relapse: *aʿraḍtum*, you turn away — and the verb is specific, from the root meaning to turn the shoulder, the gesture of deliberate withdrawal rather than of forgetting.

The word *ḍurraʿ* is worth pausing on, because it describes the quality of the invocation rather than its content. The one who calls *ḍurraʿan* has abandoned pretense; the intermediaries are gone and the voice is the voice of a person who has nothing left. The Qur’an treats this invocation as evidentially significant, not as hypocrisy. 29:65 states the same sequence: *“And when they embark upon a ship, they call upon God, sincere to Him in religion (mukhliṣīna lahu al-dīn); but when He has brought them safely to land, behold, they associate.”* The word *mukhliṣīn* — sincere, purified — is applied to people the Qur’an elsewhere condemns, which is a striking theological claim: their sincerity in the crisis is genuine, and the association that follows is also genuine, and both are true of the same people.

Al-Qurṭubī draws the doctrinal inference: the invocation in distress is proof that the knowledge of God is present in the human being prior to argument, since it emerges when argument is unavailable. This is the doctrine of *fiṭrah* stated through behavior rather than asserted — 30:30’s *“the nature (fiṭrah) upon which God originated mankind”* is demonstrated rather than declared. 39:8 adds the psychological detail that makes the verse most useful: *“And when affliction touches man, he calls upon Us; then when We bestow a favor from Us upon him, he says: I was given it only by knowledge (ʿalā ʿilm).”* The relapse is accompanied by a theory, and the theory attributes to his own competence what was in fact delivered to him.

The verse’s final clause — *wa kāna al-kafūru kafūrā* — is a rhetorical intensification, and the commentators read it as either the specific reference to the disbeliever or the general statement that the ungrateful person is intensely so. The doubling is deliberate: the *kāfir* is *kafūr*, the one who covers is one who covers much. The sequence therefore closes with a diagnosis rather than a verdict, and the diagnosis is available to any reader: watch what you say in the crisis, and then watch what you say a week later."""),

68: ("**Four Fears on Land: The Argument That Safety Is Not a Place**",
"""The verse answers the implicit objection in the previous one, and the objection is natural: the lesson of the sea does not apply to me, because I live on land. The four questions close that escape, and they are ordered from the ground upward. *Yakhsifa bikum al-arḍ*, He causes the earth to swallow you — the threat is beneath the feet. *Yursila ʿalaykum ḥāṣibā*, He sends upon you a *ḥāṣib*, a storm that pelts with stones or gravel — the threat is from above. The two directions exhaust the physical environment, and the pairing is the Qur’an’s characteristic completeness.

The word *ḥāṣib* is specific rather than general, and al-Ṭabarī glosses it as a wind that carries gravel, which is the punishment sent on the people of Lot at 11:82 and 15:74. The reference matters, because the threat is then not hypothetical: it has happened, to a named people, in recorded history, and the same word is used at 51:32 and 67:17. The verse’s question is therefore not “could this happen?” but “has it not happened, and what makes you exempt?” — the argument the sūrah made at verse 58 from the ruins on the caravan road.

The two closing clauses are the more penetrating part. *Thumma lā tajidū lakum wakīlā* — then you will find no trustee — and at verse 69, *thumma lā tajidū lakum ʿalaynā bihi tabīʿā*, you will find no one to pursue Us for it. Al-Rāzī explains the function of the *wakīl* here: it is the one to whom a person in danger turns for protection and management of his affair. The verse removes not merely the safety but the recourse. On land the human being assumes he has options — a wall, a shelter, a neighbor, an authority — and the verse strips them in a single clause.

The psychological force of the passage lies in its refusal to let the setting do the work. The man who has learned the lesson of the sea and returned to the land has learned nothing if he concludes that the lesson belonged to the sea. 67:16–17 makes the same argument with the same two directions: *“Do you feel secure that He Who is in the heaven will not cause the earth to swallow you? Or do you feel secure that He Who is in the heaven will not send upon you a storm?”* The point is not that disaster is imminent but that security is not a property of geography, and the person who has confused the two has located his trust in the wrong place."""),

69: ("**The Second Pair, and the Question of Redress**",
"""The verse repeats the structure of verse 68 at sea, and the repetition is the argument: the two environments are governed by the same authority, and safety is not a matter of location. Al-Ṭabarī reads the pair of verses as answering the same implicit claim from two directions — the man on land who says the sea lesson does not apply to him, and the man at sea who assumes the danger has passed. The verb *yuʿīdakum fīhi tārah ukhrā*, He returns you to it another time, is significant: the danger is not a single event but a recurring condition, and the human being returns to it voluntarily, for trade and travel.

The verb *qāṣifan*, used of the wind, denotes a wind that breaks and destroys what it strikes, and al-Qurṭubī contrasts it with the favorable wind of verse 66 — the same element that carried the ship now breaks it. The verse thereby completes the point made at verse 66: the favor was not a natural constant, and its withdrawal is equally within the same governance.

The final clause is the most striking in the passage: *thumma lā tajidū lakum ʿalaynā bihi tabīʿā*. The word *tabīʿ* is from the root meaning to follow, and it denotes one who pursues a claim — an avenger, or in the language of law, a claimant who follows up a debt. The verse is therefore stating, in the most concrete legal image available, that there is no recourse: no one will take up your case against God, no one will pursue the matter on your behalf. Al-Rāzī explains that this is the removal of the last comfort, since a person in extremity may give up on safety and still hold on to the expectation of vindication.

The theological content of that clause is the sovereignty the entire sūrah has been establishing. If there is no *wakīl* and no *tabīʿ*, then there is no court above this one and no party with standing to appeal — which is precisely what *tawḥīd* means in practice rather than in formula. 40:16 states the same reality from the other side: *“...and the judgment today belongs to God, the Exalted, the Great.”*

The pastoral reading of the pair of verses is what has made them matter to readers. They are not a threat of arbitrary destruction; they are a correction of a specific illusion — that safety is somewhere. The man who stops looking for it in geography begins to look for it in the One who governs the geography, and 65:3 gives the answer that the search is meant to reach: *“And whoever relies upon God, He is sufficient for him.”*"""),

70: ("**Karramnā: A Dignity That Is Given, Not Achieved**",
"""This verse is the Qur’an’s most explicit statement of human dignity, and its grammar is what gives it force. The particle *laqad* combines the oath-particle with the perfect, producing an emphatic assertion: *wa laqad karramnā banī Ādam* — and We have indeed honored the children of Adam. The verb *karrama* is from the intensive form of the root *k-r-m*, and it denotes honoring in a way that confers status rather than merely praising. The honor is stated as a completed divine act, not as a quality the human being earns, and the consequences of that grammatical fact run through the whole of Islamic ethics.

The four gifts enumerated are specific. Carriage on land and sea — *ḥamalnāhum fī al-barr wa al-baḥr*, We carried them, the same verb of being made to travel used of the ship at verse 66, which ties the honor to the argument just made: the danger of the sea is the same governance as the honor of the voyage. Provision of good things — *wa razaqnāhum min al-ṭayyibāt*, of the pure and wholesome, not merely of the available. And preferment — *wa faḍḍalnāhum ʿalā kathīrin mimman khalaqnā tafḍīlā*, We preferred them over much of what We created, with a marked preference, the cognate accusative *tafḍīlā* intensifying the verb as *ʿuluwwan kabīrā* did at verse 43.

The word *kathīr* — much, many — rather than *jamīʿ* or *kull* has been the subject of extensive comment. Al-Qurṭubī and al-Rāzī discuss the two readings it permits: that the human being is preferred over much of creation but not over all, the angels being excepted in one view; or that the preference is comprehensive and the word *kathīr* is used in a general sense. The disagreement matters less than what both readings share, which is that the preference is a divine act with a stated ground — and the Qur’an states that ground at 2:30–33, where Adam is given the *names* and the angels are asked to produce them and cannot. The honor is therefore rooted in the capacity for knowledge.

The commentators enumerate its visible forms. Al-Qurṭubī lists the upright posture, which frees the hands and lifts the face; speech and its articulation; writing, by which knowledge crosses generations; the hand capable of craft; and reason itself. 95:4 states the same doctrine in a single phrase: *“We created man in the best of forms (fī aḥsani taqwīm).”* And 2:31 supplies the ground: *“And He taught Adam the names, all of them.”*

The ethical consequences have been drawn from this verse for fourteen centuries, and they are worth stating because the verse is often quoted without them. Dignity is not conditional on virtue, usefulness, belief, or capacity, since the honor was conferred on *banī Ādam* — the children of Adam — as a class, before any of them had done anything. This is the scriptural ground on which Islamic jurisprudence built its protections for the inviolability of life, the prohibition of mutilation even of an enemy’s corpse, the requirement to bury the dead with honor, and the prohibition of selling a free human being. The one who is honored by God cannot be treated as an instrument by man.

The verse’s placement is the final point, and it is deliberate. It follows the argument that no created being has authority over the servant of God, and it precedes the account of the gathering on the Day of Resurrection at verse 71. The dignity conferred is real and it is not the end of the matter: the honored being is still summoned, still questioned, and still answerable. The Qur’an’s anthropology holds both without collapsing either — 95:4–6 states them in two consecutive verses, the best of forms, and then the return to the lowest of the low, except those who believe and do righteous deeds."""),
}
p='expanded/017.md'
s=open(p,encoding='utf-8').read()
parts=re.split(r'(?m)^(## Sūrah al-Isrāʾ 17:\d+)$', s)
d={int(parts[i].split(':')[1]):[parts[i],parts[i+1]] for i in range(1,len(parts),2)}
for n,(h,t) in ADD.items():
    body=d[n][1]
    hs=[m.start() for m in re.finditer(r'(?m)^\*\*(?!Expanded Commentary).+?\*\*$', body)]
    assert hs, n
    ins=hs[-1]
    d[n][1]=body[:ins]+'**'+h+'**\n\n'+t.strip()+'\n\n'+body[ins:]
out=[parts[0]]
for i in range(1,len(parts),2):
    n=int(parts[i].split(':')[1]); out.append(d[n][0]); out.append(d[n][1])
open(p,'w',encoding='utf-8').write(''.join(out))
print('added',len(ADD),'| words now',len(''.join(out).split()))
