# -*- coding: utf-8 -*-
"""Regenerated commentary for Sūrah al-Anbiyāʾ (21), verses 20-25.

Profile matched to the file's own healthy sections: 3 mini-headings, 3 paragraphs
each, ~130 words per paragraph, ~1,250 words per section.
Grounded in the note apparatus of initial/021.md (T = al-Tabari, Q = al-Qurtubi,
R = al-Razi, Su = al-Sulami, IK = Ibn Kathir).
"""
SURAH = "al-Anbiyāʾ"
NUM = 21

SECTIONS = {

20: (None, [
 ("Glorification Without Interval", [
  "Verse 19 established that the beings with God are neither arrogant nor weary; verse 20 states what they do in place of both. *Yusabbiḥūna al-layla wa-l-nahāra lā yafturūn* — \"They glorify night and day, without tiring.\" The pairing of night and day is not decorative. It is the Qur'an's standing idiom for unbroken duration, and it forecloses at the outset the assumption that worship must be interrupted by sleep, by boredom, or by the pull of competing concerns. Human worship is necessarily punctuated; the verse describes a worship that is not, and it does so in order to establish a measure against which the worship described four verses later can be assessed.",
  "The verb *yusabbiḥūna* is the intensive form, and its sense is not merely that they praise but that they declare God free of deficiency. What the angels are doing, on the classical reading, is not accumulating merit through repetition but continuously asserting the transcendence of the One they worship. That distinction matters for what follows, because the sūrah is about to contrast this worship with the worship of stones, and the contrast is not between more and less of the same operation but between two entirely different kinds of thing — one an act of recognition, the other an act of projection.",
  "Al-Ṭabarī preserves an observation that gives the image its force: for the angels, the glorification of God is what breathing is for human beings. Breathing is not an act one performs between other acts; it is the condition of performing any act at all. The analogy therefore does not say that the angels praise God frequently or even constantly in the sense of a long sequence of discrete acts. It says that praise is their mode of existence, as involuntary and as sustaining as respiration, and that to cease would not be to stop an activity but to stop being what they are. Worship, for them, is not something they do.",
 ]),
 ("Why the Angels Cannot Weary", [
  "Al-Rāzī draws out the theological consequence that al-Ṭabarī left implicit. Not tiring and not becoming bored is possible only for angels, not for human beings. The distinction is worth pausing on because it prevents the verse from becoming an impossible demand addressed to the reader. Human worship is intermittent by constitution, and the Qur'an nowhere asks it to be otherwise; what it asks is that the intervals be filled with something other than a rival object of worship. The verse describes an ideal that is constitutively unavailable to human beings precisely so that no human being will be measured against it.",
  "There is a second implication, and it concerns the object rather than the worshipper. Fatigue in worship arises when the object is limited — when one has exhausted what there is to say about it, or when the saying ceases to disclose anything new. The angels' indefatigable praise is thus evidence about its object rather than about them: they do not tire because there is no bottom to what they are praising. A finite object would produce boredom in an immortal worshipper within a finite time, and the absence of boredom is therefore a report about infinity rather than about angelic stamina.",
  "It is also worth noticing that al-Ṭabarī glosses *nor do they weary* as meaning that they neither tire nor become bored. The two are different failures. Tiring is a failure of capacity; boredom is a failure of interest. Human worship is vulnerable to both, and the second is the more insidious because it can persist in a body that is not exhausted — a person may continue the forms of worship long after they have ceased to disclose anything. By naming both and denying both of the angels, the verse identifies worship's two characteristic decay modes and locates their remedy in the inexhaustibility of the object.",
 ]),
 ("The Contrast the Verse Is Building", [
  "The sūrah has been assembling an argument, and verse 20 is the final piece before it turns. Verses 19–20 describe worship that is continuous, ungrudging, and untiring. Verse 21 then asks a single question — *Or have they taken gods from the earth who resurrect?* — and the force of that question depends entirely on what has just been said. The beings nearest to God worship without ceasing; the gods taken from the earth cannot even give life. The commentators connect this to 41:38, where the same refusal of arrogance and weariness is attributed to those near God, and the recurrence across sūrahs is not accidental.",
  "The rhetorical movement is deliberate and worth attending to, because the sūrah does not begin by attacking the idols. It first establishes the standard of worship among the highest created beings, so that the worship of stones appears not merely false but beneath the dignity of the worshipper. Verse 20 supplies the measure against which verse 21's question is asked, and without it the question would be a bare assertion. An idol is precisely the kind of object that produces boredom, because there is nothing in it to keep disclosing, and the verse has just described a worship in which boredom is impossible.",
  "This ordering is characteristic of the sūrah's method throughout. It establishes what is true before it names what is false, and it does so by appeal to what the audience already accepts rather than to what they must be persuaded of. The Meccan audience did not dispute that the angels worship God; the verse takes that as common ground and then asks what follows from it. The argument is therefore not an appeal to authority but an inference from a premise the audience has already granted, which is why the sūrah can afford to state it in a single clause.",
 ]),
]),

21: (None, [
 ("A Single Question", [
  "*Am ittakhadhū ālihatan mina'l-arḍi hum yunshirūn.* The verse is a question, not an assertion, and its brevity is the point. After nineteen verses establishing God's ownership of the heavens and the earth and describing the ceaseless worship of the angels, the sūrah compresses its whole critique of idolatry into one clause: have they taken gods *from the earth* who *resurrect*? Two words carry the argument. *From the earth* fixes the origin of these gods — they are not descendents from the heavens, not even fallen ones, but products of the ground, quarried and carved by the people who then worship them.",
  "*Who resurrect* fixes the test — the one function that a god must be able to perform and that no idol has ever been observed to perform. The verse does not need to state the conclusion because the two words already contain it. The interrogative *am* introduces a question that expects a negative answer, and this is a standard feature of Qur'anic rhetoric. It does something a flat assertion could not: it places the burden of response on the hearer. The verse does not say *your gods cannot resurrect*; it asks whether they can, and leaves the audience to supply the answer they already know but have not spoken.",
  "There is also an implicit irony in the phrase *from the earth*. The idols were made of earth by human hands, and the verse asks whether things made from the ground can restore life to the ground. The materials of the idol and the materials of the corpse are the same. Whatever agency is required to reverse death is therefore not resident in the stone, and the verse's choice of vocabulary makes that visible without needing to argue it. The audience is being asked to notice something about the physical composition of the objects in front of them.",
 ]),
 ("The Argument al-Qurṭubī Draws Out", [
  "Al-Qurṭubī's note is economical: rather than worship the Creator of the heavens and the earth, such people prefer to worship earthly beings incapable of giving life. The word *prefer* is important, because it identifies the choice as a preference rather than a conclusion. Nobody arrives at the worship of a stone by reasoning; people arrive at it by inheritance, by social pressure, or by the convenience of a deity that makes no demands. The verse's diagnosis of idolatry is therefore not that it is a mistaken inference but that it is not an inference at all — it is a habit that has never been examined.",
  "The verse's choice of *resurrect* rather than some lesser function is a deliberate selection of the hardest case. An idol can be credited with many things by generous observers — presence, blessing, intercession, ancestral favour. It cannot be credited with raising the dead. The sūrah therefore does not argue about the marginal claims, where reasonable people might disagree about evidence; it goes straight to the one that decides the matter, and on which no evidence has ever been offered by anyone in any generation. The selection of the test is itself part of the argument.",
  "This method has a consequence worth noting. By choosing the hardest case, the verse makes the lesser claims irrelevant. If the gods in question cannot perform the one function that defines divinity, then whatever else they may be credited with does not make them gods. The sūrah does not need to disprove intercession or blessing or presence, because none of those, even if granted, would establish the thing being claimed. The argument is efficient because it targets the load-bearing claim rather than the decorative ones.",
 ]),
 ("Resurrection as the Qur'an's Recurring Test", [
  "The source commentary notes that biological life renewed is treated throughout the Qur'an as a symbol of the Resurrection, and cites 35:9: God sends the winds, they raise clouds, the clouds are driven to a dead land, and the earth is revived after its death — *thus shall be the Resurrection*. The argument is not that the two events are alike in mechanism but that both display the same impossible transition: from nothing to something, from death to life. What makes the annual revival probative is not its similarity to resurrection but its demonstration that the transition is possible at all.",
  "This is why the question is phrased as it is. The Meccan audience already accepted that the earth is revived annually; the observation required no persuasion. The verse asks them to apply an observation they already grant to the deity they have chosen. If the revival of a dead land requires the Creator of the heavens and the earth, then a god taken from the earth cannot be the one performing it. The sūrah returns to this argument at verse 30, where the rending asunder of the heavens and the earth is followed by *And We made every living thing from water*, and then by *Will they not, then, believe?*",
  "The verse presupposes something its audience would not have disputed: that a god is defined by what it can do, not by what it is called. This is worth stating because much of the surrounding polemic assumes the opposite — that divinity is a matter of designation, of ancestral practice, of the name a community has given an object. By asking whether these gods resurrect, the sūrah shifts the entire ground of the debate from designation to capacity. Once that shift is made the outcome is settled, because the capacity in question has never been observed in any idol, and verse 24 makes the shift explicit by demanding *Bring me your proof!*",
 ]),
]),

22: (None, [
 ("The Logical Argument", [
  "*Law kāna fīhimā ālihatun illa'Llāh la-fasadatā.* \"Were there gods other than God in them, they would surely have been corrupted.\" This is one of a small group of verses that argue the impossibility of a plurality of gods as a matter of logic rather than revelation. The commentators place it alongside 12:39–40, where Joseph asks his fellow prisoners whether diverse lords are better than God the One, the Paramount, and 23:91, which reasons that if there were other gods each would take away what it created and some would overcome others. The argument runs from the observable order of the world to the unity of its source.",
  "The heavens and the earth display a single coherent system: one set of physical regularities, no interruption, no negotiation between competing agencies, no region of the cosmos governed by different rules. A plurality of sovereigns would produce exactly the interruption that is not observed. Al-Rāzī develops this as a demonstration rather than a rhetorical flourish, and 17:42 makes the same point from the opposite direction — if there were gods with Him, they would seek a way unto the Possessor of the Throne. The evidence offered is the persistence of the world, which is available to anyone without prior instruction.",
  "It is worth being precise about what the argument does and does not establish. It does not demonstrate the existence of God from the order of nature; the sūrah takes that as already granted by its audience. It demonstrates the *unity* of the source of that order, on the ground that a plurality of independent sovereigns would produce competition, and competition would produce the disorder that is absent. The verse is therefore an argument within theism rather than an argument for it, which is why it can be made so briefly — it is completing a case rather than opening one.",
 ]),
 ("The Grammar That Carries the Formula", [
  "The source commentary notes that *illa'Llāh* can be rendered either \"other than God\" or \"except for God,\" and that the second reading reproduces the second half of *lā ilāha illa'Llāh*. This is not a curiosity. It means the verse's central clause is structurally identical to the declaration of faith, so that the logical argument and the creedal formula are the same sentence in two registers — one stating a conditional about the world, the other stating a commitment. The verse thereby shows that the creed is not an arbitrary formula but a compressed statement of the demonstration just given.",
  "The commentary also notes that *fīhimā* — \"in them\" — uses a dual pronoun referring to the heavens and the earth. The duality is significant. The verse takes the two most comprehensive domains of created existence and asserts that neither contains a competing god. There is no third domain in which such a god could be located, and no gap in which it could hide. The dual form closes off the evasion available to a polytheist who might grant that the heavens belong to God while reserving the earth, or the reverse.",
  "The conditional *law kāna* is counterfactual, and its counterfactuality is doing real work. The verse does not say that there are other gods who happen to be well behaved; it says that if there were, the heavens and the earth would have collapsed. The observable persistence of the world is therefore offered as the evidence for the conclusion, which is why the argument can be made to an audience that has never read a philosophical text. What is required is not technical training but the willingness to notice that the world has not fallen apart.",
 ]),
 ("Al-Sulamī's Reading and the Verse's Close", [
  "The note records that al-Sulamī reads the verse as an allegory of the heart: a divided heart will become corrupted, and a heart must be unified and detached from entanglements in the world. On this reading *fa-sadatā* — \"they would surely have been corrupted\" — describes not a cosmological collapse but the disintegration of an interior life divided between competing objects of ultimate concern. The allegory preserves the logical structure of the verse rather than replacing it: what makes a plurality of gods impossible in the cosmos is what makes a plurality of ultimates destructive in a person.",
  "The practical consequence is not abstract. A person with two ultimate concerns does not experience them as a stable compromise; they experience the conflict between them as corrosion. Al-Sulamī's gloss identifies that corrosion as the same phenomenon the verse identifies in the heavens and the earth, and it thereby makes the verse available as a diagnosis of ordinary interior experience rather than only as a proposition about metaphysics. The commentators do not treat these as two separate meanings but as one truth at two scales, and the spiritual reading depends on the cosmological one for its force.",
  "The verse closes with *fa-subḥāna'Llāhi rabbi'l-ʿarsh ʿammā yaṣifūn* — \"So glory be to God, Lord of the Throne, above that which they ascribe.\" The formula *subḥānahu* is the Qur'an's standard marker that a preceding statement has attributed to God something incompatible with His nature, and its appearance here signals that the plurality just refuted was not a neutral hypothesis but an indignity. The title *Lord of the Throne* completes the argument by naming the sovereignty the hypothetical plurality would have displaced: the gods they ascribe are not additions to God but replacements for Him.",
 ]),
]),

23: (None, [
 ("Asymmetry of Answerability", [
  "*Lā yus'alu ʿammā yafʿalu wa-hum yus'alūn.* \"He shall not be questioned about what He does, but they shall be questioned.\" Al-Rāzī states the point plainly: God is not answerable to creation, but creatures are answerable to Him. The verse does not argue for this asymmetry; it announces it, and the announcement is itself part of the argument, since a being who could be called to account by his creatures would not be sovereign over them. The symmetry of the sentence is exact — the same verb, negated in the first clause and affirmed in the second — and that exactness is the verse's method.",
  "The source commentary notes that the idea of questioning in the sense of responsibility also arises at verse 13 of this sūrah and at 2:119, 2:134, and 16:56. The recurrence matters. The Qur'an returns repeatedly to the theme because it is the point at which divine sovereignty and human moral seriousness meet, and neither can be surrendered without losing the other. A God who must justify Himself is not sovereign; a creature who is never questioned is not moral. The verse holds both halves together in a single balanced sentence precisely because separating them produces one of these two errors.",
  "It is worth noting what the verse does not say. It does not say that God's acts are arbitrary, nor that human questioning is worthless in every context. It says that God will not be questioned about what He does, which is a statement about the direction of accountability rather than about the availability of reasons. The distinction is preserved in the commentators' glosses and is often lost in summary, where the verse is read as forbidding inquiry rather than as describing a relation in which inquiry runs one way.",
 ]),
 ("Can One Ask God Why?", [
  "Al-Qurṭubī and al-Rāzī both connect the verse to teleology — whether human beings may ask God why He did such and such. The commentary offers an alternative rendering that sharpens the issue: *He is unanswerable for what He does, but they are answerable*. Under this reading the verse is not forbidding a question but stating a structural fact about the difference between created and uncreated agency. Al-Rāzī identifies the theological stake precisely: with created things one can ask why they acted as they did, because they act from motives and causes that are in principle inspectable.",
  "It is by definition impossible for creatures to know why God does what He does, and what is at stake is whether God stands in need of a reason outside Himself in order to act. If He did, that reason would be prior to Him and would be the true sovereign. The verse's asymmetry is therefore a consequence of divine unity rather than an assertion of arbitrary power — the same unity argued in the preceding verse from the coherence of the cosmos. This connection is easy to miss because the two verses look like different topics, one about the structure of the world and one about accountability.",
  "They are the same argument. A single unconditioned source is what makes the world coherent and what makes creatures answerable rather than the reverse. Al-Qurṭubī records that the issue of free will versus predestination arises here, in that human beings cannot, on a strictly predestinarian reading, question God or ask why one was made a disbeliever in life. The commentary links this to *God provides for whomsoever He will without reckoning*, understood by some to mean that no one can bring God to account for the provisions He gives or withholds. The verse does not resolve the tension, and the commentators do not pretend that it does.",
 ]),
 ("\"But They Shall Be Questioned\"", [
  "The second half of the verse receives less attention than the first and deserves more. *Wa-hum yus'alūn* — \"but they shall be questioned\" — is the verse's pastoral content, and it is not a threat so much as a statement that human action matters. If creatures were never questioned, nothing they did would have consequence, and the moral seriousness the Qur'an insists upon throughout would be unfounded. The clause is therefore the ground of human significance rather than a limit upon it.",
  "Within the sūrah's argument the clause completes the movement begun at verse 21. There the audience was asked whether their gods resurrect; here they are told that they themselves will be asked about their answer. The sūrah does not leave the question rhetorical. It converts the demand for proof at verse 24 into a demand that will be made again, under different circumstances, at a time when evasion is no longer available. The pairing has a rhetorical function as well as a theological one: it answers the objection that the argument is merely intellectual by observing that it will be put to the hearer personally.",
  "What the commentators leave open is how the two halves are to be held together in practice. The verse does not say that the impossibility of questioning God absolves the questioner of responsibility for his own acts; it says the opposite. The asymmetry is not a licence but a specification of where the examination will fall. Verse 24's *Bring me your proof!* is thus not a debating challenge but an advance notice, and verse 23 is the reason it can be issued with confidence rather than as a rhetorical gesture.",
 ]),
]),

24: (None, [
 ("The Demand for Proof", [
  "The verse returns to the question posed at verse 21 — *Or have they taken gods apart from Him?* — and this time it does not leave the question rhetorical. It converts it into a demand: *Say, \"Bring me your proof!\"* The Qur'an's use of *burhān* here is technical. The source commentary notes that *burhān* means a demonstration or evidence, and that the word is used in the same sense at 2:111, 23:117, 27:64, and 28:75. The word choice specifies the kind of thing that would satisfy the demand, and the specification is one that ancestral practice cannot meet.",
  "This is a striking move in a text often characterised as demanding submission. The verse does not say *believe because I say so*; it says *produce your demonstration*. It places the burden of argument on the party making the positive claim — that there are gods besides God — and it identifies that burden as one the claimants have never attempted to discharge. The demand is not rhetorical precisely because it has never been met, and its force lies in that fact rather than in any expectation that a demonstration will now be forthcoming.",
  "The instruction *Say* places the demand in the Prophet's mouth rather than in the text's narrative voice, which makes it a public challenge rather than a private reflection. The audience is being addressed directly and is being asked for something specific. This is the sūrah's method at its most explicit: not to assert the absurdity of idolatry but to invite its adherents to state their case, on the confident expectation that no case exists to be stated. The confidence is not arrogance but the result of a demand that has been outstanding since the first messenger.",
 ]),
 ("Two Reminders", [
  "*This is the Reminder for those who are with me, and the Reminder for those before me.* The word in both instances is *dhikr*, which the commentary notes can mean invoke, mention, recall, remembrance, or even renown. The double occurrence is deliberate: the Prophet ﷺ is told that his own revelation is continuous with what preceded it, not a departure from it, and the continuity is stated twice rather than once so that no reader can take it as incidental. The verse is answering an objection before it is fully voiced.",
  "Al-Rāzī and al-Ṭabarī record two readings. On the first, *Reminder for those before me* refers to the fact that the Qur'an recounts the lives of peoples who passed away, and would be rendered \"Reminder *of* those before me.\" On the second, it refers to the Torah and the Gospel, whose content — like that of the Qur'an — is that human beings should not take gods apart from Him, a point the source commentary notes is reaffirmed at verse 25. Both readings serve the same argumentative purpose, and the commentators record both without adjudicating between them.",
  "That purpose is to establish that the demand for proof is not a novel challenge invented by this messenger but the standing challenge of every messenger, with the earlier scriptures cited as witnesses to it. This answers in advance the objection most natural to an audience that reveres earlier revelations — that the Prophet ﷺ is asking for something no prophet ever asked. By invoking the Torah and the Gospel as containing the same demand, the verse turns the audience's own respect for prior revelation into support for the challenge being made.",
 ]),
 ("Why They Turn Away", [
  "The verse ends with a diagnosis rather than a conclusion: *Nay, but most of them do not know the truth; so they turn away.* The sequence is important. The turning away is not presented as a considered rejection of evidence but as a consequence of not knowing. The commentators read this as an explanation of the demand for proof in the first clause: one asks for a demonstration from people who have never been asked to provide one, and who have therefore never examined what they hold. The ignorance is not culpable in the first instance; it is inherited and unexamined.",
  "The diagnosis is charitable in a way that is easily overlooked. The verse does not say that they turn away because they are wicked or because they have seen the truth and refused it. It says that they do not know, and that the turning away follows from the not knowing. That is a different claim, and it leaves open the possibility that examination would change the outcome — which is precisely why the demand for proof is issued rather than a verdict pronounced. A polemic against deliberate rejection would look quite different from this.",
  "The verse also establishes something about the structure of religious claims worth stating explicitly. The party asserting the existence of gods besides God bears the burden of proof and has never discharged it; the party denying it does not bear a corresponding burden, because a denial of this kind is not a positive claim requiring evidence. This is why the sūrah can move from the demand at verse 24 to the statement at verse 25 without any gap. Verse 25 does not offer proof of monotheism; it states that every messenger was given the same message. The burden has been placed and remains where it was placed.",
 ]),
]),

25: (None, [
 ("One Message, Many Messengers", [
  "*And We sent no messenger before thee, save that We revealed unto him, \"Verily, there is no god but I; so worship Me!\"* Al-Ṭabarī's note identifies the verse's precise claim: even though the messengers had different commands regarding what was obligatory and forbidden, they all conveyed the same message of monotheism and devotion to God. The distinction is essential to the verse's logic and is frequently lost in summary. The sūrah is not saying that all religions have the same law; it is saying that all revelation has the same first principle, and that the law varied while the principle did not.",
  "Al-Qurṭubī adds that this confirms the self-evident existence and Oneness of God. The phrase *self-evident* does real work here. If tawḥīd required demonstration in each generation, it would be a discovery rather than a reminder; the verse's insistence that every messenger received it as revelation implies that it is being restored rather than invented, and that the need for restoration is a fact about human forgetfulness rather than about the obscurity of the truth. The verse's grammar enacts the point by giving the revealed words in the first person.",
  "Because the words are *there is no god but I; so worship Me*, every messenger speaks the same sentence in the same voice. The variation lies entirely in the law that accompanies it, and the verse is explicit that the variation was real — the messengers had different commands regarding what was obligatory and forbidden. What did not vary is the object of worship or the requirement that He be worshipped. The commentators direct the reader to the essay \"The Quranic View of Sacred History and Other Religions\" on these fundamental similarities among the messages and messengers.",
 ]),
 ("The Grammatical Variant and Its Effect", [
  "The source commentary records that some read part of the verse in the third person: *We sent no messenger before thee, but that it was revealed unto him*. The variant shifts the address from the Prophet ﷺ to a general statement about prophethood, and in doing so removes any suggestion that the second-person address singles him out. On either reading the content is identical; what changes is whether the verse is heard as reassurance to one man or as a description of the office he holds. Both readings are recorded without preference.",
  "Both support the argument the sūrah has been making since verse 21. The demand for proof at verse 24 was not a personal challenge but the standing challenge of every messenger, and verse 25 establishes that standing by tracing it to the origin of the office itself. The third-person reading makes this more visible by removing the personal address altogether and leaving only the structure of the office. The second-person reading has a pastoral use: it comforts a man being told that he has brought something unprecedented.",
  "The variant therefore does not create a difficulty but supplies two registers of the same claim. Read in the second person, the verse reassures; read in the third, it demonstrates. The sūrah needs both, because the audience's objection has both a personal and a general form — that this particular man is out of step with his ancestors, and that his message contradicts what came before. The first objection is answered by the reassurance, the second by the genealogy.",
 ]),
 ("Worship as the Consequence of Tawḥīd", [
  "The revealed sentence has two halves joined by *fa-* — *there is no god but I; so worship Me* — and the conjunction indicates consequence rather than mere sequence. Worship follows from the recognition of unity; it is not an additional requirement laid on top of it. This is the same structure al-Sulamī identifies at verse 22, where the unity of God and the unity of the heart are the same truth at two scales. The verse therefore does not present monotheism as a proposition to be assented to and worship as a separate obligation, but as one movement issuing in the other.",
  "The messengers differed in what that worship required in detail; they did not differ in the fact that it followed from the recognition. Read against the preceding verses, this explains why the sūrah treats idolatry as an intellectual error rather than merely a ritual one. The failure at verse 21 and verse 24 is a failure to recognise unity, and the worship of stones is its consequence. Verse 25 states the correct order so that the incorrect one can be seen as a reversal of it rather than as an independent choice.",
  "The verse closes one argument and opens another. It answers the claim that the Prophet ﷺ has brought something unprecedented by showing that his message is the oldest there is, and it then sets up verse 26, which records a specific departure from that message: *And they say, \"The Compassionate has taken a child.\"* The juxtaposition is the point. Verse 25 states what every messenger was given; verse 26 states what some have said against it. The verse is not a claim that all religious traditions as currently practised are equivalent, but a claim about what was originally revealed to each — which leaves open the question of what has been preserved, the question the sūrah pursues next.",
 ]),
]),

}
