# -*- coding: utf-8 -*-
"""011.md vv 94, 96, 97, 98 -- rewrites grounded in initial/011.md, initial/007.md, initial/010.md.

v94 is the third occurrence of one formula in the surah; the source note directs the
reader to 11:66-68 and pairs Midian with Thamud at v95 (cf. 7:91-92c).
v96: signs = miracles (Kl), also called clear proofs (7:105; 29:39); some read the
manifest authority as Moses' staff specifically (Q).
v97: the notables were dignitaries of the highest social standing (IT, Qm, Th);
the apparatus adds no gloss on 'was not sound'.
v98: wird, watering place, normally quenching thirst, hence the severity (Z);
cf. 17:71, every people called by their imam.
"""

SURAH = "Hūd"
NUM = 11

SECTIONS = {

94: (None, [
 ("The Third Occurrence of One Formula", [
  "This is the third time in the sūrah that a prophet's story ends in the same four movements. The command comes. The believers are saved through a mercy. The cry seizes the wrongdoers. Morning finds them lifeless in their homes. The commentators' note on these two verses says as much in terms: for identical wording in the story of Ṣāliḥ — the coming of the command, the role of mercy in the salvation of the believers, the cry seizing the wrongdoers, morning finding them lifeless as though they had never dwelt there — see 11:66–68. The formula had already appeared for Thamūd. It had appeared for the people of Lot. Now it closes Midian.",
  "The repetition is the sūrah's method. Three peoples in three different places, separated by centuries, destroyed by three different means — an earthquake, an overturning, a cry — are nevertheless narrated in the same words. The reader is being told that the variation in the punishment is incidental and the pattern is not. Each community believed itself particular. The sūrah's prose refuses to let the reader believe it."]),
 ("Mercy as the Ground of Salvation", [
  "The verse says the believers were saved through a mercy from Us. It does not say they were saved because they had been righteous, or because their belief was sound, or because they had outlasted the opposition. The ground of the salvation is named as mercy. The same formulation appeared at 11:66 for Ṣāliḥ's believers and at 11:58 for Hūd's.",
  "This matters in a sūrah about punishment. The destruction of the wrongdoers is presented as the consequence of what they did; the salvation of the believers is presented as a gift. The two are not symmetrical, and the verse does not make them symmetrical. Shuʿayb had argued for eighty verses that reform was possible and that his people's ruin was not yet fixed. They refused the possibility. Those who accepted it were then saved by something other than their own merit, and the verse says so in the plainest available terms."]),
 ("The Cry and the Single Night", [
  "The cry seized those who did wrong, and morning found them lying lifeless in their abode. The commentators read the verb *aṣbaḥū* — they became in the morning, morning found them — as indicating that the destruction occurred within a single night, and that morning disclosed what had happened rather than causing it. The same reading applied at 11:67 for Thamūd and at 11:94's parallel.",
  "The pattern is exact. Shuʿayb warned them. They answered with contempt and drove the believers out of the city. The cry came. By morning the argument was over and the city was full of the dead. Nothing intervened — no siege, no famine, no gradual decline. The speed is part of the account's claim about the kind of event this was."]),
 ("The Pairing with Thamūd", [
  "The next verse draws the comparison explicitly: Away with Midian, just as Thamūd was done away. The commentators note that the two peoples' fates were so similar that the sūrah states the equivalence outright, and they direct the reader to 7:91–92, where the same pairing appears. Both were destroyed by a cry. Both were found lifeless by morning. Both were described afterwards as though they had never dwelt in their homes.",
  "The comparison is not incidental ornament. Thamūd had been the more famous of the two — a people with a recognised name, a known territory, monuments cut into rock. Midian had been a trading town on a route. To say that Midian went as Thamūd went is to say that fame and obscurity made no difference to the outcome, and that the sūrah's catalogue treats the great and the small by one standard.",
  "The commentators direct the reader to 7:91–92 for the same pairing, where the earthquake takes Thamūd and the account of Shuʿayb closes with a comparable formula. That the two sūrahs make the same comparison independently is worth noting: it is not a local device of Hūd but a settled way of reading the two stories together. The sūrah is not inventing the link between Midian and Thamūd; it is stating a connection the tradition already recognised and giving it a place in the sequence."]),
 ("What the Verse Does Not Say", [
  "The verse does not say how many of Shuʿayb's people believed, and does not name any of them. It does not describe the cry — its source, its sound, its duration — and does not say whether the believers heard it and were unharmed or whether they were spared by other means. It does not say where the survivors went, and does not record Shuʿayb's own end. The commentators note only that the mercy is named as the ground of the salvation.",
  "The verse also does not say that the punishment was proportionate to the crime in any measurable sense. It presents the sequence — warning, refusal, destruction — and leaves the reader to draw the conclusion the sūrah has been building for eighty verses. Shuʿayb's grief at v93 is the last word from him in the narrative, and after it the account moves on without comment."]),
]),

96: (None, [
 ("The Fourth Prophet in the Series", [
  "The sūrah has now carried three complete prophetic cycles — Noah, Hūd, Ṣāliḥ — and has begun a fourth with Lot, whose story closed at v95 with the destruction of Midian. This verse opens the fifth. The commentators list the parallel accounts at length: 2:49–61, 7:103–55, 10:75–93, 20:9–97, 26:10–66, 28:3–46, and 79:15–25. Moses is the most narrated prophet in the Qur'an, and this sūrah's treatment of him is the shortest of the major accounts.",
  "The placement is deliberate. The four preceding prophets were each sent to a single named community and each community was destroyed. Moses is sent to a ruling power. The sūrah is moving from the pattern of a prophet and his town to the pattern of a prophet and a state, and the difference will show in how the story ends.",
  "The brevity of this account relative to the others is itself a feature. At 7:103–55 the story runs for fifty-three verses; at 20:9–97 for eighty-nine; at 26:10–66 for fifty-seven. Here it occupies a handful. The sūrah is not retelling the story but citing it — the reader is expected to know what happened, and the sūrah takes only what it needs for the argument it is making about leadership and its consequences. That argument reaches its conclusion two verses later, which is why the narrative is compressed to the point where the signs are named but never described."]),
 ("The Signs", [
  "Moses is sent with Our signs. The commentators gloss the signs as the miracles he performed (Kl), and note that the same thing is elsewhere called clear proofs — at 7:105 and 29:39. At 10:75 the commentators add that the signs include Moses' hand and his staff (Mu).",
  "This is the first prophet in the sūrah to be sent with demonstrable signs. Noah was sent with a message. Hūd was sent with a message. Ṣāliḥ was sent with a message and a she-camel, which was itself a sign but a standing one rather than a performed one. Lot was sent with a message. Moses arrives with things that can be shown, and the sūrah's account of what follows will turn on whether showing them persuades.",
  "The apparatus at 10:75 identifies the signs more concretely as including Moses' hand and his staff (Mu), and the same verse notes that they are elsewhere called clear proofs (29:39). The vocabulary matters: a sign is something that points, and a clear proof is something that points unmistakably. The sūrah's insistence on the clarity is what makes the refusal that follows significant, since the objection cannot be that the evidence was obscure."]),
 ("The Manifest Authority", [
  "Alongside the signs, Moses is sent with a manifest authority — *sulṭān mubīn*. The commentators record that some take this to refer to Moses' staff specifically (Q), and direct the reader to 7:106–8 for the account of the staff. Others read it more broadly as the warrant for his mission.",
  "Both readings are preserved. On the narrower reading the authority is the same object as one of the signs, and the phrase singles it out as the sign that carried the commission. On the broader reading the authority is the commission itself — the standing behind the messenger — and the signs are its evidence. The verse does not decide between them, and the commentators do not decide for it.",
  "The word *sulṭān* carries a sense of rightful power rather than mere force, which is why it suits a commission. Pharaoh holds power in the ordinary sense; Moses is sent with authority in the sense of warrant. The sūrah sets the two against each other in the verses that follow, and the outcome turns on which kind of power proves durable. The phrase also anticipates the next verse's verdict on Pharaoh's own command — that it was not sound — since an authority grounded in warrant and a command grounded in position are being measured against the same standard."]),
 ("A Different Kind of Opposition", [
  "The verse names Moses' audience as Pharaoh and his notables. The commentators explain at 10:75 that the notables in Pharaoh's entourage were a group of dignitaries who held the highest social standing in Egyptian society (IṬ, Qm, Th), and at 7:103 that the opposition to each of the preceding prophets had likewise been led in part by the notables among the people to whom he was sent.",
  "The continuity is worth marking. In every case so far the resistance came from those with most to lose. The sūrah has been consistent that the argument was never primarily about the truth of the message but about the standing of those who would have to accept it. Pharaoh's case will be the sharpest version of the pattern, because here the notables are not merely prominent citizens but the apparatus of a state."]),
 ("What the Verse Does Not Say", [
  "The verse does not say which signs, and does not describe any of them. It does not say when Moses was sent or to which period of Pharaoh's reign, and it does not name Pharaoh. It does not say how long the mission lasted, and does not yet say what the outcome was.",
  "The verse also does not say that the signs were sufficient to compel belief. It states that Moses came with them, and leaves the question of their effect to what follows. The sūrah's own answer, given at the next verse, is that they were not sufficient — and that the reason was not the weakness of the signs but the disposition of those who saw them."]),
]),

97: (None, [
 ("The Notables", [
  "Moses is sent to Pharaoh and his notables. The commentators explain that the notables were dignitaries holding the highest social standing in Egyptian society (IṬ, Qm, Th), and note at 7:103 that the opposition to each preceding prophet in the sūrah had likewise been led in part by the notables. The same group is addressed at 7:103 and 10:75.",
  "The word does real work in the sūrah's argument. It identifies who in each community actually decided. The mass of the people are rarely addressed directly in these accounts; the prophets speak to those with authority, and it is those with authority who refuse. The pattern is consistent enough across five prophetic cycles that the sūrah can rely on the reader noticing it without stating it.",
  "At 7:103 the commentators add that the notables were guilty of treating God's signs wrongfully — by disbelieving in them (Ṭ, Z) or by turning others away from them (Z) — and of being workers of corruption. The second charge is the more serious of the two. Disbelief is a position; turning others away is an act with consequences beyond the actor. The notables are therefore not merely unconvinced but active, and the sūrah's account of them is an account of people who used their standing to determine what other people were permitted to believe."]),
 ("Following the Command", [
  "But they followed the command of Pharaoh. The verse does not say they were compelled, and does not say they were deceived about what the command was. It says they followed it. At 10:75 the parallel account adds that they waxed arrogant, which the commentators gloss as meaning they were too proud to believe (Mu, My), and cross-reference 40:60: Truly those who are too arrogant to worship Me shall enter Hell debased.",
  "Pride, on this reading, is not a feeling but a posture toward a claim. The notables had standing, and the standing depended on the existing order. To accept Moses would have been to accept that the order rested on something other than their position in it. The commentators' gloss makes the mechanism explicit: the refusal was not a failure to see the evidence but a refusal to occupy the position the evidence would have required.",
  "The cross-reference at 40:60 supplies the consequence: Truly those who are too arrogant to worship Me shall enter Hell debased. The pairing of arrogance with debasement is deliberate, and the following verse in this sūrah enacts it — the one who stood in front of his people will still be in front of them, but the direction will have reversed. The commentators treat the two accounts as describing the same posture from different ends."]),
 ("The Command Was Not Sound", [
  "And the command of Pharaoh was not sound. The verse states this as a fact about the command rather than as a judgement on those who followed it. The apparatus offers no gloss on the phrase beyond the cross-references, so the claim stands on the verse's own wording.",
  "The unsoundness is what the sūrah has been demonstrating for ninety-six verses. A command is sound if it can be followed to a good end. Pharaoh's command led to the Fire, and the next verse says so directly. The sūrah is making a structural point about authority: the test of a command is where it leads, and this one led somewhere that the verse then names."]),
 ("The Repetition of the Name", [
  "The verse says the command of Pharaoh twice — they followed the command of Pharaoh, and the command of Pharaoh was not sound. The repetition is not incidental. It puts the name in the position where an abstract noun would normally sit, so that the reader is left with the man rather than the office.",
  "The commentators do not gloss the repetition, and the verse does not explain it. What it achieves is that the following verse can then say he shall go before his people and lead them to the Fire. The antecedent of that he is unambiguous, and the verse before it has made sure the reader is thinking of a particular person rather than of authority in general.",
  "At 7:103 the parallel account closes with the command so behold how the workers of corruption fared in the end, which the commentators note is addressed to the Prophet — indicating that these prophetic narratives were meant to give him confidence that God aids His messengers against their enemies. The same function operates here. The sūrah is not narrating Pharaoh for its own sake but placing him in a sequence that the reader is meant to apply to the present case: those who refuse a messenger have refused before, and the outcome is on record."]),
 ("What the Verse Does Not Say", [
  "The verse does not say what Pharaoh's command was. It does not record his words, and does not summarise his policy. It does not say how many followed him or whether any refused. It does not say whether the notables agreed with the command or merely complied with it.",
  "The verse also does not say that following an unsound command excuses those who follow it. The next verse holds Pharaoh responsible for leading and his people responsible for being led, and the sūrah nowhere suggests that the second group's culpability is reduced by the first group's initiative."]),
]),

98: (None, [
 ("The Leader Goes First", [
  "He shall go before his people on the Day of Resurrection and lead them to the Fire. The verse takes up the leadership established in the previous verse and carries it past death. Pharaoh commanded, and his people followed; on the Day of Resurrection he will still be in front, and they will still be behind him, and the destination will have changed.",
  "The commentators connect this to 17:71: On the Day We shall call every people by their imam. The word *imām* carries both senses at once — the one who stands in front, and the one whose example is followed. The verse uses the fact that leadership is positional as well as normative: whoever is in front determines where the group goes, and the group's arrival is not independent of the leader's direction.",
  "The verse is also a deliberate reversal of the leadership the preceding prophets exercised. Noah led the believers into the ark. Hūd's and Ṣāliḥ's and Shuʿayb's believers were saved through a mercy, and their prophets stood with them. In each case the leader's direction was toward safety, and the followers arrived where the leader led. Pharaoh is the counter-case: the same structure, the same willingness to follow, and the opposite destination. The sūrah has spent ninety-seven verses establishing that following a prophet is safe, and now shows what following anyone else costs."]),
 ("The Watering Place", [
  "Evil indeed is the watering place to which they are led. The commentators explain that watering place renders *wird*, a word usually associated with the quenching of thirst, and that the choice of it emphasises the severity of the punishment (Z). The thing the led are brought to is the opposite of what the word normally means.",
  "The irony is exact and does not need elaboration. A *wird* is where a traveller arrives after a journey and is relieved. The verse uses the word for arrival-and-relief to name an arrival that is the beginning of punishment. The commentators note the effect rather than explaining the mechanism: the word's ordinary sense is what makes its use here severe."]),
 ("The Inversion of the Shepherd", [
  "The image of a leader conducting his people to a watering place is a familiar one, and it is ordinarily benevolent. The shepherd brings the flock to water. The guide brings the caravan to the well. The verse takes that image and reverses only its destination, keeping everything else — the order, the trust, the following — intact.",
  "What makes the reversal sharp is that the followers' behaviour is unchanged. They are doing what followers are supposed to do. They are behind their leader, going where he goes, expecting what followers expect. The verse does not say they were tricked at the last moment or that they realised too late. It says he led them and they were led, and the place was evil."]),
 ("The Continuity with the Previous Verse", [
  "The two verses work as a pair. Verse 97 says they followed the command of Pharaoh and that the command was not sound. Verse 98 says he will go before them and lead them to the Fire. The unsoundness named in the first verse is given its destination in the second.",
  "The sūrah's argument about authority is therefore complete in two lines. A command is not sound when it leads somewhere evil. Those who follow it arrive where it leads. The leader arrives first and is responsible for the direction; the followers arrive behind and are not excused by the fact that they were following. Both claims are stated without qualification, and the verse does not soften either.",
  "The commentators' note on these two verses adds that the people were pursued in this world by a curse — read either as a curse in general (Z) or specifically as their drowning in the Red Sea (Ṭ; see 7:136). The verse itself does not specify, and the two readings are left open. What both share is that the consequence is not deferred entirely to the Hereafter: something pursued them here, and the leading described in v98 is its completion rather than its beginning."]),
 ("What the Verse Does Not Say", [
  "The verse does not say how Pharaoh will lead them — whether by command, by example, or simply by being in front. It does not say whether the people will follow willingly or be driven. It does not describe the Fire, and does not say what happens to them on arrival.",
  "The verse also does not say that Pharaoh will be punished more severely than those he led, though the sūrah's treatment of leaders elsewhere implies a greater accountability. What it states is the order of arrival and the identity of the destination, and it leaves the distribution of responsibility to the reader's inference from the two verses together."]),
]),

}
