# -*- coding: utf-8 -*-
"""011.md batch K: rewrite vv 99, 100, 101, 102 (template filler).

Translations already correct; commentary only (translation=None).

Source apparatus:
  v99  -- [98-99]: the curse read either generally (Z) or as the drowning in the
          Red Sea (T; see 7:136c). wird at v98 = watering place (Z).
  v100-102 -- [100-102]: end of the narrative sequence; punishments not arbitrary
          but the result of iniquities; they wronged themselves (cf. 2:57; 9:70;
          16:33,118; 29:40; 30:9); the gods could not avail because they brought
          no benefit in this world, still less in the Hereafter (cf. 16:20); God
          destroyed the towns while they were doing wrong, and might not have had
          they reformed, as at v117.
"""

SURAH = "Hūd"
NUM = 11

SECTIONS = {

99: (None, [
 ("The Curse in This World", [
  "And they were pursued in this world by a curse. The commentators offer two readings of the pursuit. It may refer to a curse in general (Z), or specifically to their being drowned in the Red Sea (Ṭ; see 7:136). Both readings are preserved, and the verse does not choose between them.",
  "The difference matters for how the verse is read. On the general reading the curse is the lasting reputation of the people — the thing that follows them through history, the way their name is used afterwards as a term of reproach. On the specific reading it is the drowning itself, a single event that overtook them and from which none escaped. The first is a condition; the second is an occurrence. The commentators record both without preferring either, and the verse's wording supports either.",
  "The specific reading points to 7:136: So We took vengeance upon them and drowned them in the sea for their having denied Our signs and for having been heedless of them. The commentators there explain that God's taking vengeance means He punished them for their evil deeds and for their heedlessness of the signs and clear proofs of Moses' prophethood (Ṭs). The sea in that verse renders *yamm*, a word the Qur'an uses only in connection with the Mosaic narratives, and which may denote a sea of unfathomable depths or the roar and vastness of the sea (Z). On this reading the curse that pursued them is not an abstraction but a body of water that closed over them."]),
 ("The Curse in the Hereafter", [
  "And they shall be pursued on the Day of Resurrection. The verse extends the pursuit past death. Whatever followed them in this world will follow them into the next, and the continuity is stated without elaboration.",
  "This is the same movement the previous verse made with Pharaoh's leadership. There the leader went before his people on the Day of Resurrection and led them to the Fire; here the curse that pursued them in this world pursues them on the Day. In both cases the sūrah's point is that death does not interrupt the consequence. The structure established in this world — who led, who followed, what pursued them — persists into the next, and the Day is where it becomes final rather than where it begins."]),
 ("The Gift That Is Not a Gift", [
  "Evil indeed is the gift that will be offered them. The word rendered gift is ordinarily a term for favour and blessing, and its use here is ironic. What is offered to them is called by the name of a good thing, and the verse then declares it evil.",
  "The irony is the verse's method. The previous verse used a watering place — a word for relief after thirst — to name a destination of punishment. This verse uses a gift to name the same destination. Both words are borrowed from the vocabulary of provision and turned against the people who are receiving what they name. The effect is not merely rhetorical: it marks the distance between what the people expected from their course and what the course delivered.",
  "The pairing is worth holding together. A *wird* is where a traveller arrives and is relieved; a gift is what a host offers and the guest receives gladly. Both presume a relationship in which the one who provides intends the good of the one who receives. The verse takes that presumption and inverts it without comment, so that the reader is left with the words doing the work. The commentators note the severity the vocabulary produces at v98 and leave the irony at v99 to stand on the verse's own wording."]),
 ("The Two Readings of the Pursuit", [
  "The commentators' note on these verses also explains that the watering place at v98 renders *wird*, a word usually associated with the quenching of thirst, and that the choice emphasises the severity of the punishment (Z). Read together with the curse here, the two verses build a consistent picture: the people are brought to something that ought to relieve them and are instead pursued by something that does not stop.",
  "Neither verse explains the mechanism. The commentators note the vocabulary and its effect, and leave the theology to the reader. What is stated is the sequence — led, brought, pursued — and the fact that each term is drawn from a register of care while describing the opposite."]),
 ("What the Verse Does Not Say", [
  "The verse does not say how long the pursuit lasts, and does not say whether it is continuous or periodic. It does not describe the curse, and does not say who pronounces it or upon whom specifically — whether upon Pharaoh, upon the notables, or upon all who followed.",
  "The verse also does not say that the curse can be lifted. It states the pursuit in this world and in the next without qualification, and does not offer the possibility of relief that the preceding prophets' accounts offered to those who repented. The sūrah has been careful throughout to distinguish those who were warned and refused from those who were warned and accepted, and this verse concerns the first group only."]),
]),

100: (None, [
 ("The End of the Sequence", [
  "These are among the stories We have recounted unto thee of the towns. The commentators mark these verses as the close of the long sequence of narratives in the sūrah about the prophets sent to their communities and those communities' destruction for rejecting the message. Five cycles have been completed — Noah, Hūd, Ṣāliḥ, Lot, Shuʿayb — with the account of Moses inserted before the close.",
  "The verse steps back from the narratives and addresses the reader directly about them. It is no longer telling a story but commenting on the telling. The shift is signalled by the address: We have recounted unto thee. The recipient is the Prophet, and the verse makes explicit that what has just been narrated was narrated to him for a purpose.",
  "At 7:103 the commentators note that the command so behold how the workers of corruption fared in the end is addressed to the Prophet, indicating that these prophetic narratives were meant to give him confidence that God aids His messengers against their enemies. The same function operates here. The recounting is not archival; it is addressed to someone in a comparable position, and the point of the sequence is that the outcome has been consistent. The verse's mention of the towns is what makes the sequence concrete — these were places, not abstractions, and some of them are still standing."]),
 ("The Towns That Remain and the Towns Mown Down", [
  "Among them are some that remain and some that have been mown down. The image is agricultural: a field in which some of the crop is still standing and some has been cut. The commentators do not gloss the metaphor beyond the verse's own wording, and it is left to carry the distinction.",
  "What the distinction does is refuse the reader a single verdict on the past. Some of the towns of those peoples are still there — their ruins, their sites, the places travellers pass and recognise. Others are gone entirely, leaving nothing that marks where they stood. The sūrah has just narrated five destructions in identical terms, and now says that the physical traces of them differ. The sameness of the fate and the difference of the remains are held together without resolution.",
  "The distinction also does practical work for the reader. A town that remains can be visited; the sūrah elsewhere invites exactly that, telling the reader to travel in the land and see what became of those who denied. A town mown down cannot be visited, and its lesson has to be carried by the account rather than by the site. The verse does not say which is which, and the commentators do not supply a list, so the reader is left with the general fact: the evidence survives unevenly, and the narratives exist partly because it does."]),
 ("Why the Punishments Were Not Arbitrary", [
  "The commentators are explicit on the point that governs these verses: the punishments that befell these people were not arbitrary but were the result of the iniquities they had committed. They thus wronged themselves and left themselves liable to punishment. The commentators cite 2:57, 9:70, 16:33 and 118, 29:40, and 30:9 as parallels.",
  "The claim is that the sequence was warning, refusal, consequence — and that each step was the people's own doing up to the last. God wronged them not, because they had been given fair warning through the sending of messengers, but they wronged themselves by failing to acknowledge the clear proofs and to follow the teachings of the prophets sent to them. The commentators' insistence on this is what allows the following verses to state the destruction without qualification."]),
 ("The Possibility That Was Open", [
  "The commentators add a qualification that the verse itself does not state. God destroyed the towns while they were doing wrong, although if they had changed their ways He might not have destroyed them — as at v117: And thy Lord would never destroy the towns unjustly, while their people were reforming.",
  "This is the hinge of the sūrah's argument about punishment. The destruction was conditional on the wrongdoing, and the wrongdoing was avoidable. Every prophet in the sequence offered the same possibility and was refused. The commentators connect the general statement here to the specific promise at v117 so that the reader does not take the five destructions as evidence that destruction is inevitable, but as evidence that the warning was real and the refusal was theirs."]),
 ("What the Verse Does Not Say", [
  "The verse does not say which towns remain and which have been mown down. It does not name them, and does not say whether any of the five just narrated are among those still standing. It does not say how long the remains have stood or how long they will.",
  "The verse also does not say that the remaining towns are evidence of mercy or the mown-down towns evidence of greater severity. It records the difference without assigning it a meaning, and leaves the reader with the fact that the same fate produced different traces."]),
]),

101: (None, [
 ("We Wronged Them Not", [
  "We wronged them not, but they wronged themselves. The verse states the denial in the first person and immediately supplies the alternative. The commentators ground it in the sequence they have just described: the punishments were not arbitrary but followed from the iniquities the people had committed, and they had been given fair warning through the sending of messengers.",
  "The order of the two clauses matters. The denial comes first, and the attribution second. The verse does not begin with what the people did but with what God did not do, and then explains. The commentators cite the same parallels as at v100 — 2:57, 9:70, 16:33 and 118, 29:40, 30:9 — treating this as a settled formula across the Qur'an rather than a local claim."]),
 ("They Wronged Themselves", [
  "The commentators explain that the people wronged themselves by failing to acknowledge the clear proofs and to follow the teachings of the prophets sent to them. The wrongdoing is therefore specified: it is not general wickedness but a particular failure in response to a particular offer.",
  "This is the same charge the sūrah has been making since the beginning. Each prophet brought clear proofs, and each community refused them. The refusal was the wrongdoing, and the destruction was its consequence rather than an additional punishment imposed from outside. The verse's insistence that they wronged themselves is what makes the consequence intelligible as a consequence rather than as an affliction.",
  "The commentators' list of parallels — 2:57, 9:70, 16:33 and 118, 29:40, 30:9 — shows that this is a settled formula rather than a local argument. Wherever the Qur'an narrates a destroyed community it makes the same denial and the same attribution, and the consistency is what allows the verse to state it here in a single line without demonstration. The reader has been given the reasoning five times over in the narratives that precede; this verse is the summary of it, and the commentators cite the parallels so that the summary is recognisable as a summary."]),
 ("The Gods That Did Not Avail", [
  "And their gods whom they called upon apart from God did not avail them in the least when the Command of thy Lord came. The commentators explain the reason: these gods could not bring about any benefit for them in this world, and this would be the case even more so in the Hereafter (cf. 16:20).",
  "The argument is from the lesser to the greater. If the gods were powerless when the people had need of them in this world — where at least some aid is possible — they are certainly powerless in the Hereafter. The commentators note that the verse's point is not that the gods tried and failed but that they were never capable. The phrase did not avail them in the least excludes even a partial help.",
  "The cross-reference at 16:20 states the underlying reason: those whom they call upon apart from God create naught, and are themselves created. The commentators there draw the contrast with God, who is uncreated and therefore not created by another, and cite 37:95–96: Do you worship that which you carve, while God created you and that which you make? The incapacity of the gods is therefore not a temporary failure at the moment of need but a consequence of what they are. Something that is itself made cannot intervene on behalf of its maker, and the verse's report that they did not avail is the practical demonstration of a point the Qur'an makes elsewhere as doctrine."]),
 ("They Increased Them in Naught but Ruin", [
  "The verse adds that the gods increased them in naught but ruin. This goes beyond ineffectiveness. The gods were not merely useless at the moment of destruction; their worship contributed to the ruin.",
  "The commentators do not elaborate on the mechanism, and the verse does not explain it. What is claimed is a negative return: the devotion directed to these gods produced harm rather than nothing. The sūrah's argument against them throughout has been that they cannot help; this verse closes it by saying that reliance on them cost the people something, and that the cost was counted on the day the command came."]),
 ("What the Verse Does Not Say", [
  "The verse does not name the gods, and does not say whether they were idols, ancestors, angels, or something else. It does not say how long they had been worshipped or how the worship began. It does not say whether any of the people abandoned them before the end.",
  "The verse also does not say that the worshippers were deceived by the gods. It states that the gods did not avail and increased only ruin, and does not attribute intention to them. The failure is presented as incapacity rather than as betrayal, which is consistent with the commentators' explanation that the gods could bring about no benefit in this world at all."]),
]),

102: (None, [
 ("Such Is the Seizing", [
  "Such is the seizing of thy Lord when He seizes the towns while they are doing wrong. The verse generalises from the five narratives just completed. What happened to the peoples of Noah, Hūd, Ṣāliḥ, Lot, and Shuʿayb is presented not as five separate events but as instances of one thing.",
  "The word rendered seizing carries a sense of taking hold suddenly and completely. It is not a gradual decline or a series of misfortunes but a single act that ends the situation. The sūrah's narratives have been consistent on this: in each case the destruction came within a night, or within a cry, or within an overturning. The verse names that pattern and states that it is God's manner of dealing with towns in the condition these towns were in.",
  "The five cases supply the range. Noah's people were drowned. ʿĀd were destroyed by a wind. Thamūd were seized by the cry and found lifeless by morning. Lot's people were overthrown with stones of layered clay. Midian were seized by the cry and found prostrate in their homes. The means differ in every case, and the verse's claim is precisely that the difference does not matter — what is common is the suddenness and the completeness, and that is what the word seizing names."]),
 ("While They Are Doing Wrong", [
  "The condition attached to the seizing is the verse's most important qualification. God seizes the towns while they are doing wrong. The commentators connect this directly to v117: And thy Lord would never destroy the towns unjustly, while their people were reforming.",
  "The two verses together state the rule from both sides. Destruction comes when the wrongdoing continues; it does not come when the people are reforming. The commentators note that God destroyed the towns while they were doing wrong, although if they had changed their ways He might not have destroyed them. The seizing is therefore not a fixed decree against particular peoples but a response to a condition that the peoples themselves controlled."]),
 ("Painful, Severe", [
  "Surely His seizing is painful, severe. The two adjectives are distinct. Painful describes what it is like to undergo; severe describes its weight. The verse asserts both without qualifying either, and does not soften the claim by reference to mercy elsewhere.",
  "The commentators do not gloss the two words separately, and the verse does not explain why both are needed. What the pairing achieves is that the seizing is described both from inside and from outside — as experienced and as measured. The narratives that precede have shown both: the cry that seized a people overnight, and the morning that found them lifeless in their homes.",
  "The severity is also what distinguishes this seizing from ordinary misfortune. A town can suffer drought, defeat, or plague and continue to exist. What the verse describes ends the town. The commentators' note that the punishments were the result of iniquities the people had committed does not soften this; it explains why the severity was proportionate rather than arbitrary, and the qualification at v117 — that God would never destroy the towns unjustly while their people were reforming — is what keeps the severity within the bounds the sūrah has set for it."]),
 ("The Function of the Verse in the Sequence", [
  "The verse closes the narrative section and opens the general application. Everything before it has been particular — named peoples, named prophets, named punishments. This verse states the rule those particulars instantiate, and the verses that follow draw the consequence for the reader.",
  "The commentators treat vv 100–102 as a unit for this reason. The stories are recounted, the towns are divided into those that remain and those mown down, the injustice is denied and the self-wronging affirmed, and then the seizing is named as God's manner. The sequence moves from what happened to what it means, and this verse is where the movement completes."]),
 ("What the Verse Does Not Say", [
  "The verse does not say when the seizing will occur for any particular town. It states the condition and the manner but gives no timescale, and does not say whether the towns of the reader's own time are included.",
  "The verse also does not say that every town doing wrong will be seized. It describes God's manner when He seizes, and the condition under which the seizing has occurred in the cases narrated. The commentators' qualification — that He might not have destroyed them had they reformed — is what keeps the verse from being read as a prediction, and it is stated in their note rather than in the verse's own words."]),
]),

}
