# -*- coding: utf-8 -*-
"""Fourth mini-heading for Sūrah al-Anbiyāʾ (21) vv 20-25, bringing each section
to the file's own profile of ~1,250 words."""
SURAH = "al-Anbiyāʾ"
NUM = 21

BLOCKS = {

20: ("The Verse as a Standard for Human Worship", [
 "If the angels' worship is constitutively unavailable to human beings, the verse still functions as a standard, and its function is to fix the direction rather than the distance. The sūrah does not ask the reader to glorify without interval; it asks the reader to notice what worship looks like when it is not compromised by fatigue, resentment, or distraction, and then to ask what in his own worship is owed to those three things rather than to its object. The measure is set high precisely so that it cannot be mistaken for an achievable target, and so that falling short of it is not experienced as failure but as the ordinary condition of a creature.",
 "There is a further use to which the classical commentators put the verse. Because the angels' glorification is described as their breathing, the verse has been read as an account of what remembrance becomes when it ceases to be an exercise and becomes a disposition. The Sufi exegetes whom the commentators record elsewhere in this sūrah treat that transition as the aim of practice rather than its reward, and the verse supplies the image of what the aim looks like — not a longer list of acts but a different relation to the One who is remembered.",
 "Read this way the verse is not primarily cosmological. It is describing a mode of existence in order to make a point about worship, and the point is that worship's quality is determined by its object's inexhaustibility rather than by the worshipper's effort. A person who tires has not necessarily been inattentive; he may simply have been attending to something finite. The remedy the verse implies is not more discipline but a larger object, which is why the sūrah turns immediately to the question of what has been taken as an object in God's place.",
]),

21: ("What the Verse Does Not Argue", [
 "It is worth marking the limits of the verse's claim, because they are as instructive as the claim itself. The verse does not say that the idols do not exist; nobody in the audience supposed that the stones were unreal. It does not say that the ancestors who carved them were foolish, or that the practice is without social function. It asks one question about one capacity, and the question is narrow enough that it cannot be evaded by appealing to tradition, to sentiment, or to the usefulness of the cult.",
 "This narrowness is what makes the verse effective as an argument rather than merely as a rebuke. A broad denunciation invites a broad defence; a single precise question invites a single precise answer, and no answer is available. The commentators' glosses concentrate on exactly this point — that the verse selects the function which defines divinity and asks whether it has ever been observed — and their concentration indicates that they understood the verse's force to lie in its specificity rather than in its tone.",
 "The same method appears at verse 24, where the demand is for *burhān*, a demonstration, and at verse 30, where the appeal is to observation rather than to authority. The sūrah's polemic against idolatry is consistently conducted at the level of specific, checkable claims. This is why it can be so brief. A case built on particulars does not need the length that a case built on generalities requires, and the sūrah's treatment of idolatry is among its most compressed arguments for that reason.",
]),

22: ("The Argument Read Against Verse 21", [
 "Verses 21 and 22 are a matched pair and lose much of their force when read apart. Verse 21 asks whether gods taken from the earth can resurrect; verse 22 asks what the world would look like if there were gods other than God. The first is a question about capacity, the second about coherence, and together they close off the two routes by which polytheism might be defended — that the gods can do something, and that they can coexist.",
 "The order matters. The capacity question comes first because it is the simpler and because an audience that cannot answer it will not reach the second. Only after the gods have been shown incapable of the defining function does the verse turn to the structural argument, which is more demanding and more general. The sūrah is not presenting two independent proofs but a sequence in which the second builds on the failure of the first.",
 "This sequencing also explains why the verse can move from the conditional to the doxology so abruptly. By the time *la-fasadatā* has been stated, the case is closed, and what remains is not further argument but the recognition that the alternative just refuted would have been an indignity. *Subḥāna'Llāh* is not a conclusion drawn from the argument; it is the response the argument makes appropriate, and the verse places it immediately after the conditional for that reason.",
]),

23: ("The Verse in the Sūrah's Sequence", [
 "Verse 23 sits between two arguments and belongs to both. Verse 22 has established the unity of the source of the world's order; verse 24 will demand proof from those who claim otherwise. The verse between them states the relation in which the demanding and the demanded stand to the One whose unity has just been shown, and without it the demand at verse 24 would lack its ground. One can demand proof of another only where there is a shared accountability, and the verse establishes that there is one.",
 "The commentators' attention to teleology and predestination in this verse is therefore not a digression into systematic theology but a response to the question the sequence raises. If God is not questioned about what He does, in what sense can His creatures be questioned about theirs? The classical answers differ, and the verse does not settle the difference, but the question arises from the verse's position in the argument rather than from the commentators' independent interests.",
 "Read in sequence, the verse also has a rhetorical function. It tells the audience that the demand about to be made at verse 24 is not the last word on the matter. There will be a further questioning, and it will not be conducted in the register of debate. The sūrah thereby converts what could be read as an intellectual dispute into a matter of consequence, and verse 23 is the hinge on which that conversion turns.",
]),

24: ("The Demand and the Audience's Own Scriptures", [
 "The verse's invocation of the Reminder for those before me has a specific polemical use that is easy to miss. The Meccan audience included people who knew the Torah and the Gospel by reputation and who treated both as revelations. By citing them as containing the same demand, the verse places the audience in the position of having to choose between their reverence for those scriptures and their practice at home. The choice is not forced rhetorically; it is presented as a matter of fact.",
 "Al-Rāzī's reading — that the content of the earlier Reminder, like that of the Qur'an, is that human beings should not take gods apart from Him — makes the point sharply. If the earlier scriptures say what the Qur'an says on this matter, then the audience's appeal to those scriptures is an appeal against their own practice rather than in defence of it. The verse does not need to argue for the authority of the Torah and the Gospel; it needs only to note what they contain.",
 "This is why the verse can issue its demand so plainly. It is not asking the audience to accept a new authority but to apply one they already accept. The *burhān* demanded is not a demonstration internal to Islam but the demonstration that any of the revelations would require, and the verse's confidence rests on the fact that the demand has been made before and has never been met by anyone claiming gods besides God.",
]),

25: ("Why the Verse Is Placed Here", [
 "The verse's position is argumentative rather than incidental. Four verses of demand and diagnosis precede it, and the natural objection to all four is that the Prophet ﷺ is asking his audience to abandon the religion of their fathers for something he has invented. Verse 25 removes that objection at its root by showing that what he brings is not new but is what every messenger was given, and that the religion of the fathers is the departure rather than the inheritance.",
 "The reversal is the verse's central rhetorical move. An audience that thinks of itself as conservative is told that it is the innovator, and the evidence offered is the record of the messengers rather than any claim about the present. This is why the verse gives the revealed words in the first person and traces them to every messenger without exception: the argument depends on the universality of the formula and would be weakened by any acknowledged variation in it.",
 "The verse also prepares the transition to verse 26, which records a specific departure from the formula. Having established what was revealed to every messenger, the sūrah can present the claim that the Compassionate has taken a child not as an alternative tradition but as a contradiction of the tradition both parties accept. The juxtaposition does the work that an argument would otherwise have to do, and it is the reason verse 25 is placed immediately before it.",
]),

}
