#!/usr/bin/env python3
"""
make_standard.py — build new/STANDARD.md, the small loadable style standard.

The old pipeline told the writer to "study new/007.md" — 1.65 MB, 280k words,
~413k tokens. Nothing can hold that, so every model improvised the standard and
the chapter drifted. This file is what it should have been: two measured numbers,
one complete model verse, the cross-reference tier, the anti-patterns with a
before/after pair, and the gate contract. ~2,600 words, loadable in one read.

Everything numeric here is COMPUTED from the reference, not typed by hand, so the
standard can never again contradict the exemplar. Regenerate after any repair:

    python3 scripts/make_standard.py 007
"""
import re, sys, statistics, importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("ck", ROOT / "scripts" / "check.py")
ck = importlib.util.module_from_spec(spec); spec.loader.exec_module(ck)

MODEL_VERSE = 15          # compact, 5 sections, no cross-ref tier
XREF_VERSE = 23           # shows the trailing cross-reference tier


def main(chap="007"):
    text = (ROOT / "new" / f"{chap}.md").read_text(encoding="utf-8", errors="replace")
    secs = dict(ck.verses(text))
    stats = []
    for v, b in ck.verses(text):
        heads, chunks, xref, tail, main_p = ck.parse(b)
        lens = [len(c.split()) for c in chunks if c.split()]
        e, w, info = ck.check(v, b, chap, None, need_heading=False)
        stats.append(dict(v=v, h=len(heads), med=round(statistics.median(lens)) if lens else 0,
                          words=info["words"], xref=len(xref), fails=len(e),
                          frames=info["frames"]))
    ok = [s for s in stats if not s["fails"]]
    H = [s for s in ok if s["v"] <= 117] or ok
    hs = [s["h"] for s in H]; md = [s["med"] for s in H]; wd = [s["words"] for s in H]
    xr = [s["xref"] for s in H]

    init = (ROOT / "initial" / f"{chap}.md")
    ov = 0.0
    if init.exists():
        it = init.read_text(encoding="utf-8", errors="replace")
        ov = 100 * len(ck.shingles(text) & ck.shingles(it)) / max(1, len(ck.shingles(text)))
    L = []
    A = L.append
    A(f"# Writing Standard — measured from `new/{chap}.md`\n")
    A("This file is the loadable standard. **Read this, not the reference chapter.**")
    A(f"The reference (`new/{chap}.md`, {len(text.split()):,} words) is the source of every number")
    A("below; consult a single verse of it only when you need a fuller example.\n")
    A(f"Generated by `scripts/make_standard.py` from {len(H)} verses that pass every gate.")
    A("If you repair the reference, regenerate this file — never hand-edit a rule.\n")

    A("## 1. The numbers (measured, not aspirational)\n")
    A("| property | reference range | what to aim for |")
    A("|---|---|---|")
    A(f"| bold mini-headings per verse | {min(hs)}–{max(hs)} (mean {statistics.mean(hs):.1f}) | 5–8 |")
    A(f"| median section length | {min(md)}–{max(md)} words (mean {statistics.mean(md):.0f}) | 160–220 |")
    A(f"| total words per verse | {min(wd)}–{max(wd)} (mean {statistics.mean(wd):.0f}) | 1,000–1,500 |")
    A(f"| cross-reference sections | {min(xr)}–{max(xr)} | 0–2 |")
    A(f"| reader-frame sentences | ≤1 | 0 |")
    A(f"| repeated 4-word sentence opening | ≤3 | ≤2 |")
    A(f"| verbatim overlap with the source | {ov:.2f}% | ≤{ck.MAX_OVERLAP}% |")
    A("")
    A("Hard limits enforced by `scripts/check.py` (a verse that trips one is regenerated,")
    A("not argued with):")
    A(f"median section ≥{ck.MEDIAN_MIN_FAIL}w; {ck.MIN_HEADINGS}–{ck.MAX_HEADINGS} headings;")
    A(f"{ck.MIN_WORDS}–{ck.MAX_WORDS} words; ≤{ck.MAX_FRAMES_FAIL} reader-frames;")
    A(f"≤{ck.MAX_XREF} cross-ref headings; verbatim run <{ck.MAX_RUN} words.\n")

    A("## 2. Structure of a verse file\n")
    A("```markdown")
    A(f"## Sūrah <Name> {int(chap)}:<V>")
    A("")
    A("> <the verse's translation, copied verbatim from translation/<CHAP>.txt>")
    A("")
    A("**Expanded Commentary**")
    A("")
    A("**<A heading that states the point, not a label>**")
    A("")
    A("<160–220 words of developed argument>")
    A("")
    A("**<next point>**")
    A("")
    A("<...>")
    A("```")
    A("")
    A("- Bold `**...**` lines are the mini-headings. **No `###` headings anywhere.**")
    A("- Every section is a developed argument of 130–270 words. A heading followed by")
    A("  two or three sentences is a defect: merge it into a neighbour.")
    A("- Optional second tier: 0–2 **cross-reference sections** at the end, each a PLAIN")
    A("  (non-bold) Title-Case line naming the parallel, then a short paragraph. These do")
    A("  not count as mini-headings.")
    A("- `**Expanded Commentary**` is the one fixed line; everything else is content-driven.\n")

    A("## 3. Model verse — study this, then write your own\n")
    A(f"`new/{chap}.md` verse {int(chap)}:{MODEL_VERSE}, complete ({[s['words'] for s in stats if s['v']==MODEL_VERSE][0]} words, "
      f"{[s['h'] for s in stats if s['v']==MODEL_VERSE][0]} sections, median section "
      f"{[s['med'] for s in stats if s['v']==MODEL_VERSE][0]} words):\n")
    A("```markdown")
    A(f"## Sūrah al-Aʿrāf {int(chap)}:{MODEL_VERSE}")
    A(secs[MODEL_VERSE].strip())
    A("```")
    A("")
    A("Notice: the opening section answers the verse's literal question before evaluating")
    A("it; disagreement among exegetes is reported with each side's reason and then weighed,")
    A("not just listed; every quotation carries its reference; nothing says *the readers are")
    A("shown* — the prose asserts.\n")

    A("## 4. The cross-reference tier\n")
    A(f"From verse {int(chap)}:{XREF_VERSE} — plain heading, then one short paragraph. Note it is")
    A("*appended*, not interleaved, and it never becomes the whole commentary:\n")
    b = secs[XREF_VERSE]
    heads, chunks, xref, tail, main_p = ck.parse(b)
    A("```markdown")
    A((tail or "(this verse has no tier)").strip()[:900])
    A("```")
    A("")

    A("## 5. Anti-patterns — each one is measured, so they cannot be argued away\n")
    A("| defect | why it is the drift signature | gate |")
    A("|---|---|---|")
    A("| `The sūrah's readers are shown that X` | hedges the point behind an attention-director | ≤2 per verse |")
    A(f"| 14–16 tiny sections | the actual collapse of this chapter: same words, cut finer | median section ≥{ck.MEDIAN_MIN_FAIL}w |")
    A("| same 4 words open >3 sentences | a new tic replacing the old one | FAIL above 4 |")
    A("| duplicated sentences | padding, forbidden by the no-padding rule | >1 dup = FAIL |")
    A("| `It is worth noting`, `delve`, `tapestry` … | filler with no claim in it | FAIL |")
    A("| a 25-word run from the source | paraphrase passed off as rewriting | FAIL |")
    A("| heading that names rather than claims (`**Language**`) | a label is not an argument | style |")
    A("")
    A("**Before → after**, from the repair of this very file:\n")
    A("> The sūrah's readers are shown that the pattern of judgment extends to those who")
    A("> were inside the covenant rather than outside it.")
    A("")
    A("> The pattern of judgment extends to those who were inside the covenant rather than")
    A("> outside it.")
    A("")
    A("Same claim, same evidence, one fewer hedge. Prefer that transformation everywhere.")
    A("Do not swap the frame for another fixed frame — `MONOTONY` will catch it.\n")

    A("## 6. The gate contract\n")
    A("```bash")
    A(f"python3 scripts/check.py split initial {chap}       # per-verse source chunks, once")
    A(f"python3 scripts/check.py verse {chap} <V>              # after writing each verse")
    A(f"python3 scripts/check.py chapter {chap}                # after merging")
    A(f"python3 scripts/fix_quotetags.py {chap}                 # audit: untagged quotations")
    A("```")
    A("A verse is finished when the command exits 0. Exit 1 means regenerate that verse;")
    A("it does not mean explain, negotiate, or report the failure.\n")

    out = ROOT / "new" / "STANDARD.md"
    body = "\n".join(L).replace("\n\n\n", "\n\n") + "\n"
    out.write_text(body, encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}: {len(body.split()):,} words (~{len(body)//4:,} tokens)")
    print(f"vs new/{chap}.md: {len(text.split()):,} words (~{len(text)//4:,} tokens) — "
          f"{len(text)/max(1,len(body)):.0f}× smaller")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "007"))
